export const appConfig = {
  appId: "kelly-seo",
  appName: "Kelly SEO",
  deployment: "cloud",
  locale: "auto",
  readOnly: false,
  spaceId: "",
  schemaVersion: 1,
  folder: {
    name: "Kelly SEO",
    description:
      "SEO + GEO (AI-search) + brand-entity desk: Search Console analytics, an SEO opportunities review queue, an AI-visibility tracker, a geo-qa-gated GEO content queue, and an entity/knowledge-panel readiness checklist",
    slug: "kelly-seo",
  },
  airApp: { name: "Kelly SEO", slug: "kelly-seo-app", resourceKey: "kelly-seo-app" },
  bases: [
    {
      key: "sites",
      name: "Sites",
      slug: "kelly-seo-sites",
      description: "Configured Search Console properties with 28d totals and a daily trend series",
      readLimit: 20,
      fields: [
        { slug: "site-id", name: "Site ID", type: "text", required: true },
        { slug: "ref", name: "Ref", type: "number", required: false },
        { slug: "property-url", name: "Property URL", type: "text", required: false },
        { slug: "verification-type", name: "Verification type", type: "text", required: false },
        { slug: "permission-level", name: "Permission level", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "last-sync-at", name: "Last sync at", type: "text", required: false },
        { slug: "totals", name: "Totals (JSON)", type: "longtext", required: false },
        { slug: "previous", name: "Previous totals (JSON)", type: "longtext", required: false },
        { slug: "daily", name: "Daily series (JSON)", type: "longtext", required: false },
      ],
    },
    {
      key: "queries",
      name: "Queries",
      slug: "kelly-seo-queries",
      description: "Top Search Console queries with deltas, badges, top pages, and a trend series",
      readLimit: 100,
      fields: [
        { slug: "query-id", name: "Query ID", type: "text", required: true },
        { slug: "site-id", name: "Site ID", type: "text", required: false },
        { slug: "query", name: "Query", type: "text", required: false },
        { slug: "clicks", name: "Clicks", type: "number", required: false },
        { slug: "impressions", name: "Impressions", type: "number", required: false },
        { slug: "ctr", name: "CTR", type: "number", required: false },
        { slug: "position", name: "Position", type: "number", required: false },
        { slug: "previous", name: "Previous metrics (JSON)", type: "longtext", required: false },
        { slug: "badges", name: "Badges (JSON)", type: "longtext", required: false },
        { slug: "top-pages", name: "Top pages (JSON)", type: "longtext", required: false },
        { slug: "trend", name: "Trend (JSON)", type: "longtext", required: false },
        { slug: "agent-notes", name: "Agent notes", type: "longtext", required: false },
      ],
    },
    {
      key: "pages",
      name: "Pages",
      slug: "kelly-seo-pages",
      description: "Top Search Console pages with deltas, issues, top queries, and a trend series",
      readLimit: 100,
      fields: [
        { slug: "page-id", name: "Page ID", type: "text", required: true },
        { slug: "site-id", name: "Site ID", type: "text", required: false },
        { slug: "url", name: "URL", type: "text", required: false },
        { slug: "clicks", name: "Clicks", type: "number", required: false },
        { slug: "impressions", name: "Impressions", type: "number", required: false },
        { slug: "ctr", name: "CTR", type: "number", required: false },
        { slug: "position", name: "Position", type: "number", required: false },
        { slug: "previous", name: "Previous metrics (JSON)", type: "longtext", required: false },
        { slug: "issues", name: "Issues (JSON)", type: "longtext", required: false },
        { slug: "top-queries", name: "Top queries (JSON)", type: "longtext", required: false },
        { slug: "trend", name: "Trend (JSON)", type: "longtext", required: false },
        { slug: "agent-notes", name: "Agent notes", type: "longtext", required: false },
      ],
    },
    {
      key: "opportunities",
      name: "Opportunities",
      slug: "kelly-seo-opportunities",
      description: "Agent-proposed SEO opportunities (title/meta rewrite, internal links, content brief, page fix)",
      readLimit: 100,
      fields: [
        { slug: "opportunity-id", name: "Opportunity ID", type: "text", required: true },
        { slug: "ref", name: "Ref", type: "number", required: false },
        { slug: "site-id", name: "Site ID", type: "text", required: false },
        { slug: "type", name: "Type", type: "text", required: false },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "target-page", name: "Target page", type: "text", required: false },
        { slug: "target-query", name: "Target query", type: "text", required: false },
        { slug: "reason", name: "Reason", type: "longtext", required: false },
        { slug: "expected-impact", name: "Expected impact", type: "longtext", required: false },
        { slug: "draft", name: "Draft", type: "longtext", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "agent-notes", name: "Agent notes", type: "longtext", required: false },
        { slug: "created-at", name: "Created at", type: "text", required: false },
        { slug: "decision-action", name: "Decision action", type: "text", required: false },
        { slug: "decision-note", name: "Decision note", type: "longtext", required: false },
        { slug: "decision-draft", name: "Decision draft override", type: "longtext", required: false },
        { slug: "decided-at", name: "Decided at", type: "text", required: false },
        { slug: "execution-status", name: "Execution status", type: "text", required: false },
        { slug: "execution-operation", name: "Execution operation", type: "text", required: false },
        { slug: "execution-target", name: "Execution target", type: "text", required: false },
        { slug: "execution-detail", name: "Execution detail", type: "longtext", required: false },
        { slug: "executed-at", name: "Executed at", type: "text", required: false },
      ],
    },
    {
      key: "geo-opportunities",
      name: "GEO Opportunities",
      slug: "kelly-seo-geo-opportunities",
      description: "Agent-proposed GEO content optimizations, gated by geo-qa before they can ship",
      readLimit: 100,
      fields: [
        { slug: "geo-opportunity-id", name: "GEO opportunity ID", type: "text", required: true },
        { slug: "ref", name: "Ref", type: "number", required: false },
        { slug: "type", name: "Type", type: "text", required: false },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "target-page", name: "Target page", type: "text", required: false },
        { slug: "target-prompt", name: "Target prompt", type: "text", required: false },
        { slug: "reason", name: "Reason", type: "longtext", required: false },
        { slug: "expected-impact", name: "Expected impact", type: "longtext", required: false },
        { slug: "draft", name: "Draft", type: "longtext", required: false },
        { slug: "grounding", name: "Grounding (JSON)", type: "longtext", required: false },
        { slug: "claims", name: "Claims (JSON)", type: "longtext", required: false },
        { slug: "has-schema", name: "Has schema markup", type: "text", required: false },
        { slug: "has-qa-block", name: "Has Q&A block", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "agent-notes", name: "Agent notes", type: "longtext", required: false },
        { slug: "created-at", name: "Created at", type: "text", required: false },
        { slug: "decision-action", name: "Decision action", type: "text", required: false },
        { slug: "decision-note", name: "Decision note", type: "longtext", required: false },
        { slug: "decision-draft", name: "Decision draft override", type: "longtext", required: false },
        { slug: "decided-at", name: "Decided at", type: "text", required: false },
        { slug: "execution-status", name: "Execution status", type: "text", required: false },
        { slug: "execution-operation", name: "Execution operation", type: "text", required: false },
        { slug: "execution-target", name: "Execution target", type: "text", required: false },
        { slug: "execution-detail", name: "Execution detail", type: "longtext", required: false },
        { slug: "executed-at", name: "Executed at", type: "text", required: false },
      ],
    },
    {
      key: "ai-visibility",
      name: "AI Visibility",
      slug: "kelly-seo-ai-visibility",
      description: "Tracked AI-answer-engine prompts with per-engine mentions and a visibility trend",
      readLimit: 50,
      fields: [
        { slug: "prompt-id", name: "Prompt ID", type: "text", required: true },
        { slug: "ref", name: "Ref", type: "number", required: false },
        { slug: "prompt", name: "Prompt", type: "text", required: false },
        { slug: "intent", name: "Intent", type: "text", required: false },
        { slug: "mentions", name: "Mentions (JSON)", type: "longtext", required: false },
        { slug: "trend", name: "Trend (JSON)", type: "longtext", required: false },
      ],
    },
    {
      key: "entity-signals",
      name: "Entity Signals",
      slug: "kelly-seo-entity-signals",
      description: "Brand-entity / knowledge-panel readiness checklist",
      readLimit: 50,
      fields: [
        { slug: "signal-id", name: "Signal ID", type: "text", required: true },
        { slug: "label", name: "Label", type: "text", required: false },
        { slug: "category", name: "Category", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "detail", name: "Detail", type: "longtext", required: false },
        { slug: "fix", name: "Proposed fix", type: "longtext", required: false },
      ],
    },
    {
      key: "settings",
      name: "Settings",
      slug: "kelly-seo-settings",
      description:
        "Brand, sync window/read-only config, last sync range, warnings, and AI-visibility baseline — a single settings row",
      readLimit: 20,
      fields: [
        { slug: "record-id", name: "Record ID", type: "text", required: true },
        { slug: "brand", name: "Brand", type: "text", required: false },
        { slug: "locale", name: "Locale", type: "text", required: false },
        { slug: "sync-window-days", name: "Sync window (days)", type: "number", required: false },
        { slug: "sync-row-limit", name: "Sync row limit", type: "number", required: false },
        { slug: "sync-read-only", name: "Sync read-only", type: "text", required: false },
        { slug: "range-current-start", name: "Current range start", type: "text", required: false },
        { slug: "range-current-end", name: "Current range end", type: "text", required: false },
        { slug: "range-previous-start", name: "Previous range start", type: "text", required: false },
        { slug: "range-previous-end", name: "Previous range end", type: "text", required: false },
        { slug: "warnings", name: "Warnings (JSON)", type: "longtext", required: false },
        { slug: "ai-visibility-prev-score", name: "AI visibility previous score", type: "number", required: false },
        { slug: "ai-visibility-engines", name: "AI visibility engines (JSON)", type: "longtext", required: false },
      ],
    },
  ],
  permissions: {
    readProcedures: ["nodes.list", "nodes.get", "bases.get", "records.list"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata"],
    writeProcedures: ["records.changeRequest", "bases.createChangeRequest"],
  },
};
