export const appConfig = {
  appId: "kelly-legal-firm-radar",
  appName: "Legal Firm Radar",
  deployment: "cloud",
  locale: "auto",
  readOnly: false,
  spaceId: "",
  schemaVersion: 1,
  folder: {
    name: "Legal Firm Radar",
    description:
      "Firm-level radar desk over anonymized casebase analytics: practice-area mix, case-quality indicators, lawyer capability profiles, brand proof points, and approval-gated management insights (approve / request changes / revise / block) before a report becomes a management or brand handoff",
    nodeId: "",
    slug: "kelly-legal-firm-radar",
  },
  airApp: { name: "Legal Firm Radar", slug: "kelly-legal-firm-radar-app", resourceKey: "airapp" },
  bases: [
    {
      key: "items",
      name: "Management Insights",
      slug: "kelly-legal-firm-radar-items-v1",
      description:
        "Agent-prepared management insights — practice mix, quality, talent, and brand-proof analytics facts, workflow status, and the review-queue decision on the same row",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "item-id", name: "Item ID", type: "text", required: true },
        { slug: "ref", name: "Ref", type: "text", required: false },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "category", name: "Category", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "owner", name: "Owner", type: "text", required: false },
        { slug: "risk", name: "Risk (JSON array)", type: "longtext", required: false },
        { slug: "summary", name: "Summary", type: "longtext", required: false },
        { slug: "body", name: "Body", type: "longtext", required: false },
        { slug: "recommendation", name: "Recommendation", type: "longtext", required: false },
        { slug: "proposed-action", name: "Proposed action", type: "text", required: false },
        { slug: "draft", name: "Editable draft", type: "longtext", required: false },
        { slug: "evidence", name: "Evidence (JSON array)", type: "longtext", required: false },
        { slug: "sample-size", name: "Sample size", type: "number", required: false },
        { slug: "period", name: "Reporting period", type: "text", required: false },
        { slug: "visibility", name: "Visibility", type: "text", required: false },
        { slug: "lawyer-count", name: "Lawyer count", type: "number", required: false },
        { slug: "public-citable", name: "Public-citable count", type: "number", required: false },
        { slug: "quality-indicators", name: "Quality indicators (JSON array)", type: "longtext", required: false },
        { slug: "decision-action", name: "Decision action", type: "text", required: false },
        { slug: "decision-note", name: "Decision note", type: "longtext", required: false },
        { slug: "decided-at", name: "Decided at", type: "text", required: false },
        { slug: "execution-status", name: "Execution status", type: "text", required: false },
        { slug: "execution-operation", name: "Execution operation", type: "text", required: false },
        { slug: "execution-target", name: "Execution target", type: "text", required: false },
        { slug: "execution-detail", name: "Execution detail", type: "longtext", required: false },
        { slug: "executed-at", name: "Executed at", type: "text", required: false },
        { slug: "created-at", name: "Created at", type: "text", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
    {
      key: "entities",
      name: "Practice And Lawyer Profiles",
      slug: "kelly-legal-firm-radar-entities-v1",
      description:
        "Practice-area groupings and lawyer capability profile cards derived from anonymized casebase metadata — not raw case documents",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "entity-id", name: "Entity ID", type: "text", required: true },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "meta", name: "Meta", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "owner", name: "Owner", type: "text", required: false },
        { slug: "summary", name: "Summary", type: "longtext", required: false },
        { slug: "tags", name: "Tags (JSON array)", type: "longtext", required: false },
        { slug: "metrics", name: "Metrics (JSON object)", type: "longtext", required: false },
      ],
    },
    {
      key: "checks",
      name: "Checks",
      slug: "kelly-legal-firm-radar-checks-v1",
      description:
        "Deterministic analytics QA checks for anonymization, sample size, attribution, and unsupported claims",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "check-id", name: "Check ID", type: "text", required: true },
        { slug: "label", name: "Label", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "detail", name: "Detail", type: "longtext", required: false },
        { slug: "item-id", name: "Item ID", type: "text", required: false },
        { slug: "severity", name: "Severity", type: "text", required: false },
      ],
    },
    {
      key: "settings",
      name: "Settings",
      slug: "kelly-legal-firm-radar-settings-v1",
      description: "Firm profile, analytics policy, practice taxonomy, and export preferences — a single settings row",
      nodeId: "",
      baseId: "",
      readLimit: 20,
      fields: [
        { slug: "record-id", name: "Record ID", type: "text", required: true },
        { slug: "firm-name", name: "Firm name", type: "text", required: false },
        { slug: "branch", name: "Branch", type: "text", required: false },
        {
          slug: "default-jurisdictions",
          name: "Default jurisdictions (JSON array)",
          type: "longtext",
          required: false,
        },
        { slug: "reviewer-role", name: "Reviewer role", type: "text", required: false },
        {
          slug: "require-anonymized-metadata",
          name: "Require anonymized metadata",
          type: "text",
          required: false,
        },
        {
          slug: "minimum-sample-size-for-claim",
          name: "Minimum sample size for a claim",
          type: "number",
          required: false,
        },
        {
          slug: "external-brand-claims-require-approval",
          name: "External brand claims require approval",
          type: "text",
          required: false,
        },
        { slug: "allowed-views", name: "Allowed views (JSON array)", type: "longtext", required: false },
        { slug: "practice-areas", name: "Practice areas (JSON array)", type: "longtext", required: false },
        { slug: "outcome-trends", name: "Outcome trends (JSON array)", type: "longtext", required: false },
        { slug: "export-format", name: "Export format", type: "text", required: false },
        { slug: "export-out-dir", name: "Export out dir", type: "text", required: false },
      ],
    },
  ],
  permissions: {
    readProcedures: ["nodes.list", "nodes.get", "bases.get", "records.list"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata"],
    writeProcedures: ["records.changeRequest", "bases.createChangeRequest"],
  },
};
