export const appConfig = {
  appId: "kelly-legal-precedent-desk",
  appName: "Legal Precedent Desk",
  deployment: "cloud",
  locale: "auto",
  readOnly: false,
  spaceId: "",
  schemaVersion: 1,
  folder: {
    name: "Legal Precedent Desk",
    description:
      "Precedent-research desk over internal casebase search, local court-pattern analysis, similar-case packs, citations, and approval-gated research exports (approve / request changes / revise / block) before a research pack becomes a matter-strategy input",
    nodeId: "",
    slug: "kelly-legal-precedent-desk",
  },
  airApp: { name: "Legal Precedent Desk", slug: "kelly-legal-precedent-desk-app", resourceKey: "airapp" },
  bases: [
    {
      key: "items",
      name: "Research Packs",
      slug: "kelly-legal-precedent-desk-items-v1",
      description:
        "Agent-prepared precedent research packs — matched similar cases, similarity scores, local court-pattern notes, citations, workflow status, and the review-queue decision on the same row",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "item-id", name: "Item ID", type: "text", required: true },
        { slug: "ref", name: "Ref", type: "text", required: false },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "category", name: "Category", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "owner", name: "Owner", type: "text", required: false },
        { slug: "risk", name: "Risk (JSON array)", type: "longtext", required: false },
        { slug: "summary", name: "Summary", type: "longtext", required: false },
        { slug: "body", name: "Body", type: "longtext", required: false },
        { slug: "recommendation", name: "Recommendation", type: "longtext", required: false },
        { slug: "proposed-action", name: "Proposed action", type: "text", required: false },
        { slug: "draft", name: "Editable draft", type: "longtext", required: false },
        { slug: "evidence", name: "Evidence (JSON array)", type: "longtext", required: false },
        { slug: "query", name: "Research question", type: "longtext", required: false },
        { slug: "jurisdiction", name: "Jurisdiction", type: "text", required: false },
        { slug: "match-count", name: "Match count", type: "number", required: false },
        { slug: "high-match-count", name: "High match count", type: "number", required: false },
        { slug: "top-similarity", name: "Top similarity", type: "number", required: false },
        { slug: "avg-similarity", name: "Average similarity", type: "number", required: false },
        { slug: "court-pattern", name: "Local court pattern", type: "longtext", required: false },
        { slug: "citation-count", name: "Citation count", type: "number", required: false },
        { slug: "decision-action", name: "Decision action", type: "text", required: false },
        { slug: "decision-note", name: "Decision note", type: "longtext", required: false },
        { slug: "decided-at", name: "Decided at", type: "text", required: false },
        { slug: "execution-status", name: "Execution status", type: "text", required: false },
        { slug: "execution-operation", name: "Execution operation", type: "text", required: false },
        { slug: "execution-target", name: "Execution target", type: "text", required: false },
        { slug: "execution-detail", name: "Execution detail", type: "longtext", required: false },
        { slug: "executed-at", name: "Executed at", type: "text", required: false },
        { slug: "created-at", name: "Created at", type: "text", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
    {
      key: "entities",
      name: "Precedent Library",
      slug: "kelly-legal-precedent-desk-entities-v1",
      description:
        "Issue clusters, court-pattern groups, or precedent collections grouped by issue, court, outcome, and lawyer",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "entity-id", name: "Entity ID", type: "text", required: true },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "meta", name: "Meta", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "owner", name: "Owner", type: "text", required: false },
        { slug: "summary", name: "Summary", type: "longtext", required: false },
        { slug: "tags", name: "Tags (JSON array)", type: "longtext", required: false },
        { slug: "metrics", name: "Metrics (JSON object)", type: "longtext", required: false },
      ],
    },
    {
      key: "checks",
      name: "Checks",
      slug: "kelly-legal-precedent-desk-checks-v1",
      description:
        "Deterministic precedent QA checks for citation traceability, similarity rationale, jurisdiction fit, and confidentiality limits",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "check-id", name: "Check ID", type: "text", required: true },
        { slug: "label", name: "Label", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "detail", name: "Detail", type: "longtext", required: false },
        { slug: "item-id", name: "Item ID", type: "text", required: false },
        { slug: "severity", name: "Severity", type: "text", required: false },
      ],
    },
    {
      key: "settings",
      name: "Settings",
      slug: "kelly-legal-precedent-desk-settings-v1",
      description: "Firm profile, search policy, and export preferences — a single settings row",
      nodeId: "",
      baseId: "",
      readLimit: 20,
      fields: [
        { slug: "record-id", name: "Record ID", type: "text", required: true },
        { slug: "firm-name", name: "Firm name", type: "text", required: false },
        { slug: "branch", name: "Branch", type: "text", required: false },
        {
          slug: "default-jurisdictions",
          name: "Default jurisdictions (JSON array)",
          type: "longtext",
          required: false,
        },
        { slug: "reviewer-role", name: "Reviewer role", type: "text", required: false },
        { slug: "default-jurisdiction", name: "Default jurisdiction", type: "text", required: false },
        { slug: "minimum-similarity-score", name: "Minimum similarity score", type: "number", required: false },
        { slug: "require-source-case-ids", name: "Require source case ids", type: "text", required: false },
        { slug: "quote-limit-words", name: "Quote limit words", type: "number", required: false },
        { slug: "export-format", name: "Export format", type: "text", required: false },
        { slug: "export-out-dir", name: "Export out dir", type: "text", required: false },
      ],
    },
  ],
  permissions: {
    readProcedures: ["nodes.list", "nodes.get", "bases.get", "records.list"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata"],
    writeProcedures: ["records.changeRequest", "bases.createChangeRequest"],
  },
};
