export const appConfig = {
  appId: "kelly-campaigns",
  appName: "Kelly Campaigns",
  deployment: "cloud",
  locale: "auto",
  readOnly: false,
  spaceId: "",
  schemaVersion: 1,
  folder: {
    name: "Kelly Campaigns",
    description: "Outbound email-marketing desk built on the SEND discipline",
    slug: "kelly-campaigns",
  },
  airApp: { name: "Kelly Campaigns", slug: "kelly-campaigns-app", resourceKey: "kelly-campaigns-app" },
  bases: [
    {
      key: "segments",
      name: "Segments",
      slug: "kelly-campaigns-segments",
      description: "Audience segments and their size",
      readLimit: 50,
      fields: [
        { slug: "segment-id", name: "Segment ID", type: "text", required: true },
        { slug: "name", name: "Name", type: "text", required: false },
        { slug: "description", name: "Description", type: "longtext", required: false },
        { slug: "audience-size", name: "Audience size", type: "number", required: false },
      ],
    },
    {
      key: "sends",
      name: "Sends",
      slug: "kelly-campaigns-sends",
      description: "Campaign/newsletter/sequence sends under human review",
      readLimit: 100,
      fields: [
        { slug: "send-id", name: "Send ID", type: "text", required: true },
        { slug: "ref", name: "Ref", type: "number", required: false },
        { slug: "type", name: "Type", type: "text", required: false },
        { slug: "phase", name: "Phase", type: "text", required: false },
        { slug: "from-identity-id", name: "From identity", type: "text", required: false },
        { slug: "subject", name: "Subject", type: "text", required: false },
        { slug: "preview-text", name: "Preview text", type: "text", required: false },
        { slug: "segment-id", name: "Segment", type: "text", required: false },
        { slug: "audience-size", name: "Audience size", type: "number", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "proposed-action", name: "Proposed action", type: "text", required: false },
        { slug: "risk", name: "Risk", type: "text", required: false },
        { slug: "send-at", name: "Send at", type: "text", required: false },
        { slug: "deliverability", name: "Deliverability", type: "longtext", required: false },
        { slug: "subject-variants", name: "Subject A/B variants", type: "longtext", required: false },
        { slug: "chosen-variant", name: "Chosen variant", type: "text", required: false },
        { slug: "reason", name: "Reason", type: "longtext", required: false },
        { slug: "body", name: "Body", type: "longtext", required: false },
        { slug: "target-addresses", name: "Explicit target addresses", type: "longtext", required: false },
        { slug: "performance", name: "Performance", type: "longtext", required: false },
        { slug: "quality-gate", name: "Quality gate (EQS)", type: "longtext", required: false },
        { slug: "created-at", name: "Created at", type: "text", required: false },
        { slug: "decision-note", name: "Decision note", type: "longtext", required: false },
        { slug: "decided-at", name: "Decided at", type: "text", required: false },
      ],
    },
    {
      key: "suppression",
      name: "Suppression",
      slug: "kelly-campaigns-suppression",
      description: "Consent/suppression list: recipients or segments removed by unsubscribe/bounce/complaint",
      readLimit: 100,
      fields: [
        { slug: "entry-id", name: "Entry ID", type: "text", required: true },
        { slug: "address", name: "Address", type: "text", required: false },
        { slug: "segment-id", name: "Segment", type: "text", required: false },
        { slug: "reason", name: "Reason", type: "text", required: false },
        { slug: "note", name: "Note", type: "longtext", required: false },
        { slug: "suppressed-at", name: "Suppressed at", type: "text", required: false },
        { slug: "source", name: "Source", type: "text", required: false },
      ],
    },
    {
      key: "settings",
      name: "Settings",
      slug: "kelly-campaigns-settings",
      description: "Operator/brand/ESP profile, sending policy, list health, and the agent lock",
      readLimit: 20,
      fields: [
        { slug: "record-id", name: "Record ID", type: "text", required: true },
        { slug: "kind", name: "Kind", type: "text", required: true },
        { slug: "name", name: "Name", type: "text", required: false },
        { slug: "payload", name: "Payload", type: "longtext", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
  ],
  permissions: {
    readProcedures: ["nodes.list", "nodes.get", "bases.get", "records.list"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata"],
    writeProcedures: ["records.changeRequest", "bases.createChangeRequest"],
  },
};
