export const appConfig = {
  appId: "kelly-portrait-retouch",
  appName: "Kelly Portrait Retouch",
  deployment: "cloud",
  locale: "auto",
  readOnly: false,
  spaceId: "",
  schemaVersion: 1,
  folder: {
    name: "Kelly Portrait Retouch",
    description: "Natural portrait retouch jobs, reviewable candidates, and non-secret workflow settings",
    slug: "kelly-portrait-retouch",
  },
  airApp: {
    name: "Kelly Portrait Retouch",
    slug: "kelly-portrait-retouch-app",
    resourceKey: "kelly-portrait-retouch-app",
  },
  bases: [
    {
      key: "jobs",
      name: "Retouch Jobs",
      slug: "kelly-portrait-retouch-jobs",
      description: "One row per non-destructive portrait processing request",
      readLimit: 100,
      fields: [
        { slug: "job-id", name: "Job ID", type: "text", required: true },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "source-label", name: "Source label", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "created-at", name: "Created at", type: "text", required: false },
        { slug: "source-sha256", name: "Source SHA-256", type: "text", required: false },
        { slug: "idempotency-key", name: "Idempotency key", type: "text", required: false },
        { slug: "run-id", name: "Agent run ID", type: "text", required: false },
        { slug: "candidate-count", name: "Candidate count", type: "number", required: false },
      ],
    },
    {
      key: "candidates",
      name: "Candidates",
      slug: "kelly-portrait-retouch-candidates",
      description: "Candidate provenance, naturalness checks, and human verdicts; binary images live in Drive",
      readLimit: 100,
      fields: [
        { slug: "candidate-id", name: "Candidate ID", type: "text", required: true },
        { slug: "job-id", name: "Job ID", type: "text", required: true },
        { slug: "ref", name: "Review ref", type: "number", required: false },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "preset", name: "Preset", type: "text", required: false },
        { slug: "strength", name: "Strength", type: "number", required: false },
        { slug: "face-count", name: "Face count", type: "number", required: false },
        { slug: "source-label", name: "Source label", type: "text", required: false },
        { slug: "output-label", name: "Output label", type: "text", required: false },
        { slug: "source-asset-id", name: "Source asset ID", type: "text", required: false },
        { slug: "output-asset-id", name: "Output asset ID", type: "text", required: false },
        { slug: "comparison-asset-id", name: "Comparison asset ID", type: "text", required: false },
        { slug: "checks", name: "Checks (JSON)", type: "longtext", required: false },
        { slug: "review-version", name: "Review version", type: "number", required: false },
        { slug: "decision-action", name: "Decision action", type: "text", required: false },
        { slug: "decision-comment", name: "Decision comment", type: "longtext", required: false },
        { slug: "decided-at", name: "Decided at", type: "text", required: false },
      ],
    },
    {
      key: "settings",
      name: "Settings",
      slug: "kelly-portrait-retouch-settings",
      description: "Structured non-secret defaults, onboarding version, and privacy policy",
      readLimit: 20,
      fields: [
        { slug: "record-id", name: "Record ID", type: "text", required: true },
        { slug: "onboarding-version", name: "Onboarding version", type: "number", required: false },
        { slug: "completed-at", name: "Completed at", type: "text", required: false },
        { slug: "default-preset", name: "Default preset", type: "text", required: false },
        { slug: "default-strength", name: "Default strength", type: "number", required: false },
        { slug: "metadata-policy", name: "Metadata policy", type: "text", required: false },
        { slug: "external-upload-policy", name: "External upload policy", type: "text", required: false },
        { slug: "overwrite-policy", name: "Overwrite policy", type: "text", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
  ],
  permissions: {
    readProcedures: ["nodes.list", "nodes.get", "bases.get", "records.list", "records.get", "assets.get"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata"],
    writeProcedures: ["records.changeRequest", "bases.createChangeRequest"],
  },
};
