export const appConfig = {
  appId: "kelly-messenger",
  appName: "Kelly Messenger",
  deployment: "cloud",
  locale: "auto",
  readOnly: false,
  spaceId: "",
  schemaVersion: 1,
  folder: {
    name: "Kelly Messenger",
    description:
      "Unified chat inbox: WhatsApp/Discord/Slack/Telegram accounts, conversations, messages, and a reply outbox",
    nodeId: "",
    slug: "kelly-messenger",
  },
  airApp: { name: "Kelly Messenger", slug: "kelly-messenger-app", resourceKey: "airapp" },
  bases: [
    {
      key: "accounts",
      name: "Accounts",
      slug: "kelly-messenger-accounts-v1",
      description: "Connected messaging accounts: platform, connector, channels to watch, and env var names for tokens",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "account-id", name: "Account ID", type: "text", required: true },
        { slug: "platform", name: "Platform", type: "text", required: false },
        { slug: "connector", name: "Connector", type: "text", required: false },
        { slug: "display-name", name: "Display name", type: "text", required: false },
        { slug: "workspace", name: "Workspace", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "channels", name: "Channels", type: "longtext", required: false },
        { slug: "bot-token-env", name: "Bot token env", type: "text", required: false },
        { slug: "user-token-env", name: "User token env", type: "text", required: false },
        { slug: "access-token-env", name: "Access token env", type: "text", required: false },
        { slug: "phone-number-id-env", name: "Phone number id env", type: "text", required: false },
        { slug: "phone-number-id", name: "Phone number id", type: "text", required: false },
        { slug: "last-sync-at", name: "Last sync at", type: "text", required: false },
      ],
    },
    {
      key: "conversations",
      name: "Conversations",
      slug: "kelly-messenger-conversations-v1",
      description: "One row per conversation across all connected accounts",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "conversation-id", name: "Conversation ID", type: "text", required: true },
        { slug: "account-id", name: "Account ID", type: "text", required: false },
        { slug: "platform", name: "Platform", type: "text", required: false },
        { slug: "kind", name: "Kind", type: "text", required: false },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "channel", name: "Channel", type: "text", required: false },
        { slug: "workspace", name: "Workspace", type: "text", required: false },
        { slug: "participants", name: "Participants", type: "longtext", required: false },
        { slug: "provider-conversation-id", name: "Provider conversation ID", type: "text", required: false },
        { slug: "suggested-reply", name: "Suggested reply", type: "longtext", required: false },
        { slug: "unread", name: "Unread", type: "text", required: false },
        { slug: "awaiting-reply", name: "Awaiting reply", type: "text", required: false },
      ],
    },
    {
      key: "messages",
      name: "Messages",
      slug: "kelly-messenger-messages-v1",
      description: "One row per message, joined onto its conversation by conversation-id",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "message-id", name: "Message ID", type: "text", required: true },
        { slug: "conversation-id", name: "Conversation ID", type: "text", required: false },
        { slug: "direction", name: "Direction", type: "text", required: false },
        { slug: "sender", name: "Sender", type: "text", required: false },
        { slug: "text", name: "Text", type: "longtext", required: false },
        { slug: "sent-at", name: "Sent at", type: "text", required: false },
        { slug: "attachment", name: "Attachment", type: "text", required: false },
      ],
    },
    {
      key: "sync_log",
      name: "Sync Log",
      slug: "kelly-messenger-sync-log-v1",
      description: "Append-only history of sync/ingest runs per account",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "sync-id", name: "Sync ID", type: "text", required: true },
        { slug: "account-id", name: "Account ID", type: "text", required: false },
        { slug: "method", name: "Method", type: "text", required: false },
        { slug: "at", name: "At", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "message", name: "Message", type: "longtext", required: false },
        { slug: "new-messages", name: "New messages", type: "number", required: false },
      ],
    },
    {
      key: "replies",
      name: "Replies",
      slug: "kelly-messenger-replies-v1",
      description: "Outgoing reply review queue: draft, decision, and send execution result",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "reply-id", name: "Reply ID", type: "text", required: true },
        { slug: "conversation-id", name: "Conversation ID", type: "text", required: false },
        { slug: "account-id", name: "Account ID", type: "text", required: false },
        { slug: "platform", name: "Platform", type: "text", required: false },
        { slug: "conversation-title", name: "Conversation title", type: "text", required: false },
        { slug: "text", name: "Text", type: "longtext", required: false },
        { slug: "note", name: "Note", type: "longtext", required: false },
        { slug: "reason", name: "Reason", type: "longtext", required: false },
        { slug: "suggested-by", name: "Suggested by", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "decision-action", name: "Decision action", type: "text", required: false },
        { slug: "decision-comment", name: "Decision comment", type: "longtext", required: false },
        { slug: "decided-at", name: "Decided at", type: "text", required: false },
        { slug: "execution-status", name: "Execution status", type: "text", required: false },
        { slug: "execution-operation", name: "Execution operation", type: "text", required: false },
        { slug: "execution-connector", name: "Execution connector", type: "text", required: false },
        { slug: "execution-target", name: "Execution target", type: "text", required: false },
        { slug: "execution-detail", name: "Execution detail", type: "longtext", required: false },
        { slug: "executed-at", name: "Executed at", type: "text", required: false },
        { slug: "created-at", name: "Created at", type: "text", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
    {
      key: "settings",
      name: "Settings",
      slug: "kelly-messenger-settings-v1",
      description: "Reply style and sync cadence, a single settings row",
      nodeId: "",
      baseId: "",
      readLimit: 20,
      fields: [
        { slug: "record-id", name: "Record ID", type: "text", required: true },
        { slug: "reply-style-tone", name: "Reply style tone", type: "text", required: false },
        { slug: "reply-style-language", name: "Reply style language", type: "text", required: false },
        { slug: "sync-default-limit", name: "Sync default limit", type: "number", required: false },
        { slug: "sync-cadence-minutes", name: "Sync cadence minutes", type: "number", required: false },
      ],
    },
  ],
  permissions: {
    readProcedures: ["nodes.list", "nodes.get", "bases.get", "records.list"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata"],
    writeProcedures: ["records.changeRequest", "bases.createChangeRequest"],
  },
};
