export const appConfig = {
  appId: "kelly-invoice-sheet",
  appName: "Kelly Invoice Sheet",
  deployment: "cloud",
  locale: "auto",
  readOnly: false,
  spaceId: "",
  schemaVersion: 1,
  folder: {
    name: "Kelly Invoice Sheet",
    description:
      "Kelly Invoice Sheet: invoice/receipt/credit-note/statement extraction batches under human review, with field confidence, line items, and export-ready approved rows",
    nodeId: "",
    slug: "kelly-invoice-sheet",
  },
  airApp: { name: "Kelly Invoice Sheet", slug: "kelly-invoice-sheet-app", resourceKey: "airapp" },
  bases: [
    {
      key: "invoices",
      name: "Invoices",
      slug: "kelly-invoice-sheet-invoices-v1",
      description:
        "One row per extracted invoice/receipt/credit note/statement — header fields, field confidence, line items (JSON array, shares the invoice's own lifecycle), risk/warning flags, and the reviewer's decision (decision-action/decision-note/decided-at) written directly onto the same row. Written by scripts/import_batch.mjs when the agent finishes extracting a batch; status is set directly by a human decision in the app",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "invoice-id", name: "Invoice ID", type: "text", required: true },
        { slug: "ref", name: "Ref", type: "text", required: false },
        { slug: "batch-id", name: "Batch ID", type: "text", required: false },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "category", name: "Category", type: "text", required: false },
        { slug: "source-file", name: "Source file", type: "text", required: false },
        { slug: "source-path", name: "Source path", type: "text", required: false },
        { slug: "source-type", name: "Source type", type: "text", required: false },
        { slug: "source-page", name: "Source page", type: "number", required: false },
        { slug: "vendor-name", name: "Vendor name", type: "text", required: false },
        { slug: "vendor-tax-id", name: "Vendor tax ID", type: "text", required: false },
        { slug: "invoice-number", name: "Invoice number", type: "text", required: false },
        { slug: "invoice-date", name: "Invoice date", type: "text", required: false },
        { slug: "due-date", name: "Due date", type: "text", required: false },
        { slug: "currency", name: "Currency", type: "text", required: false },
        { slug: "subtotal", name: "Subtotal", type: "number", required: false },
        { slug: "tax", name: "Tax", type: "number", required: false },
        { slug: "total", name: "Total", type: "number", required: false },
        { slug: "amount-due", name: "Amount due", type: "number", required: false },
        { slug: "payment-terms", name: "Payment terms", type: "text", required: false },
        { slug: "bill-to", name: "Bill to", type: "text", required: false },
        { slug: "purchase-order", name: "Purchase order", type: "text", required: false },
        { slug: "iban-or-account-hint", name: "IBAN or account hint", type: "text", required: false },
        { slug: "confidence", name: "Confidence", type: "number", required: false },
        { slug: "field-confidence", name: "Field confidence (JSON object)", type: "longtext", required: false },
        { slug: "risk", name: "Risk (JSON array)", type: "longtext", required: false },
        { slug: "warnings", name: "Warnings (JSON array)", type: "longtext", required: false },
        { slug: "notes", name: "Notes", type: "longtext", required: false },
        { slug: "line-items", name: "Line items (JSON array)", type: "longtext", required: false },
        { slug: "proposed-action", name: "Proposed action", type: "text", required: false },
        { slug: "reason", name: "Reason", type: "longtext", required: false },
        { slug: "decision-action", name: "Decision action", type: "text", required: false },
        { slug: "decision-note", name: "Decision note", type: "longtext", required: false },
        { slug: "decided-at", name: "Decided at", type: "text", required: false },
        { slug: "created-at", name: "Created at", type: "text", required: false },
      ],
    },
    {
      key: "settings",
      name: "Settings",
      slug: "kelly-invoice-sheet-settings-v1",
      description:
        "Sanitized config summary (default currency, extraction preferences, review policy, export preferences — no secrets), one row keyed by kind",
      nodeId: "",
      baseId: "",
      readLimit: 20,
      fields: [
        { slug: "record-id", name: "Record ID", type: "text", required: true },
        { slug: "kind", name: "Kind", type: "text", required: true },
        { slug: "payload", name: "Payload (JSON object)", type: "longtext", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
  ],
  permissions: {
    readProcedures: ["nodes.list", "nodes.get", "bases.get", "records.list"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata"],
    writeProcedures: ["records.changeRequest", "bases.createChangeRequest"],
  },
};
