// Kelly Drama's Busabase resource map. One workspace = exactly one drama
// project (series bible + characters + relationships + episodes + storyboard
// shots + review tasks) — the retired local-file app's "library of many
// projects with a project switcher" was vestigial (the UI only ever showed
// the single active project) and is dropped here, same as every other
// converted skill models one workspace per AirApp instance. `readLimit` stays
// <= 100 everywhere per the migration recipe.
//
// Binary media (character reference-card images, character reference-voice
// samples, shot storyboard images/videos) are NOT stored as Base fields —
// they are real Busabase Drive Asset uploads via busabase-sdk's `assets`
// client (createUploadUrl -> PUT bytes -> confirm), and only the returned
// `assetId` is stored as a text field on the owning record. See
// js/drama-client.js for the upload/read helpers and references/ui-schema.md
// for the field <-> asset mapping.
export const appConfig = {
  appId: "kelly-drama",
  appName: "Kelly Drama",
  deployment: "cloud",
  locale: "auto",
  readOnly: false,
  spaceId: "",
  schemaVersion: 1,
  folder: {
    name: "Kelly Drama",
    description: "Short-drama workspace: series bible, characters, relationships, episodes, and storyboard shots",
    slug: "kelly-drama",
  },
  airApp: { name: "Kelly Drama", slug: "kelly-drama-app", resourceKey: "kelly-drama-app" },
  bases: [
    {
      key: "project",
      name: "Project",
      slug: "kelly-drama-project",
      description: "Single-row series bible + visual bible + paired HyperFrame project link",
      readLimit: 5,
      fields: [
        { slug: "project-id", name: "Project ID", type: "text", required: true },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "logline", name: "Logline", type: "longtext", required: false },
        { slug: "genre", name: "Genre", type: "text", required: false },
        { slug: "platform", name: "Platform", type: "text", required: false },
        { slug: "format", name: "Format", type: "text", required: false },
        { slug: "tone", name: "Tone", type: "text", required: false },
        { slug: "audience", name: "Audience", type: "text", required: false },
        { slug: "hook-rules-json", name: "Hook rules JSON", type: "longtext", required: false },
        { slug: "world-rules-json", name: "World rules JSON", type: "longtext", required: false },
        { slug: "hyperframe-project-path", name: "HyperFrame project path", type: "text", required: false },
        { slug: "hyperframe-status-json", name: "HyperFrame status JSON", type: "longtext", required: false },
        { slug: "hyperframe-status-updated-at", name: "HyperFrame status updated at", type: "text", required: false },
        { slug: "visual-format-note", name: "Visual format note", type: "longtext", required: false },
        { slug: "visual-realism-target", name: "Visual realism target", type: "longtext", required: false },
        { slug: "visual-cinematography", name: "Visual cinematography", type: "longtext", required: false },
        { slug: "visual-color-palette", name: "Visual color palette", type: "text", required: false },
        { slug: "visual-period-detail", name: "Visual period detail", type: "longtext", required: false },
        { slug: "visual-aspect-ratio", name: "Visual aspect ratio", type: "text", required: false },
        { slug: "visual-orientation", name: "Visual orientation", type: "text", required: false },
        { slug: "visual-style-medium", name: "Visual style medium", type: "longtext", required: false },
        {
          slug: "visual-background-refs-json",
          name: "Visual background reference assets JSON",
          type: "longtext",
          required: false,
        },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
    {
      key: "settings",
      name: "Settings",
      slug: "kelly-drama-settings",
      description: "One row (record-id: config): image/video/TTS generation backend settings",
      readLimit: 5,
      fields: [
        { slug: "record-id", name: "Record ID", type: "text", required: true },
        { slug: "image-base-url", name: "Image base URL", type: "text", required: false },
        { slug: "image-model", name: "Image model", type: "text", required: false },
        { slug: "image-size", name: "Image size", type: "text", required: false },
        { slug: "video-draft-backend", name: "Video draft backend", type: "text", required: false },
        { slug: "video-width", name: "Video width", type: "number", required: false },
        { slug: "video-height", name: "Video height", type: "number", required: false },
        { slug: "video-fps", name: "Video fps", type: "number", required: false },
        { slug: "video-max-frames", name: "Video max frames", type: "number", required: false },
        { slug: "video-prod-backend", name: "Video prod backend", type: "text", required: false },
        { slug: "video-ark-base-url", name: "Video Ark base URL", type: "text", required: false },
        { slug: "video-ark-model", name: "Video Ark model", type: "text", required: false },
        { slug: "video-prod-resolution", name: "Video prod resolution", type: "text", required: false },
        { slug: "video-prod-ratio", name: "Video prod ratio", type: "text", required: false },
        { slug: "video-prod-watermark", name: "Video prod watermark", type: "text", required: false },
        { slug: "video-generate-audio", name: "Video generate audio", type: "text", required: false },
        { slug: "tts-backend", name: "TTS backend", type: "text", required: false },
        { slug: "tts-model", name: "TTS model", type: "text", required: false },
      ],
    },
    {
      key: "characters",
      name: "Characters",
      slug: "kelly-drama-characters",
      description: "Character library: card, three-view visual notes, voice profile, reference card + voice assets",
      readLimit: 100,
      fields: [
        { slug: "character-id", name: "Character ID", type: "text", required: true },
        { slug: "name", name: "Name", type: "text", required: false },
        { slug: "role", name: "Role", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "actor-profile", name: "Actor profile", type: "longtext", required: false },
        { slug: "card-identity", name: "Card identity", type: "longtext", required: false },
        { slug: "card-motivation", name: "Card motivation", type: "longtext", required: false },
        { slug: "card-wound", name: "Card wound", type: "longtext", required: false },
        { slug: "card-secret", name: "Card secret", type: "longtext", required: false },
        { slug: "card-arc", name: "Card arc", type: "longtext", required: false },
        { slug: "card-voice", name: "Card voice", type: "longtext", required: false },
        { slug: "visual-front", name: "Visual front", type: "longtext", required: false },
        { slug: "visual-side", name: "Visual side", type: "longtext", required: false },
        { slug: "visual-back", name: "Visual back", type: "longtext", required: false },
        { slug: "visual-wardrobe", name: "Visual wardrobe", type: "longtext", required: false },
        { slug: "visual-anchors-json", name: "Visual anchors JSON", type: "longtext", required: false },
        { slug: "visual-forbidden-drift-json", name: "Visual forbidden drift JSON", type: "longtext", required: false },
        { slug: "voice-type", name: "Voice type", type: "text", required: false },
        { slug: "voice-pace", name: "Voice pace", type: "text", required: false },
        { slug: "voice-accent", name: "Voice accent", type: "text", required: false },
        { slug: "voice-signature", name: "Voice signature", type: "text", required: false },
        { slug: "voice-casting-reference", name: "Voice casting reference", type: "text", required: false },
        { slug: "voice-sample-script", name: "Voice sample script", type: "longtext", required: false },
        { slug: "reference-card-status", name: "Reference card status", type: "text", required: false },
        { slug: "reference-card-purpose", name: "Reference card purpose", type: "text", required: false },
        { slug: "reference-card-prompt", name: "Reference card prompt", type: "longtext", required: false },
        { slug: "reference-card-asset-id", name: "Reference card asset ID", type: "text", required: false },
        { slug: "reference-card-generated-at", name: "Reference card generated at", type: "text", required: false },
        {
          slug: "reference-card-generation-json",
          name: "Reference card generation JSON",
          type: "longtext",
          required: false,
        },
        { slug: "voice-reference-status", name: "Voice reference status", type: "text", required: false },
        { slug: "voice-reference-provider", name: "Voice reference provider", type: "text", required: false },
        { slug: "voice-reference-asset-id", name: "Voice reference asset ID", type: "text", required: false },
        { slug: "voice-reference-generated-at", name: "Voice reference generated at", type: "text", required: false },
        {
          slug: "voice-reference-generation-json",
          name: "Voice reference generation JSON",
          type: "longtext",
          required: false,
        },
        { slug: "voice-candidates-json", name: "Voice candidates JSON", type: "longtext", required: false },
        { slug: "deleted", name: "Deleted", type: "text", required: false },
      ],
    },
    {
      key: "relationships",
      name: "Relationships",
      slug: "kelly-drama-relationships",
      description: "Directional character relationships: power dynamic, temperature, conflict, evidence",
      readLimit: 100,
      fields: [
        { slug: "relationship-id", name: "Relationship ID", type: "text", required: true },
        { slug: "from-character-id", name: "From character ID", type: "text", required: false },
        { slug: "to-character-id", name: "To character ID", type: "text", required: false },
        { slug: "type", name: "Type", type: "text", required: false },
        { slug: "public-status", name: "Public status", type: "longtext", required: false },
        { slug: "hidden-truth", name: "Hidden truth", type: "longtext", required: false },
        { slug: "power-dynamic", name: "Power dynamic", type: "longtext", required: false },
        { slug: "emotional-temperature", name: "Emotional temperature", type: "text", required: false },
        { slug: "conflict", name: "Conflict", type: "longtext", required: false },
        { slug: "evidence-json", name: "Evidence JSON", type: "longtext", required: false },
        { slug: "deleted", name: "Deleted", type: "text", required: false },
      ],
    },
    {
      key: "episodes",
      name: "Episodes",
      slug: "kelly-drama-episodes",
      description: "Episode ladder: promise, A/B plot, beats, cliffhanger, paired HyperFrame composition",
      readLimit: 100,
      fields: [
        { slug: "episode-id", name: "Episode ID", type: "text", required: true },
        { slug: "number", name: "Number", type: "number", required: false },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "hyperframe-composition", name: "HyperFrame composition", type: "text", required: false },
        { slug: "hyperframe-video-asset", name: "HyperFrame video asset", type: "text", required: false },
        { slug: "summary", name: "Summary", type: "longtext", required: false },
        { slug: "promise", name: "Promise", type: "longtext", required: false },
        { slug: "a-plot", name: "A-plot", type: "longtext", required: false },
        { slug: "b-plot", name: "B-plot", type: "longtext", required: false },
        { slug: "cliffhanger", name: "Cliffhanger", type: "longtext", required: false },
        { slug: "beats-json", name: "Beats JSON", type: "longtext", required: false },
        { slug: "deleted", name: "Deleted", type: "text", required: false },
      ],
    },
    {
      key: "shots",
      name: "Shots",
      slug: "kelly-drama-shots",
      description: "Storyboard shots: production sheet (camera/action/audio/continuity) + image/video candidates",
      readLimit: 100,
      fields: [
        { slug: "shot-id", name: "Shot ID", type: "text", required: true },
        { slug: "episode-id", name: "Episode ID", type: "text", required: false },
        { slug: "beat-id", name: "Beat ID", type: "text", required: false },
        { slug: "position", name: "Position", type: "number", required: false },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "duration-seconds", name: "Duration seconds", type: "number", required: false },
        { slug: "duration-preset", name: "Duration preset", type: "text", required: false },
        { slug: "aspect-ratio", name: "Aspect ratio", type: "text", required: false },
        { slug: "emotion", name: "Emotion", type: "text", required: false },
        { slug: "shot-size", name: "Shot size", type: "text", required: false },
        { slug: "camera-angle", name: "Camera angle", type: "text", required: false },
        { slug: "camera-movement", name: "Camera movement", type: "text", required: false },
        { slug: "lens", name: "Lens", type: "text", required: false },
        { slug: "characters-json", name: "Characters JSON", type: "longtext", required: false },
        { slug: "composition", name: "Composition", type: "longtext", required: false },
        { slug: "camera", name: "Camera (freeform)", type: "longtext", required: false },
        { slug: "setting", name: "Setting", type: "longtext", required: false },
        { slug: "lighting", name: "Lighting", type: "longtext", required: false },
        { slug: "action", name: "Action script", type: "longtext", required: false },
        { slug: "prompt", name: "Image prompt", type: "longtext", required: false },
        { slug: "video-prompt", name: "Video prompt", type: "longtext", required: false },
        { slug: "negative-prompt", name: "Negative prompt", type: "longtext", required: false },
        { slug: "transition-in", name: "Transition in", type: "text", required: false },
        { slug: "transition-out", name: "Transition out", type: "text", required: false },
        { slug: "silent", name: "Silent", type: "text", required: false },
        { slug: "audio-json", name: "Audio JSON", type: "longtext", required: false },
        { slug: "srt-json", name: "SRT JSON", type: "longtext", required: false },
        { slug: "continuity-json", name: "Continuity JSON", type: "longtext", required: false },
        { slug: "image-asset-id", name: "Image asset ID", type: "text", required: false },
        { slug: "image-status", name: "Image status", type: "text", required: false },
        { slug: "image-generated-at", name: "Image generated at", type: "text", required: false },
        { slug: "image-generation-json", name: "Image generation JSON", type: "longtext", required: false },
        { slug: "image-candidates-json", name: "Image candidates JSON", type: "longtext", required: false },
        { slug: "video-asset-id", name: "Video asset ID", type: "text", required: false },
        { slug: "video-status", name: "Video status", type: "text", required: false },
        { slug: "video-generated-at", name: "Video generated at", type: "text", required: false },
        { slug: "video-generation-json", name: "Video generation JSON", type: "longtext", required: false },
        { slug: "video-candidates-json", name: "Video candidates JSON", type: "longtext", required: false },
        { slug: "deleted", name: "Deleted", type: "text", required: false },
      ],
    },
    {
      key: "tasks",
      name: "Tasks",
      slug: "kelly-drama-tasks",
      description: "Freeform human/agent review tasks (@ai notes, missing-field follow-ups)",
      readLimit: 100,
      fields: [
        { slug: "task-id", name: "Task ID", type: "text", required: true },
        { slug: "kind", name: "Kind", type: "text", required: false },
        { slug: "target-id", name: "Target ID", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "note", name: "Note", type: "longtext", required: false },
        { slug: "deleted", name: "Deleted", type: "text", required: false },
      ],
    },
  ],
  permissions: {
    readProcedures: ["nodes.list", "nodes.get", "bases.get", "records.list"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata"],
    writeProcedures: ["records.changeRequest", "bases.createChangeRequest"],
  },
};
