export const appConfig = {
  appId: "kelly-devops",
  appName: "Kelly DevOps",
  deployment: "cloud",
  locale: "auto",
  readOnly: false,
  spaceId: "",
  schemaVersion: 1,
  folder: {
    name: "Kelly DevOps",
    description:
      "Product-fleet ops desk: service health, SSL/domain/key expiries, cloud spend, and an action review queue",
    nodeId: "",
    slug: "kelly-devops",
  },
  airApp: { name: "Kelly DevOps", slug: "kelly-devops-app", resourceKey: "airapp" },
  bases: [
    {
      key: "services",
      name: "Services",
      slug: "kelly-devops-services-v1",
      description: "Monitored endpoints: roster plus the latest HTTP/TLS check result",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "service-id", name: "Service ID", type: "text", required: true },
        { slug: "name", name: "Name", type: "text", required: false },
        { slug: "product", name: "Product", type: "text", required: false },
        { slug: "url", name: "URL", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "latency-ms", name: "Latency ms", type: "number", required: false },
        { slug: "uptime-7d", name: "Uptime 7d", type: "number", required: false },
        { slug: "ssl-issuer", name: "SSL issuer", type: "text", required: false },
        { slug: "ssl-valid-to", name: "SSL valid to", type: "text", required: false },
        { slug: "last-check-at", name: "Last check at", type: "text", required: false },
        { slug: "history", name: "History", type: "longtext", required: false },
        { slug: "meta", name: "Meta", type: "longtext", required: false },
        { slug: "warnings", name: "Warnings", type: "longtext", required: false },
      ],
    },
    {
      key: "expiries",
      name: "Expiries",
      slug: "kelly-devops-expiries-v1",
      description: "One ledger row per domain, API key rotation, or plan renewal (SSL certs are derived from Services)",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "expiry-id", name: "Expiry ID", type: "text", required: true },
        { slug: "type", name: "Type", type: "text", required: false },
        { slug: "item", name: "Item", type: "text", required: false },
        { slug: "product", name: "Product", type: "text", required: false },
        { slug: "expires-on", name: "Expires on", type: "text", required: false },
        { slug: "auto-renew", name: "Auto renew", type: "text", required: false },
        { slug: "registrar", name: "Registrar", type: "text", required: false },
        { slug: "source", name: "Source", type: "text", required: false },
        { slug: "detail", name: "Detail", type: "longtext", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
    {
      key: "spend_providers",
      name: "Spend Providers",
      slug: "kelly-devops-spend-providers-v1",
      description: "Per cloud/billing provider month-to-date vs last-month spend",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "provider-id", name: "Provider ID", type: "text", required: true },
        { slug: "name", name: "Name", type: "text", required: false },
        { slug: "currency", name: "Currency", type: "text", required: false },
        { slug: "mtd", name: "MTD", type: "number", required: false },
        { slug: "last-month", name: "Last month", type: "number", required: false },
        { slug: "note", name: "Note", type: "longtext", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
    {
      key: "spend_products",
      name: "Spend Products",
      slug: "kelly-devops-spend-products-v1",
      description: "Per-product spend allocation for the same billing period",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "product-id", name: "Product ID", type: "text", required: true },
        { slug: "product", name: "Product", type: "text", required: false },
        { slug: "currency", name: "Currency", type: "text", required: false },
        { slug: "mtd", name: "MTD", type: "number", required: false },
        { slug: "last-month", name: "Last month", type: "number", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
    {
      key: "actions",
      name: "Actions",
      slug: "kelly-devops-actions-v1",
      description:
        "Agent-proposed action cards: renew domain, rotate key, investigate spend, restart service, ack incident",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "action-id", name: "Action ID", type: "text", required: true },
        { slug: "ref", name: "Ref", type: "number", required: false },
        { slug: "type", name: "Type", type: "text", required: false },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "reason", name: "Reason", type: "longtext", required: false },
        { slug: "evidence", name: "Evidence", type: "longtext", required: false },
        { slug: "plan", name: "Plan", type: "longtext", required: false },
        { slug: "target", name: "Target", type: "longtext", required: false },
        { slug: "note", name: "Note", type: "longtext", required: false },
        { slug: "created-at", name: "Created at", type: "text", required: false },
        { slug: "decision-verdict", name: "Decision verdict", type: "text", required: false },
        { slug: "decision-note", name: "Decision note", type: "longtext", required: false },
        { slug: "decided-at", name: "Decided at", type: "text", required: false },
      ],
    },
    {
      key: "events",
      name: "Events",
      slug: "kelly-devops-events-v1",
      description: "Append-only feed: check runs, incidents, expiry warnings, spend anomalies, action decisions",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "event-id", name: "Event ID", type: "text", required: true },
        { slug: "at", name: "At", type: "text", required: false },
        { slug: "severity", name: "Severity", type: "text", required: false },
        { slug: "kind", name: "Kind", type: "text", required: false },
        { slug: "message", name: "Message", type: "longtext", required: false },
        { slug: "service-id", name: "Service ID", type: "text", required: false },
      ],
    },
    {
      key: "settings",
      name: "Settings",
      slug: "kelly-devops-settings-v1",
      description:
        "Thresholds for expiry warnings, degraded latency, and spend anomaly detection, a single settings row",
      nodeId: "",
      baseId: "",
      readLimit: 20,
      fields: [
        { slug: "record-id", name: "Record ID", type: "text", required: true },
        { slug: "expiry-warning-days", name: "Expiry warning days", type: "number", required: false },
        { slug: "expiry-critical-days", name: "Expiry critical days", type: "number", required: false },
        { slug: "degraded-latency-ms", name: "Degraded latency ms", type: "number", required: false },
        { slug: "spend-anomaly-pct", name: "Spend anomaly pct", type: "number", required: false },
      ],
    },
  ],
  permissions: {
    readProcedures: ["nodes.list", "nodes.get", "bases.get", "records.list"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata"],
    writeProcedures: ["records.changeRequest", "bases.createChangeRequest"],
  },
};
