export const appConfig = {
  appId: "kelly-feedback",
  appName: "Kelly Feedback",
  deployment: "cloud",
  locale: "auto",
  readOnly: false,
  spaceId: "",
  schemaVersion: 1,
  folder: {
    name: "Kelly Feedback",
    description: "Voice-of-customer desk: raw feedback, clustered feature requests, and the roadmap decision queue",
    nodeId: "",
    slug: "kelly-feedback",
  },
  airApp: { name: "Kelly Feedback", slug: "kelly-feedback-app", resourceKey: "airapp" },
  bases: [
    {
      key: "products",
      name: "Products",
      slug: "kelly-feedback-products-v1",
      description: "Products feedback can be about",
      nodeId: "",
      baseId: "",
      readLimit: 50,
      fields: [
        { slug: "product-id", name: "Product ID", type: "text", required: true },
        { slug: "display-name", name: "Display name", type: "text", required: false },
        { slug: "tagline", name: "Tagline", type: "text", required: false },
      ],
    },
    {
      key: "sources",
      name: "Sources",
      slug: "kelly-feedback-sources-v1",
      description: "Feedback channels: email, Discord, Slack, X, app-store, survey, interview",
      nodeId: "",
      baseId: "",
      readLimit: 50,
      fields: [
        { slug: "source-id", name: "Source ID", type: "text", required: true },
        { slug: "channel", name: "Channel", type: "text", required: false },
        { slug: "name", name: "Name", type: "text", required: false },
        { slug: "collection", name: "Collection", type: "text", required: false },
        { slug: "secret-envs", name: "Secret envs", type: "longtext", required: false },
        { slug: "last-ingest-at", name: "Last ingest at", type: "text", required: false },
        { slug: "item-count", name: "Item count", type: "number", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
      ],
    },
    {
      key: "feedback",
      name: "Feedback",
      slug: "kelly-feedback-feedback-v1",
      description: "Raw feedback items normalized from every channel, one row per item",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "feedback-id", name: "Feedback ID", type: "text", required: true },
        { slug: "source-id", name: "Source ID", type: "text", required: false },
        { slug: "channel", name: "Channel", type: "text", required: false },
        { slug: "product", name: "Product", type: "text", required: false },
        { slug: "user-handle", name: "User handle", type: "text", required: false },
        { slug: "user-plan", name: "User plan", type: "text", required: false },
        { slug: "user-tenure-months", name: "User tenure months", type: "number", required: false },
        { slug: "user-weight", name: "User weight", type: "number", required: false },
        { slug: "text", name: "Text", type: "longtext", required: false },
        { slug: "sentiment", name: "Sentiment", type: "text", required: false },
        { slug: "received-at", name: "Received at", type: "text", required: false },
        { slug: "permalink", name: "Permalink", type: "text", required: false },
        { slug: "request-id", name: "Request ID", type: "text", required: false },
        { slug: "triage", name: "Triage", type: "text", required: false },
        { slug: "agent-note", name: "Agent note", type: "longtext", required: false },
      ],
    },
    {
      key: "requests",
      name: "Requests",
      slug: "kelly-feedback-requests-v1",
      description: "Clustered feature requests (frequency/weighted score are derived, not stored)",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "request-id", name: "Request ID", type: "text", required: true },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "product", name: "Product", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "trend", name: "Trend", type: "text", required: false },
        { slug: "effort-estimate", name: "Effort estimate", type: "text", required: false },
        { slug: "problem-statement", name: "Problem statement", type: "longtext", required: false },
        { slug: "spec-summary", name: "Spec summary", type: "longtext", required: false },
        { slug: "representative-feedback-ids", name: "Representative feedback IDs", type: "longtext", required: false },
        { slug: "decision-history", name: "Decision history", type: "longtext", required: false },
        { slug: "created-at", name: "Created at", type: "text", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
    {
      key: "roadmap",
      name: "Roadmap",
      slug: "kelly-feedback-roadmap-v1",
      description: "Roadmap lane items (now/next/later), read-only in the app; changed only via approved proposals",
      nodeId: "",
      baseId: "",
      readLimit: 50,
      fields: [
        { slug: "item-id", name: "Item ID", type: "text", required: true },
        { slug: "lane", name: "Lane", type: "text", required: false },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "request-id", name: "Request ID", type: "text", required: false },
        { slug: "note", name: "Note", type: "longtext", required: false },
      ],
    },
    {
      key: "proposals",
      name: "Proposals",
      slug: "kelly-feedback-proposals-v1",
      description: "Agent-proposed roadmap changes: promote / decline / merge / publish changelog",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "proposal-id", name: "Proposal ID", type: "text", required: true },
        { slug: "type", name: "Type", type: "text", required: false },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "request-id", name: "Request ID", type: "text", required: false },
        { slug: "request-ids", name: "Request IDs", type: "longtext", required: false },
        { slug: "target-lane", name: "Target lane", type: "text", required: false },
        { slug: "reason", name: "Reason", type: "longtext", required: false },
        { slug: "evidence", name: "Evidence", type: "longtext", required: false },
        { slug: "draft-kind", name: "Draft kind", type: "text", required: false },
        { slug: "draft", name: "Draft", type: "longtext", required: false },
        { slug: "review-note", name: "Review note", type: "longtext", required: false },
        { slug: "created-at", name: "Created at", type: "text", required: false },
        { slug: "decided-at", name: "Decided at", type: "text", required: false },
      ],
    },
    {
      key: "sync_log",
      name: "Sync Log",
      slug: "kelly-feedback-sync-log-v1",
      description: "Append-only history of ingest/cluster/execute runs",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "sync-id", name: "Sync ID", type: "text", required: true },
        { slug: "at", name: "At", type: "text", required: false },
        { slug: "actor", name: "Actor", type: "text", required: false },
        { slug: "action", name: "Action", type: "text", required: false },
        { slug: "detail", name: "Detail", type: "longtext", required: false },
        { slug: "count", name: "Count", type: "number", required: false },
      ],
    },
    {
      key: "settings",
      name: "Settings",
      slug: "kelly-feedback-settings-v1",
      description: "One row (record-id: config) with scoring weights and roadmap lane names",
      nodeId: "",
      baseId: "",
      readLimit: 20,
      fields: [
        { slug: "record-id", name: "Record ID", type: "text", required: true },
        { slug: "plan-weights", name: "Plan weights", type: "longtext", required: false },
        { slug: "default-weight", name: "Default weight", type: "number", required: false },
        { slug: "recency-half-life-days", name: "Recency half-life days", type: "number", required: false },
        { slug: "roadmap-lanes", name: "Roadmap lanes", type: "longtext", required: false },
      ],
    },
  ],
  permissions: {
    readProcedures: ["nodes.list", "nodes.get", "bases.get", "records.list"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata"],
    writeProcedures: ["records.changeRequest", "bases.createChangeRequest"],
  },
};
