export const appConfig = {
  appId: "kelly-inquiry",
  appName: "Kelly Inquiry",
  deployment: "cloud",
  locale: "auto",
  readOnly: false,
  spaceId: "",
  schemaVersion: 1,
  folder: {
    name: "Kelly Inquiry",
    description:
      "Inbound-inquiry reception desk: WhatsApp/Instagram/Messenger/email accounts, inquiries, product KB, quotes, and the reply/quote approval queue",
    slug: "kelly-inquiry",
  },
  airApp: { name: "Kelly Inquiry", slug: "kelly-inquiry-app", resourceKey: "kelly-inquiry-app" },
  bases: [
    {
      key: "accounts",
      name: "Accounts",
      slug: "kelly-inquiry-accounts",
      description:
        "Connected inquiry channels: WhatsApp/Instagram/Messenger/email, connector, and env var names for tokens",
      readLimit: 50,
      fields: [
        { slug: "account-id", name: "Account ID", type: "text", required: true },
        { slug: "channel", name: "Channel", type: "text", required: false },
        { slug: "connector", name: "Connector", type: "text", required: false },
        { slug: "display-name", name: "Display name", type: "text", required: false },
        { slug: "handle", name: "Handle", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "access-token-env", name: "Access token env", type: "text", required: false },
        { slug: "phone-number-id-env", name: "Phone number id env", type: "text", required: false },
        { slug: "phone-number-id", name: "Phone number id", type: "text", required: false },
        { slug: "ig-user-id-env", name: "IG user id env", type: "text", required: false },
        { slug: "page-id-env", name: "Page id env", type: "text", required: false },
        { slug: "last-sync-at", name: "Last sync at", type: "text", required: false },
      ],
    },
    {
      key: "inquiries",
      name: "Inquiries",
      slug: "kelly-inquiry-inquiries",
      description: "The sales pipeline: one row per inquiry across new/replied/quoted/negotiating/won/lost",
      readLimit: 100,
      fields: [
        { slug: "inquiry-id", name: "Inquiry ID", type: "text", required: true },
        { slug: "account-id", name: "Account ID", type: "text", required: false },
        { slug: "channel", name: "Channel", type: "text", required: false },
        { slug: "customer-name", name: "Customer name", type: "text", required: false },
        { slug: "customer-company", name: "Customer company", type: "text", required: false },
        { slug: "customer-country", name: "Customer country", type: "text", required: false },
        { slug: "customer-source", name: "Customer source", type: "text", required: false },
        { slug: "product-interest", name: "Product interest", type: "text", required: false },
        { slug: "product-ids", name: "Product IDs", type: "longtext", required: false },
        { slug: "quote-ids", name: "Quote IDs", type: "longtext", required: false },
        { slug: "stage", name: "Stage", type: "text", required: false },
        { slug: "value-estimate", name: "Value estimate", type: "number", required: false },
        { slug: "currency", name: "Currency", type: "text", required: false },
        { slug: "owner", name: "Owner", type: "text", required: false },
        { slug: "unread", name: "Unread", type: "text", required: false },
        { slug: "created-at", name: "Created at", type: "text", required: false },
        { slug: "next-follow-up", name: "Next follow-up", type: "text", required: false },
        { slug: "provider-conversation-id", name: "Provider conversation ID", type: "text", required: false },
        { slug: "suggested-reply", name: "Suggested reply", type: "longtext", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
    {
      key: "messages",
      name: "Messages",
      slug: "kelly-inquiry-messages",
      description: "One row per conversation message, joined onto its inquiry by inquiry-id",
      readLimit: 100,
      fields: [
        { slug: "message-id", name: "Message ID", type: "text", required: true },
        { slug: "inquiry-id", name: "Inquiry ID", type: "text", required: false },
        { slug: "direction", name: "Direction", type: "text", required: false },
        { slug: "sender", name: "Sender", type: "text", required: false },
        { slug: "text", name: "Text", type: "longtext", required: false },
        { slug: "sent-at", name: "Sent at", type: "text", required: false },
        { slug: "attachment", name: "Attachment", type: "text", required: false },
      ],
    },
    {
      key: "products",
      name: "Products",
      slug: "kelly-inquiry-products",
      description: "The product knowledge base: SKU, MOQ, price floors/ceilings, lead time, specs, and FAQ",
      readLimit: 100,
      fields: [
        { slug: "product-id", name: "Product ID", type: "text", required: true },
        { slug: "sku", name: "SKU", type: "text", required: false },
        { slug: "name", name: "Name", type: "text", required: false },
        { slug: "category", name: "Category", type: "text", required: false },
        { slug: "moq", name: "MOQ", type: "number", required: false },
        { slug: "price-min", name: "Price min", type: "number", required: false },
        { slug: "price-max", name: "Price max", type: "number", required: false },
        { slug: "currency", name: "Currency", type: "text", required: false },
        { slug: "lead-time-days", name: "Lead time days", type: "number", required: false },
        { slug: "specs", name: "Specs", type: "longtext", required: false },
        { slug: "faq", name: "FAQ", type: "longtext", required: false },
      ],
    },
    {
      key: "quotes",
      name: "Quotes",
      slug: "kelly-inquiry-quotes",
      description: "Quote worksheets: line items sourced from the product KB, validity, and min-price guard results",
      readLimit: 100,
      fields: [
        { slug: "quote-id", name: "Quote ID", type: "text", required: true },
        { slug: "quote-no", name: "Quote no", type: "text", required: false },
        { slug: "inquiry-id", name: "Inquiry ID", type: "text", required: false },
        { slug: "customer", name: "Customer", type: "text", required: false },
        { slug: "currency", name: "Currency", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "issue-date", name: "Issue date", type: "text", required: false },
        { slug: "valid-until", name: "Valid until", type: "text", required: false },
        { slug: "items", name: "Items", type: "longtext", required: false },
        { slug: "subtotal", name: "Subtotal", type: "number", required: false },
        { slug: "total", name: "Total", type: "number", required: false },
        { slug: "terms", name: "Terms", type: "longtext", required: false },
        { slug: "pricing-notes", name: "Pricing notes", type: "longtext", required: false },
        { slug: "pricing-alerts", name: "Pricing alerts", type: "longtext", required: false },
        { slug: "created-at", name: "Created at", type: "text", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
    {
      key: "approvals",
      name: "Approvals",
      slug: "kelly-inquiry-approvals",
      description: "The review queue: outgoing reply/quote drafts, decision, and send-execution result",
      readLimit: 100,
      fields: [
        { slug: "item-id", name: "Item ID", type: "text", required: true },
        { slug: "kind", name: "Kind", type: "text", required: false },
        { slug: "inquiry-id", name: "Inquiry ID", type: "text", required: false },
        { slug: "quote-id", name: "Quote ID", type: "text", required: false },
        { slug: "account-id", name: "Account ID", type: "text", required: false },
        { slug: "channel", name: "Channel", type: "text", required: false },
        { slug: "customer", name: "Customer", type: "text", required: false },
        { slug: "text", name: "Text", type: "longtext", required: false },
        { slug: "note", name: "Note", type: "longtext", required: false },
        { slug: "reason", name: "Reason", type: "longtext", required: false },
        { slug: "suggested-by", name: "Suggested by", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "decision-action", name: "Decision action", type: "text", required: false },
        { slug: "decision-comment", name: "Decision comment", type: "longtext", required: false },
        { slug: "decided-at", name: "Decided at", type: "text", required: false },
        { slug: "execution-status", name: "Execution status", type: "text", required: false },
        { slug: "execution-operation", name: "Execution operation", type: "text", required: false },
        { slug: "execution-connector", name: "Execution connector", type: "text", required: false },
        { slug: "execution-target", name: "Execution target", type: "text", required: false },
        { slug: "execution-detail", name: "Execution detail", type: "longtext", required: false },
        { slug: "executed-at", name: "Executed at", type: "text", required: false },
        { slug: "created-at", name: "Created at", type: "text", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
    {
      key: "sync-log",
      name: "Sync Log",
      slug: "kelly-inquiry-sync-log",
      description: "Append-only history of ingest/sync runs per account",
      readLimit: 100,
      fields: [
        { slug: "sync-id", name: "Sync ID", type: "text", required: true },
        { slug: "account-id", name: "Account ID", type: "text", required: false },
        { slug: "method", name: "Method", type: "text", required: false },
        { slug: "at", name: "At", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "message", name: "Message", type: "longtext", required: false },
        { slug: "new-messages", name: "New messages", type: "number", required: false },
      ],
    },
    {
      key: "settings",
      name: "Settings",
      slug: "kelly-inquiry-settings",
      description:
        "One row (record-id: config) with quote defaults, follow-up SLA, reply style, and the product KB source",
      readLimit: 20,
      fields: [
        { slug: "record-id", name: "Record ID", type: "text", required: true },
        { slug: "quote-defaults", name: "Quote defaults", type: "longtext", required: false },
        { slug: "follow-up", name: "Follow-up", type: "longtext", required: false },
        { slug: "reply-style", name: "Reply style", type: "longtext", required: false },
        { slug: "kb-source-path", name: "KB source path", type: "text", required: false },
      ],
    },
  ],
  permissions: {
    readProcedures: ["nodes.list", "nodes.get", "bases.get", "records.list"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata"],
    writeProcedures: ["records.changeRequest", "bases.createChangeRequest"],
  },
};
