export const appConfig = {
  appId: "kelly-listing",
  appName: "Kelly Listing",
  deployment: "cloud",
  locale: "auto",
  readOnly: false,
  spaceId: "",
  schemaVersion: 1,
  folder: {
    name: "Kelly Listing",
    description:
      "Listing factory desk: product library, platform drafts, compliance checks, claims registry, and a review queue",
    nodeId: "",
    slug: "kelly-listing",
  },
  bases: [
    {
      key: "products",
      name: "Products",
      slug: "kelly-listing-products-v1",
      description: "Product source-material library referenced by platform drafts",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "product-id", name: "Product ID", type: "text", required: true },
        { slug: "ref", name: "Ref", type: "number", required: false },
        { slug: "name", name: "Name", type: "text", required: false },
        { slug: "sku", name: "SKU", type: "text", required: false },
        { slug: "category", name: "Category", type: "text", required: false },
        { slug: "source", name: "Source", type: "text", required: false },
        { slug: "platforms", name: "Platforms", type: "longtext", required: false },
        { slug: "locales", name: "Locales", type: "longtext", required: false },
        { slug: "specs", name: "Specifications", type: "longtext", required: false },
        { slug: "features", name: "Feature list", type: "longtext", required: false },
        { slug: "keywords", name: "Target keywords", type: "longtext", required: false },
        { slug: "images", name: "Image checklist", type: "longtext", required: false },
        { slug: "notes", name: "Notes", type: "longtext", required: false },
        { slug: "created-at", name: "Created at", type: "text", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
    {
      key: "drafts",
      name: "Drafts",
      slug: "kelly-listing-drafts-v1",
      description:
        "Platform listing drafts — structured fields, workflow status, and the review-queue decision on the same row",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "draft-id", name: "Draft ID", type: "text", required: true },
        { slug: "ref", name: "Ref", type: "number", required: false },
        { slug: "product-id", name: "Product ID", type: "text", required: false },
        { slug: "platform", name: "Platform", type: "text", required: false },
        { slug: "locale", name: "Locale", type: "text", required: false },
        { slug: "variant-group", name: "Variant group", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "compliance-score", name: "Compliance score", type: "number", required: false },
        { slug: "keyword-strategy", name: "Keyword strategy", type: "longtext", required: false },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "subtitle", name: "Subtitle", type: "text", required: false },
        { slug: "bullets", name: "Bullet points", type: "longtext", required: false },
        { slug: "description", name: "Description", type: "longtext", required: false },
        { slug: "search-terms", name: "Backend search terms", type: "longtext", required: false },
        { slug: "seo-title", name: "SEO title", type: "text", required: false },
        { slug: "seo-description", name: "SEO description", type: "longtext", required: false },
        { slug: "selling-points", name: "Selling points", type: "longtext", required: false },
        { slug: "aplus-outline", name: "A+ content outline", type: "longtext", required: false },
        { slug: "item-specifics", name: "Item specifics", type: "longtext", required: false },
        { slug: "compliance-summary", name: "Compliance summary", type: "longtext", required: false },
        { slug: "suggestions", name: "Agent suggestions", type: "longtext", required: false },
        { slug: "decision-action", name: "Decision action", type: "text", required: false },
        { slug: "decision-note", name: "Decision note", type: "longtext", required: false },
        { slug: "decided-at", name: "Decided at", type: "text", required: false },
        { slug: "execution-status", name: "Execution status", type: "text", required: false },
        { slug: "execution-operation", name: "Execution operation", type: "text", required: false },
        { slug: "execution-target", name: "Execution target", type: "text", required: false },
        { slug: "execution-detail", name: "Execution detail", type: "longtext", required: false },
        { slug: "executed-at", name: "Executed at", type: "text", required: false },
        { slug: "created-at", name: "Created at", type: "text", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
    {
      key: "checks",
      name: "Checks",
      slug: "kelly-listing-checks-v1",
      description: "Per-draft, per-rule compliance check results",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "check-id", name: "Check ID", type: "text", required: true },
        { slug: "draft-id", name: "Draft ID", type: "text", required: false },
        { slug: "rule-id", name: "Rule ID", type: "text", required: false },
        { slug: "severity", name: "Severity", type: "text", required: false },
        { slug: "result", name: "Result", type: "text", required: false },
        { slug: "evidence", name: "Evidence", type: "longtext", required: false },
        { slug: "ref-rules", name: "Referenced banned-word rules", type: "longtext", required: false },
        { slug: "ref-claims", name: "Referenced claims", type: "longtext", required: false },
        { slug: "checked-at", name: "Checked at", type: "text", required: false },
      ],
    },
    {
      key: "claims",
      name: "Claims",
      slug: "kelly-listing-claims-v1",
      description: "Compliance registry — approved marketing claims and rejected claims",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "claim-id", name: "Claim ID", type: "text", required: true },
        { slug: "text", name: "Claim", type: "longtext", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "category", name: "Category", type: "text", required: false },
        { slug: "substantiation", name: "Substantiation", type: "longtext", required: false },
        { slug: "evidence", name: "Evidence", type: "longtext", required: false },
        { slug: "approved-by", name: "Approved by", type: "text", required: false },
        { slug: "approved-at", name: "Approved at", type: "text", required: false },
        { slug: "notes", name: "Notes", type: "longtext", required: false },
        { slug: "created-at", name: "Created at", type: "text", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
    {
      key: "claim_rules",
      name: "Claim Rules",
      slug: "kelly-listing-claim-rules-v1",
      description: "Compliance registry — banned-word / restricted-phrase rules",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "rule-id", name: "Rule ID", type: "text", required: true },
        { slug: "phrase", name: "Phrase", type: "text", required: false },
        { slug: "type", name: "Type", type: "text", required: false },
        { slug: "severity", name: "Severity", type: "text", required: false },
        { slug: "reason", name: "Reason", type: "longtext", required: false },
        { slug: "alternative", name: "Suggested alternative", type: "longtext", required: false },
        { slug: "created-at", name: "Created at", type: "text", required: false },
      ],
    },
    {
      key: "settings",
      name: "Settings",
      slug: "kelly-listing-settings-v1",
      description:
        "Seller profile, per-platform rule sets, banned words, and export preferences — a single settings row",
      nodeId: "",
      baseId: "",
      readLimit: 20,
      fields: [
        { slug: "record-id", name: "Record ID", type: "text", required: true },
        { slug: "seller-brand", name: "Brand", type: "text", required: false },
        { slug: "seller-entity", name: "Entity", type: "text", required: false },
        { slug: "seller-tone", name: "Tone", type: "text", required: false },
        { slug: "locales", name: "Locales", type: "longtext", required: false },
        { slug: "platforms", name: "Platforms", type: "longtext", required: false },
        { slug: "banned-words", name: "Banned words", type: "longtext", required: false },
        { slug: "competitor-brands", name: "Competitor brands", type: "longtext", required: false },
        { slug: "keyword-stuffing-max-repeats", name: "Keyword repeat threshold", type: "number", required: false },
        { slug: "allowed-all-caps", name: "Allowed all-caps terms", type: "longtext", required: false },
        { slug: "export-format", name: "Export format", type: "text", required: false },
        { slug: "export-out-dir", name: "Export out dir", type: "text", required: false },
        { slug: "publish-handoff-to-agent", name: "Handoff to agent", type: "text", required: false },
        { slug: "publish-requires-approval", name: "Requires approval", type: "text", required: false },
      ],
    },
  ],
  permissions: {
    readProcedures: ["nodes.list", "nodes.get", "bases.get", "records.list"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata"],
    writeProcedures: ["records.changeRequest", "bases.createChangeRequest"],
  },
};
