export const appConfig = {
  appId: "kelly-finance",
  appName: "Kelly Finance",
  deployment: "cloud",
  locale: "auto",
  readOnly: false,
  spaceId: "",
  schemaVersion: 1,
  folder: {
    name: "Kelly Finance",
    description:
      "Kelly Finance: a review workspace for a three-statement financial model — the current model snapshot (company/currency/periods/workbook), its model-quality check queue (balance-sheet ties, cash roll-forward, formula reviews), and sanitized settings",
    nodeId: "",
    slug: "kelly-finance",
  },
  bases: [
    {
      key: "model",
      name: "Model",
      slug: "kelly-finance-model-v1",
      description:
        "One row per model run (usually just the current run, record-id 'current') — company, currency, display unit, model purpose, the forecast periods array, headline metrics, warnings, and the generated workbook's path/tab contract. Written by scripts/build_three_statement_model.mjs after the Python starter-model script runs, or by an agent that has reviewed a real workbook",
      nodeId: "",
      baseId: "",
      readLimit: 20,
      fields: [
        { slug: "model-id", name: "Model ID", type: "text", required: true },
        { slug: "snapshot-id", name: "Snapshot ID", type: "text", required: false },
        { slug: "generated-at", name: "Generated at", type: "text", required: false },
        { slug: "source", name: "Source", type: "text", required: false },
        { slug: "company", name: "Company", type: "text", required: false },
        { slug: "currency", name: "Currency", type: "text", required: false },
        { slug: "display-unit", name: "Display unit", type: "text", required: false },
        { slug: "model-purpose", name: "Model purpose", type: "text", required: false },
        { slug: "periods", name: "Periods (JSON array)", type: "longtext", required: false },
        { slug: "revenue-cagr", name: "Revenue CAGR", type: "number", required: false },
        { slug: "ending-cash", name: "Ending cash", type: "number", required: false },
        { slug: "free-cash-flow", name: "Free cash flow", type: "number", required: false },
        { slug: "balance-check", name: "Balance check", type: "number", required: false },
        { slug: "warnings", name: "Warnings (JSON array)", type: "longtext", required: false },
        { slug: "workbook-path", name: "Workbook path", type: "text", required: false },
        { slug: "workbook-tabs", name: "Workbook tabs (JSON array)", type: "longtext", required: false },
      ],
    },
    {
      key: "checks",
      name: "Checks",
      slug: "kelly-finance-checks-v1",
      description:
        "One row per model-audit check (formula ties, model-quality issues, delivery notes) — the raw check fields plus the reviewer's decision, written directly onto the same row. Status is stored directly (set by the reviewer's decision action), not recomputed",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "check-id", name: "Check ID", type: "text", required: true },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "summary", name: "Summary", type: "text", required: false },
        { slug: "severity", name: "Severity", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "check-type", name: "Check type", type: "text", required: false },
        { slug: "evidence", name: "Evidence (JSON array)", type: "longtext", required: false },
        { slug: "proposed-action", name: "Proposed action", type: "text", required: false },
        { slug: "draft", name: "Draft", type: "longtext", required: false },
        { slug: "decision-action", name: "Decision action", type: "text", required: false },
        { slug: "decision-comment", name: "Decision comment", type: "longtext", required: false },
        { slug: "decided-at", name: "Decided at", type: "text", required: false },
        { slug: "execution-status", name: "Execution status", type: "text", required: false },
        { slug: "execution-detail", name: "Execution detail", type: "text", required: false },
        { slug: "executed-at", name: "Executed at", type: "text", required: false },
      ],
    },
    {
      key: "settings",
      name: "Settings",
      slug: "kelly-finance-settings-v1",
      description: "Sanitized config summary (company/currency defaults, no secrets), one row keyed by record-id/kind",
      nodeId: "",
      baseId: "",
      readLimit: 20,
      fields: [
        { slug: "record-id", name: "Record ID", type: "text", required: true },
        { slug: "kind", name: "Kind", type: "text", required: true },
        { slug: "payload", name: "Payload", type: "longtext", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
  ],
  permissions: {
    readProcedures: ["nodes.list", "nodes.get", "bases.get", "records.list"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata"],
    writeProcedures: ["records.changeRequest", "bases.createChangeRequest"],
  },
};
