export const appConfig = {
  appId: "kelly-standup",
  appName: "Kelly Standup",
  deployment: "cloud",
  locale: "auto",
  readOnly: false,
  spaceId: "",
  schemaVersion: 1,
  folder: {
    name: "Kelly Standup",
    description: "Team standup board: check-ins, blockers, and missing-check-in reminders",
    nodeId: "",
    slug: "kelly-standup",
  },
  bases: [
    {
      key: "members",
      name: "Members",
      slug: "kelly-standup-members-v1",
      description: "Team roster",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "member-id", name: "Member ID", type: "text", required: true },
        { slug: "name", name: "Name", type: "text", required: false },
        { slug: "role", name: "Role", type: "text", required: false },
        { slug: "timezone", name: "Timezone", type: "text", required: false },
        { slug: "channel", name: "Channel", type: "text", required: false },
        { slug: "active", name: "Active", type: "text", required: false },
        { slug: "contact-env", name: "Contact env", type: "text", required: false },
        { slug: "notes", name: "Notes", type: "longtext", required: false },
      ],
    },
    {
      key: "days",
      name: "Days",
      slug: "kelly-standup-days-v1",
      description: "One row per recorded standup day: digest paragraph and who is on leave",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "date", name: "Date", type: "text", required: true },
        { slug: "digest", name: "Digest", type: "longtext", required: false },
        { slug: "on-leave", name: "On leave", type: "longtext", required: false },
      ],
    },
    {
      key: "checkins",
      name: "Check-ins",
      slug: "kelly-standup-checkins-v1",
      description: "One row per member per day: yesterday/today/blockers/mood",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "checkin-id", name: "Check-in ID", type: "text", required: true },
        { slug: "member-id", name: "Member ID", type: "text", required: false },
        { slug: "date", name: "Date", type: "text", required: false },
        { slug: "yesterday", name: "Yesterday", type: "longtext", required: false },
        { slug: "today", name: "Today", type: "longtext", required: false },
        { slug: "blockers", name: "Blockers", type: "longtext", required: false },
        { slug: "mood", name: "Mood", type: "text", required: false },
        { slug: "submitted-at", name: "Submitted at", type: "text", required: false },
        { slug: "source", name: "Source", type: "text", required: false },
        { slug: "raw-excerpt", name: "Raw excerpt", type: "longtext", required: false },
      ],
    },
    {
      key: "blockers",
      name: "Blockers",
      slug: "kelly-standup-blockers-v1",
      description: "Blocker registry, deduplicated across days by content",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "blocker-id", name: "Blocker ID", type: "text", required: true },
        { slug: "member-id", name: "Member ID", type: "text", required: false },
        { slug: "raised-date", name: "Raised date", type: "text", required: false },
        { slug: "severity", name: "Severity", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "text", name: "Text", type: "longtext", required: false },
        { slug: "suggested-action", name: "Suggested action", type: "longtext", required: false },
        { slug: "resolved-date", name: "Resolved date", type: "text", required: false },
      ],
    },
    {
      key: "reminders",
      name: "Reminders",
      slug: "kelly-standup-reminders-v1",
      description: "Approval-gated nudges: missing check-ins and blocker escalations",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "reminder-id", name: "Reminder ID", type: "text", required: true },
        { slug: "type", name: "Type", type: "text", required: false },
        { slug: "member-id", name: "Member ID", type: "text", required: false },
        { slug: "channel", name: "Channel", type: "text", required: false },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "reason", name: "Reason", type: "longtext", required: false },
        { slug: "draft", name: "Draft", type: "longtext", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "created-at", name: "Created at", type: "text", required: false },
        { slug: "revised-at", name: "Revised at", type: "text", required: false },
        { slug: "decision-action", name: "Decision action", type: "text", required: false },
        { slug: "decision-note", name: "Decision note", type: "longtext", required: false },
        { slug: "decided-at", name: "Decided at", type: "text", required: false },
        { slug: "execution-status", name: "Execution status", type: "text", required: false },
        { slug: "execution-operations", name: "Execution operations", type: "longtext", required: false },
        { slug: "execution-detail", name: "Execution detail", type: "longtext", required: false },
        { slug: "executed-at", name: "Executed at", type: "text", required: false },
      ],
    },
    {
      key: "settings",
      name: "Settings",
      slug: "kelly-standup-settings-v1",
      description: "Team profile: name, timezone, workdays, standup questions, digest style",
      nodeId: "",
      baseId: "",
      readLimit: 20,
      fields: [
        { slug: "record-id", name: "Record ID", type: "text", required: true },
        { slug: "team-name", name: "Team name", type: "text", required: false },
        { slug: "team-timezone", name: "Team timezone", type: "text", required: false },
        { slug: "team-workdays", name: "Team workdays", type: "longtext", required: false },
        { slug: "digest-style", name: "Digest style", type: "text", required: false },
        { slug: "standup-questions", name: "Standup questions", type: "longtext", required: false },
      ],
    },
  ],
  permissions: {
    readProcedures: ["nodes.list", "nodes.get", "bases.get", "records.list"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata"],
    writeProcedures: ["records.changeRequest", "bases.createChangeRequest"],
  },
};
