export const appConfig = {
  appId: "kelly-support",
  appName: "Kelly Support",
  deployment: "cloud",
  locale: "auto",
  readOnly: false,
  spaceId: "",
  schemaVersion: 1,
  folder: {
    name: "Kelly Support",
    description: "Customer-support desk: tickets, knowledge base, and the support-qa quality gate",
    nodeId: "",
    slug: "kelly-support",
  },
  airApp: { name: "Kelly Support", slug: "kelly-support-app", resourceKey: "airapp" },
  bases: [
    {
      key: "accounts",
      name: "Accounts",
      slug: "kelly-support-accounts-v1",
      description: "Channel accounts: email, WhatsApp, web chat, contact form, WeChat",
      nodeId: "",
      baseId: "",
      readLimit: 50,
      fields: [
        { slug: "account-id", name: "Account ID", type: "text", required: true },
        { slug: "channel", name: "Channel", type: "text", required: false },
        { slug: "connector", name: "Connector", type: "text", required: false },
        { slug: "display-name", name: "Display name", type: "text", required: false },
        { slug: "handle", name: "Handle", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "access-token-env", name: "Access token env", type: "text", required: false },
        { slug: "phone-number-id-env", name: "Phone number id env", type: "text", required: false },
        { slug: "corp-secret-env", name: "Corp secret env", type: "text", required: false },
        { slug: "last-sync-at", name: "Last sync at", type: "text", required: false },
      ],
    },
    {
      key: "tickets",
      name: "Tickets",
      slug: "kelly-support-tickets-v1",
      description: "The approval queue: triaged ticket, KB-grounded draft reply, decision, and execution result",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "ticket-id", name: "Ticket ID", type: "text", required: true },
        { slug: "account-id", name: "Account ID", type: "text", required: false },
        { slug: "channel", name: "Channel", type: "text", required: false },
        { slug: "customer-name", name: "Customer name", type: "text", required: false },
        { slug: "customer-company", name: "Customer company", type: "text", required: false },
        { slug: "customer-email", name: "Customer email", type: "text", required: false },
        { slug: "customer-handle", name: "Customer handle", type: "text", required: false },
        { slug: "customer-country", name: "Customer country", type: "text", required: false },
        { slug: "customer-plan", name: "Customer plan", type: "text", required: false },
        { slug: "subject", name: "Subject", type: "text", required: false },
        { slug: "body", name: "Body", type: "longtext", required: false },
        { slug: "category", name: "Category", type: "text", required: false },
        { slug: "priority", name: "Priority", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "proposed-action", name: "Proposed action", type: "text", required: false },
        { slug: "reason", name: "Reason", type: "longtext", required: false },
        { slug: "suggested-reply", name: "Suggested reply", type: "longtext", required: false },
        { slug: "kb-refs", name: "KB refs", type: "longtext", required: false },
        { slug: "sla-policy", name: "SLA policy", type: "text", required: false },
        { slug: "sla-due-by", name: "SLA due by", type: "text", required: false },
        { slug: "sla-first-response-at", name: "SLA first response at", type: "text", required: false },
        { slug: "csat-score", name: "CSAT score", type: "number", required: false },
        { slug: "csat-comment", name: "CSAT comment", type: "longtext", required: false },
        { slug: "csat-rated-at", name: "CSAT rated at", type: "text", required: false },
        { slug: "owner", name: "Owner", type: "text", required: false },
        { slug: "unread", name: "Unread", type: "text", required: false },
        { slug: "created-at", name: "Created at", type: "text", required: false },
        { slug: "provider-conversation-id", name: "Provider conversation ID", type: "text", required: false },
        { slug: "decision-action", name: "Decision action", type: "text", required: false },
        { slug: "decision-comment", name: "Decision comment", type: "longtext", required: false },
        { slug: "decided-at", name: "Decided at", type: "text", required: false },
        { slug: "execution-status", name: "Execution status", type: "text", required: false },
        { slug: "execution-operation", name: "Execution operation", type: "text", required: false },
        { slug: "execution-connector", name: "Execution connector", type: "text", required: false },
        { slug: "execution-target", name: "Execution target", type: "text", required: false },
        { slug: "execution-tier", name: "Execution tier", type: "text", required: false },
        { slug: "execution-amount", name: "Execution amount", type: "number", required: false },
        { slug: "execution-detail", name: "Execution detail", type: "longtext", required: false },
        { slug: "executed-at", name: "Executed at", type: "text", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
    {
      key: "messages",
      name: "Messages",
      slug: "kelly-support-messages-v1",
      description: "One row per conversation message, joined onto its ticket by ticket-id",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "message-id", name: "Message ID", type: "text", required: true },
        { slug: "ticket-id", name: "Ticket ID", type: "text", required: false },
        { slug: "direction", name: "Direction", type: "text", required: false },
        { slug: "sender", name: "Sender", type: "text", required: false },
        { slug: "text", name: "Text", type: "longtext", required: false },
        { slug: "sent-at", name: "Sent at", type: "text", required: false },
        { slug: "attachment", name: "Attachment", type: "text", required: false },
      ],
    },
    {
      key: "knowledge_base",
      name: "Knowledge Base",
      slug: "kelly-support-knowledge-base-v1",
      description: "Articles and canned macros the agent cites when drafting replies",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "article-id", name: "Article ID", type: "text", required: true },
        { slug: "kind", name: "Kind", type: "text", required: false },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "body", name: "Body", type: "longtext", required: false },
        { slug: "tags", name: "Tags", type: "longtext", required: false },
        { slug: "category", name: "Category", type: "text", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
    {
      key: "sync_log",
      name: "Sync Log",
      slug: "kelly-support-sync-log-v1",
      description: "Append-only history of ticket collection runs per account",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "sync-id", name: "Sync ID", type: "text", required: true },
        { slug: "account-id", name: "Account ID", type: "text", required: false },
        { slug: "method", name: "Method", type: "text", required: false },
        { slug: "at", name: "At", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "message", name: "Message", type: "longtext", required: false },
        { slug: "new-messages", name: "New messages", type: "number", required: false },
      ],
    },
    {
      key: "settings",
      name: "Settings",
      slug: "kelly-support-settings-v1",
      description: "One row (record-id: config) with SLA policy, risk policy, reply style, and the KB source path",
      nodeId: "",
      baseId: "",
      readLimit: 20,
      fields: [
        { slug: "record-id", name: "Record ID", type: "text", required: true },
        { slug: "sla-policy", name: "SLA policy", type: "longtext", required: false },
        { slug: "risk-policy", name: "Risk policy", type: "longtext", required: false },
        { slug: "reply-style", name: "Reply style", type: "longtext", required: false },
        { slug: "kb-source-path", name: "KB source path", type: "text", required: false },
      ],
    },
  ],
  permissions: {
    readProcedures: ["nodes.list", "nodes.get", "bases.get", "records.list"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata"],
    writeProcedures: ["records.changeRequest", "bases.createChangeRequest"],
  },
};
