export const appConfig = {
  appId: "kelly-agent-builder",
  appName: "Agent Builder & Governance Console",
  deployment: "cloud",
  locale: "auto",
  readOnly: false,
  spaceId: "",
  schemaVersion: 1,
  folder: {
    name: "Kelly Agent Builder",
    description: "Mock agent config catalog and governance console",
    nodeId: "",
    slug: "kelly-agent-builder",
  },
  bases: [
    {
      key: "agents",
      name: "Agent Configs",
      slug: "kelly-agent-builder-agents-v1",
      description: "Mock agent configs and their governance status",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "agent-id", name: "Agent ID", type: "text", required: true },
        { slug: "name", name: "Name", type: "text", required: false },
        { slug: "trigger-description", name: "Trigger description", type: "longtext", required: false },
        { slug: "allowed-tools", name: "Allowed tools", type: "text", required: false },
        { slug: "approval-required", name: "Approval required", type: "text", required: false },
        { slug: "monthly-quota", name: "Monthly quota", type: "number", required: false },
        { slug: "calls-this-month", name: "Calls this month", type: "number", required: false },
        { slug: "owning-team", name: "Owning team", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "created-at", name: "Created at", type: "text", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
    {
      key: "settings",
      name: "Settings",
      slug: "kelly-agent-builder-settings-v1",
      description: "Onboarding marker and cosmetic org display config",
      nodeId: "",
      baseId: "",
      readLimit: 20,
      fields: [
        { slug: "record-id", name: "Record ID", type: "text", required: true },
        { slug: "kind", name: "Kind", type: "text", required: true },
        { slug: "name", name: "Name", type: "text", required: false },
        { slug: "payload", name: "Payload", type: "longtext", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
  ],
  permissions: {
    readProcedures: ["nodes.list", "nodes.get", "bases.get", "records.list"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata"],
    writeProcedures: ["records.changeRequest", "bases.createChangeRequest"],
  },
};
