const field = (slug, name, type = "text", required = false, options = {}) => ({
  slug,
  name,
  type,
  required,
  ...(Object.keys(options).length ? { options } : {}),
});

const choices = (...names) => ({ choices: names.map((name) => ({ id: name, name })) });
const view = (slug, name, type, config = {}) => ({
  slug,
  name,
  type,
  description: `${name} for Kelly PMO`,
  config: { filters: [], sorts: [], ...config },
});
const table = (name, visibleFieldSlugs) =>
  view(`${name.toLowerCase().replaceAll(" ", "-")}-table`, name, "table", { visibleFieldSlugs });
const kanban = (name, stackByFieldSlug, visibleFieldSlugs) =>
  view(`${name.toLowerCase().replaceAll(" ", "-")}-kanban`, name, "kanban", {
    stackByFieldSlug,
    visibleFieldSlugs,
  });
const calendar = (name, dateFieldSlug, visibleFieldSlugs) =>
  view(`${name.toLowerCase().replaceAll(" ", "-")}-calendar`, name, "calendar", {
    dateFieldSlug,
    visibleFieldSlugs,
  });
const gallery = (name, visibleFieldSlugs, coverFieldSlug = null) =>
  view(`${name.toLowerCase().replaceAll(" ", "-")}-gallery`, name, "gallery", {
    visibleFieldSlugs,
    coverFieldSlug,
    coverFit: "cover",
    cardSize: "medium",
    showFieldLabels: true,
  });
const gantt = (name, startFieldSlug, endFieldSlug, visibleFieldSlugs) =>
  view(`${name.toLowerCase().replaceAll(" ", "-")}-gantt`, name, "gantt", {
    startFieldSlug,
    endFieldSlug,
    ganttScale: "week",
    visibleFieldSlugs,
  });
const base = (key, name, description, fields, views) => ({
  key,
  name,
  slug: `kelly-pmo-${key}`,
  description,
  readLimit: 50,
  fields,
  views,
});

export const PMO_REFERENCE_TABLE_KEYS = [
  "programs",
  "project-teams",
  "projects",
  "reports",
  "special-tasks",
  "communications",
  "resources",
  "functional-groups",
  "glossary",
  "testing",
  "requirements",
  "iterations",
];

export const NATIVE_VIEW_TYPES = ["table", "gallery", "kanban", "calendar", "gantt"];

export const appConfig = {
  appId: "kelly-pmo",
  appName: "Kelly PMO",
  deployment: "cloud",
  locale: "auto",
  readOnly: false,
  spaceId: "",
  schemaVersion: 2,
  folder: {
    name: "Kelly PMO",
    slug: "kelly-pmo",
    description:
      "Complete PMO workspace for project groups, teams, plans, status reports, special tasks, communications, people, functional groups, glossary, testing, requirements, iterations, milestones, risks, and reviewable decisions.",
  },
  airApp: { name: "Kelly PMO", slug: "kelly-pmo-app", resourceKey: "kelly-pmo-app" },
  onboarding: {
    version: 2,
    completionResource: "settings",
    requiredFields: [
      "portfolio-name",
      "timezone",
      "reporting-weekday",
      "decision-policy",
      "resource-capacity-policy",
      "status-freshness-days",
    ],
  },
  supportNodes: [
    { key: "playbook", type: "doc", slug: "kelly-pmo-playbook", name: "PMO Operating Playbook" },
    { key: "files", type: "drive", slug: "kelly-pmo-files", name: "PMO Files" },
    { key: "import-schema", type: "file", slug: "pmo-import-schema", name: "PMO Import Schema" },
    { key: "status-form", type: "form", slug: "kelly-pmo-status-form", name: "Weekly Status Form" },
    { key: "dependency-map", type: "whiteboard", slug: "kelly-pmo-dependency-map", name: "Dependency Map" },
    { key: "weekly-workflow", type: "workflow", slug: "kelly-pmo-weekly-workflow", name: "Weekly Reporting Workflow" },
    { key: "wallboard", type: "html", slug: "kelly-pmo-wallboard", name: "Portfolio Wallboard" },
    { key: "operator-skill", type: "skill", slug: "kelly-pmo-operator", name: "PMO Operator Skill" },
  ],
  bases: [
    base(
      "programs",
      "Project Groups",
      "The portfolio's project groups/programs and the projects they own.",
      [
        field("program-id", "Program ID", "text", true),
        field("name", "Project group name", "text", true),
        field("manager", "Program manager"),
        field("sponsor", "Sponsor"),
        field("health", "Health", "select", false, choices("green", "amber", "red")),
        field("objective", "Objective", "longtext"),
        field("project-ids", "Owned project IDs", "multiselect"),
        field("cover", "Cover", "attachment", false, { attachment: { maxFiles: 1 } }),
        field("updated-at", "Updated at", "updated_time"),
      ],
      [
        table("All project groups", ["name", "manager", "sponsor", "health", "project-ids"]),
        gallery("Project group gallery", ["name", "manager", "health", "objective"], "cover"),
        kanban("Project groups by health", "health", ["name", "manager", "objective"]),
      ],
    ),
    base(
      "project-teams",
      "Project Teams",
      "Delivery teams, team leads, scope, and linked projects.",
      [
        field("team-id", "Team ID", "text", true),
        field("name", "Team name", "text", true),
        field("lead", "Team lead"),
        field(
          "function",
          "Function",
          "select",
          false,
          choices("product", "engineering", "operations", "growth", "finance"),
        ),
        field("project-ids", "Project IDs", "multiselect"),
        field("capacity", "Capacity", "number"),
        field("location", "Location"),
        field("avatar", "Team image", "attachment", false, { attachment: { maxFiles: 1 } }),
      ],
      [
        table("All project teams", ["name", "lead", "function", "capacity", "project-ids"]),
        gallery("Team gallery", ["name", "lead", "function", "capacity"], "avatar"),
        kanban("Teams by function", "function", ["name", "lead", "capacity"]),
      ],
    ),
    base(
      "projects",
      "Project Plans",
      "One row per project plan with program, ownership, dates, progress, health, budget, and reporting cadence.",
      [
        field("project-id", "Project ID", "text", true),
        field("name", "Project name", "text", true),
        field("program", "Project group"),
        field("team", "Project team"),
        field("type", "Type"),
        field("status", "Status", "select", false, choices("proposed", "planning", "active", "paused", "complete")),
        field("health", "Health", "select", false, choices("green", "amber", "red")),
        field("owner", "Project manager"),
        field("sponsor", "Sponsor"),
        field("budget", "Budget"),
        field("progress", "Progress", "number"),
        field("start-date", "Start date", "date"),
        field("target-date", "Target date", "date"),
        field("last-report-at", "Last report at", "date"),
        field("next-report-due", "Next report due", "date"),
        field("next-action", "Next action", "longtext"),
        field("cover", "Cover", "attachment", false, { attachment: { maxFiles: 1 } }),
        field("created-at", "Created at"),
        field("updated-at", "Updated at"),
      ],
      [
        table("All project plans", ["name", "program", "team", "owner", "status", "health", "progress", "target-date"]),
        gallery("Project portfolio gallery", ["name", "program", "owner", "health", "progress"], "cover"),
        kanban("Delivery board", "status", ["name", "owner", "health", "progress", "target-date"]),
        calendar("Project target calendar", "target-date", ["name", "owner", "health"]),
        gantt("Portfolio gantt", "start-date", "target-date", ["name", "owner", "status", "progress"]),
      ],
    ),
    base(
      "reports",
      "Status Reports",
      "One idempotent status report per project and ISO-week period key.",
      [
        field("report-id", "Report ID", "text", true),
        field("project-id", "Project ID", "text", true),
        field("period-key", "Period key", "text", true),
        field("summary", "Summary", "longtext"),
        field("progress", "Progress", "number"),
        field("health", "Health", "select", false, choices("green", "amber", "red")),
        field("accomplishments", "Accomplishments", "longtext"),
        field("next-period", "Next period", "longtext"),
        field("blockers", "Blockers", "longtext"),
        field("decisions-needed", "Decisions needed", "longtext"),
        field("submitted-at", "Submitted at", "date"),
        field("updated-at", "Updated at"),
      ],
      [
        table("All status reports", ["project-id", "period-key", "health", "progress", "submitted-at"]),
        gallery("Weekly report digest", ["project-id", "period-key", "health", "summary", "decisions-needed"]),
        kanban("Reports by health", "health", ["project-id", "period-key", "summary"]),
        calendar("Report calendar", "submitted-at", ["project-id", "period-key", "health"]),
      ],
    ),
    base(
      "special-tasks",
      "Special Tasks",
      "Cross-project or executive special assignments outside the ordinary milestone plan.",
      [
        field("task-id", "Task ID", "text", true),
        field("title", "Task", "text", true),
        field("project-id", "Project ID"),
        field("owner", "Owner"),
        field("priority", "Priority", "select", false, choices("low", "medium", "high", "critical")),
        field("status", "Status", "select", false, choices("ready", "in_progress", "blocked", "done")),
        field("due-date", "Due date", "date"),
        field("brief", "Brief", "longtext"),
      ],
      [
        table("All special tasks", ["title", "project-id", "owner", "priority", "status", "due-date"]),
        kanban("Special task board", "status", ["title", "owner", "priority", "due-date"]),
        calendar("Special task calendar", "due-date", ["title", "owner", "priority"]),
      ],
    ),
    base(
      "communications",
      "Communication Plans",
      "Stakeholder communication events, channels, owners, audiences, and approval state.",
      [
        field("communication-id", "Communication ID", "text", true),
        field("project-id", "Project ID"),
        field("title", "Communication", "text", true),
        field("audience", "Audience"),
        field("channel", "Channel", "select", false, choices("meeting", "email", "chat", "document", "townhall")),
        field("owner", "Owner"),
        field("scheduled-at", "Scheduled at", "date"),
        field("status", "Status", "select", false, choices("draft", "ready", "sent", "cancelled")),
        field("message", "Message", "longtext"),
      ],
      [
        table("Communication register", [
          "title",
          "project-id",
          "audience",
          "channel",
          "owner",
          "scheduled-at",
          "status",
        ]),
        kanban("Communications by state", "status", ["title", "audience", "channel", "scheduled-at"]),
        calendar("Communication calendar", "scheduled-at", ["title", "audience", "channel", "owner"]),
      ],
    ),
    base(
      "resources",
      "Human Resources",
      "People, roles, capacity, allocation, skills, and availability for portfolio planning.",
      [
        field("resource-id", "Resource ID", "text", true),
        field("name", "Name", "text", true),
        field("role", "Role"),
        field(
          "function",
          "Function",
          "select",
          false,
          choices("product", "engineering", "operations", "growth", "finance"),
        ),
        field("project-ids", "Project IDs", "multiselect"),
        field("allocation-percent", "Allocation percent", "number"),
        field("availability", "Availability", "select", false, choices("available", "partial", "full", "leave")),
        field("skills", "Skills", "multiselect"),
        field("photo", "Photo", "attachment", false, { attachment: { maxFiles: 1 } }),
      ],
      [
        table("Resource ledger", ["name", "role", "function", "allocation-percent", "availability", "project-ids"]),
        gallery("People gallery", ["name", "role", "function", "availability", "skills"], "photo"),
        kanban("Capacity board", "availability", ["name", "role", "allocation-percent", "project-ids"]),
      ],
    ),
    base(
      "functional-groups",
      "Functional Groups",
      "Functional ownership, group leads, responsibilities, and capacity envelopes.",
      [
        field("group-id", "Group ID", "text", true),
        field("name", "Functional group", "text", true),
        field("lead", "Lead"),
        field("responsibility", "Responsibility", "longtext"),
        field("headcount", "Headcount", "number"),
        field("health", "Health", "select", false, choices("green", "amber", "red")),
        field("icon", "Group image", "attachment", false, { attachment: { maxFiles: 1 } }),
      ],
      [
        table("Functional group register", ["name", "lead", "responsibility", "headcount", "health"]),
        gallery("Functional group gallery", ["name", "lead", "headcount", "health"], "icon"),
        kanban("Groups by health", "health", ["name", "lead", "headcount"]),
      ],
    ),
    base(
      "glossary",
      "Glossary",
      "Shared PMO terms, acronyms, definitions, owners, and effective dates.",
      [
        field("term-id", "Term ID", "text", true),
        field("term", "Term", "text", true),
        field("acronym", "Acronym"),
        field("definition", "Definition", "markdown"),
        field(
          "domain",
          "Domain",
          "select",
          false,
          choices("portfolio", "delivery", "product", "technology", "finance"),
        ),
        field("owner", "Owner"),
        field("effective-date", "Effective date", "date"),
      ],
      [
        table("Glossary A-Z", ["term", "acronym", "domain", "owner", "effective-date"]),
        gallery("Term cards", ["term", "acronym", "definition", "domain", "owner"]),
        calendar("Terminology changes", "effective-date", ["term", "domain", "owner"]),
      ],
    ),
    base(
      "testing",
      "Testing",
      "Test cycles, owners, environments, coverage, defects, and release readiness.",
      [
        field("test-id", "Test ID", "text", true),
        field("project-id", "Project ID"),
        field("cycle", "Cycle", "text", true),
        field(
          "test-type",
          "Test type",
          "select",
          false,
          choices("unit", "integration", "uat", "performance", "security"),
        ),
        field("owner", "Owner"),
        field("environment", "Environment"),
        field("status", "Status", "select", false, choices("planned", "running", "blocked", "passed", "failed")),
        field("planned-date", "Planned date", "date"),
        field("coverage", "Coverage", "number"),
        field("open-defects", "Open defects", "number"),
        field("evidence", "Evidence", "attachment", false, { attachment: { maxFiles: 20 } }),
      ],
      [
        table("Test register", ["cycle", "project-id", "test-type", "owner", "status", "coverage", "open-defects"]),
        kanban("Test execution board", "status", ["cycle", "project-id", "test-type", "owner", "planned-date"]),
        calendar("Test calendar", "planned-date", ["cycle", "project-id", "test-type", "status"]),
        gallery("Test evidence", ["cycle", "project-id", "status", "coverage", "open-defects"], "evidence"),
      ],
    ),
    base(
      "requirements",
      "Requirements",
      "Requirements, acceptance criteria, owners, priority, source, and delivery state.",
      [
        field("requirement-id", "Requirement ID", "text", true),
        field("project-id", "Project ID"),
        field("iteration-id", "Iteration ID"),
        field("title", "Requirement", "text", true),
        field("type", "Type", "select", false, choices("business", "functional", "nonfunctional", "compliance")),
        field("priority", "Priority", "select", false, choices("must", "should", "could", "wont")),
        field("status", "Status", "select", false, choices("draft", "ready", "in_progress", "accepted", "blocked")),
        field("owner", "Owner"),
        field("acceptance-criteria", "Acceptance criteria", "markdown"),
        field("source-url", "Source URL", "url"),
      ],
      [
        table("Requirement register", ["title", "project-id", "iteration-id", "type", "priority", "status", "owner"]),
        kanban("Requirement board", "status", ["title", "project-id", "priority", "owner"]),
        gallery("Requirement cards", ["title", "project-id", "type", "priority", "status", "acceptance-criteria"]),
      ],
    ),
    base(
      "iterations",
      "Iterations",
      "Delivery iterations/sprints with goals, dates, team, capacity, and status.",
      [
        field("iteration-id", "Iteration ID", "text", true),
        field("project-id", "Project ID"),
        field("name", "Iteration", "text", true),
        field("goal", "Goal", "longtext"),
        field("team", "Team"),
        field("status", "Status", "select", false, choices("planned", "active", "review", "complete")),
        field("start-date", "Start date", "date"),
        field("end-date", "End date", "date"),
        field("capacity", "Capacity", "number"),
        field("velocity", "Velocity", "number"),
      ],
      [
        table("Iteration register", [
          "name",
          "project-id",
          "team",
          "status",
          "start-date",
          "end-date",
          "capacity",
          "velocity",
        ]),
        kanban("Iteration board", "status", ["name", "project-id", "team", "goal"]),
        calendar("Iteration calendar", "start-date", ["name", "project-id", "team", "status"]),
        gantt("Iteration timeline", "start-date", "end-date", ["name", "project-id", "team", "status"]),
      ],
    ),
    base(
      "milestones",
      "Milestones",
      "Project milestones and gates with owner, dates, progress, evidence, and delivery state.",
      [
        field("milestone-id", "Milestone ID", "text", true),
        field("project-id", "Project ID", "text", true),
        field("title", "Milestone", "text", true),
        field("owner", "Owner"),
        field("start-date", "Start date", "date"),
        field("due-date", "Due date", "date"),
        field("status", "Status", "select", false, choices("not_started", "in_progress", "at_risk", "blocked", "done")),
        field("progress", "Progress", "number"),
        field("evidence", "Evidence", "longtext"),
        field("created-at", "Created at"),
        field("updated-at", "Updated at"),
      ],
      [
        table("Milestone register", ["title", "project-id", "owner", "due-date", "status", "progress"]),
        kanban("Milestone board", "status", ["title", "project-id", "owner", "due-date", "progress"]),
        calendar("Milestone calendar", "due-date", ["title", "project-id", "owner", "status"]),
        gantt("Milestone gantt", "start-date", "due-date", ["title", "project-id", "owner", "status", "progress"]),
      ],
    ),
    base(
      "risks",
      "Risks",
      "Portfolio RAID register with probability, impact, owner, mitigation, and review date.",
      [
        field("risk-id", "Risk ID", "text", true),
        field("project-id", "Project ID", "text", true),
        field("title", "Risk or issue", "text", true),
        field(
          "category",
          "Category",
          "select",
          false,
          choices("scope", "schedule", "quality", "budget", "resource", "dependency"),
        ),
        field("probability", "Probability", "select", false, choices("low", "medium", "high")),
        field("impact", "Impact", "select", false, choices("low", "medium", "high")),
        field("status", "Status", "select", false, choices("open", "mitigating", "accepted", "closed")),
        field("owner", "Owner"),
        field("mitigation", "Mitigation", "longtext"),
        field("review-date", "Review date", "date"),
        field("created-at", "Created at"),
        field("updated-at", "Updated at"),
      ],
      [
        table("RAID register", [
          "title",
          "project-id",
          "category",
          "probability",
          "impact",
          "status",
          "owner",
          "review-date",
        ]),
        kanban("Risk response board", "status", ["title", "project-id", "probability", "impact", "owner"]),
        calendar("Risk review calendar", "review-date", ["title", "project-id", "impact", "owner"]),
      ],
    ),
    base(
      "decisions",
      "Decisions",
      "Review queue for cross-project decisions with a stable visible reference and versioned human verdict.",
      [
        field("decision-id", "Decision ID", "text", true),
        field("ref", "Reference", "number"),
        field("project-id", "Project ID"),
        field("title", "Decision", "text", true),
        field("summary", "Summary", "longtext"),
        field("recommendation", "Recommendation", "longtext"),
        field(
          "status",
          "Status",
          "select",
          false,
          choices("needs_review", "changes_requested", "approved", "blocked", "done"),
        ),
        field("decision-note", "Decision note", "longtext"),
        field("decided-at", "Decided at", "date"),
        field("created-at", "Created at"),
        field("updated-at", "Updated at"),
      ],
      [
        table("Decision register", ["ref", "title", "project-id", "status", "decided-at"]),
        kanban("Decision board", "status", ["ref", "title", "project-id", "recommendation"]),
        calendar("Decision calendar", "decided-at", ["ref", "title", "project-id", "status"]),
      ],
    ),
    base(
      "settings",
      "Settings",
      "Versioned portfolio onboarding, reporting cadence, capacity policy, health thresholds, and decision policy.",
      [
        field("record-id", "Record ID", "text", true),
        field("portfolio-name", "Portfolio name"),
        field("timezone", "Timezone"),
        field("reporting-weekday", "Reporting weekday"),
        field("amber-threshold-days", "Amber threshold days", "number"),
        field("red-threshold-days", "Red threshold days", "number"),
        field("status-freshness-days", "Status freshness days", "number"),
        field("resource-capacity-policy", "Resource capacity policy", "longtext"),
        field("decision-policy", "Decision policy", "longtext"),
        field("onboarding-version", "Onboarding version", "number"),
        field(
          "onboarding-status",
          "Onboarding status",
          "select",
          false,
          choices("not_started", "in_progress", "needs_review", "complete"),
        ),
        field("completed-at", "Completed at", "date"),
        field("updated-at", "Updated at"),
      ],
      [
        table("PMO settings", [
          "portfolio-name",
          "timezone",
          "reporting-weekday",
          "status-freshness-days",
          "onboarding-status",
        ]),
      ],
    ),
  ],
  permissions: {
    readProcedures: ["nodes.list", "nodes.get", "bases.get", "bases.listViews", "records.list", "records.count"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata", "views.changeRequest"],
    writeProcedures: ["records.changeRequest", "bases.createChangeRequest"],
  },
};
