export const appConfig = {
  appId: "kelly-sales-outreach",
  appName: "Kelly Sales Outreach",
  deployment: "cloud",
  locale: "zh-CN",
  readOnly: false,
  spaceId: "",
  schemaVersion: 1,
  onboardingVersion: 1,
  folder: {
    name: "Kelly 销售拓客",
    description: "Product positioning, ideal-customer profile, target accounts, contacts, and reviewed outreach",
    nodeId: "",
    slug: "kelly-sales-outreach",
  },
  airApp: { name: "Kelly Sales Outreach", slug: "kelly-sales-outreach-app", resourceKey: "airapp" },
  bases: [
    {
      key: "profile",
      name: "产品与 ICP",
      slug: "sales-outreach-profile-v1",
      description: "One offer profile and the ideal-customer hypothesis that drives research and messaging",
      nodeId: "",
      baseId: "",
      fields: [
        { slug: "seller-name", name: "发起人", type: "text", required: false },
        { slug: "offer-name", name: "产品或服务", type: "text", required: true },
        { slug: "offer-summary", name: "产品服务说明", type: "longtext", required: true },
        { slug: "value-proposition", name: "价值主张", type: "longtext", required: false },
        { slug: "proof-points", name: "案例与证据", type: "longtext", required: false },
        { slug: "target-industries", name: "目标行业", type: "text", required: false },
        { slug: "target-regions", name: "目标地区", type: "text", required: false },
        { slug: "buyer-roles", name: "决策角色", type: "text", required: false },
        { slug: "ideal-customer", name: "理想客户画像", type: "longtext", required: false },
        { slug: "research-channels", name: "研究渠道", type: "text", required: false },
        { slug: "collateral-file", name: "销售资料附件", type: "text", required: false },
        { slug: "from-email", name: "发件邮箱", type: "text", required: false },
        { slug: "smtp-vault-key", name: "SMTP 凭据引用", type: "text", required: false },
        { slug: "updated-at", name: "更新时间", type: "date", required: false },
        { slug: "onboarding-version", name: "引导完成版本", type: "number", required: false },
      ],
    },
    {
      key: "companies",
      name: "目标客户",
      slug: "sales-outreach-companies-v1",
      description:
        "One row per target account with fit evidence, pain signals, a reviewed first-touch draft, and outreach state",
      nodeId: "",
      baseId: "",
      fields: [
        { slug: "name", name: "公司名称", type: "text", required: true },
        { slug: "key", name: "公司标识", type: "text", required: true },
        { slug: "website", name: "官网", type: "text", required: false },
        { slug: "source-url", name: "来源链接", type: "text", required: false },
        { slug: "industry", name: "行业", type: "text", required: false },
        { slug: "region", name: "地区", type: "text", required: false },
        { slug: "company-size", name: "规模", type: "text", required: false },
        { slug: "match-score", name: "ICP 匹配度", type: "number", required: false },
        { slug: "match-reason", name: "匹配理由", type: "longtext", required: false },
        { slug: "pain-signals", name: "业务信号", type: "longtext", required: false },
        { slug: "email-subject", name: "邮件主题", type: "text", required: false },
        { slug: "email-body", name: "邮件正文", type: "longtext", required: false },
        { slug: "status", name: "状态", type: "text", required: false },
        { slug: "sent-to", name: "实发邮箱", type: "text", required: false },
        { slug: "approved-at", name: "批准时间", type: "date", required: false },
        { slug: "sent-at", name: "发送时间", type: "date", required: false },
        { slug: "opted-out-at", name: "退出联系时间", type: "date", required: false },
        { slug: "evidence-type", name: "证据类型", type: "text", required: false },
        { slug: "evidence-date", name: "抓取日期", type: "date", required: false },
      ],
    },
    {
      key: "leads",
      name: "业务联系人",
      slug: "sales-outreach-leads-v1",
      description: "Public business contact candidates for each target account, each with provenance and confidence",
      nodeId: "",
      baseId: "",
      fields: [
        { slug: "email", name: "邮箱", type: "text", required: true },
        { slug: "company-key", name: "所属公司", type: "text", required: true },
        { slug: "contact-name", name: "联系人", type: "text", required: false },
        { slug: "role", name: "业务角色", type: "text", required: false },
        { slug: "source-url", name: "来源链接", type: "text", required: true },
        { slug: "confidence", name: "置信度", type: "text", required: false },
      ],
    },
  ],
  permissions: {
    readProcedures: ["nodes.list", "nodes.get", "bases.get", "records.list"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata"],
    writeProcedures: ["bases.createChangeRequest", "records.changeRequest"],
  },
};
