export const appConfig = {
  appId: "kelly-disclosure-tracker",
  appName: "Cross-Entity Disclosure Tracker",
  deployment: "cloud",
  locale: "auto",
  readOnly: false,
  spaceId: "",
  schemaVersion: 1,
  folder: {
    name: "Kelly Disclosure Tracker",
    description:
      "Cross-Entity Disclosure Tracker: a review workspace that assembles and tracks a standardized disclosure package per financing vehicle (fund/SPV), across an onshore origination entity, an offshore fund-manager entity, and a listing/exchange venue",
    nodeId: "",
    slug: "kelly-disclosure-tracker",
  },
  airApp: { name: "Cross-Entity Disclosure Tracker", slug: "kelly-disclosure-tracker-app", resourceKey: "airapp" },
  bases: [
    {
      key: "vehicles",
      name: "Vehicles",
      slug: "kelly-disclosure-tracker-vehicles-v1",
      description:
        "One row per financing vehicle (fund/SPV) — the origination entity, fund-manager entity, listing venue, base currency, and target close date. Per-vehicle checklist completeness/readiness is never stored; it is recomputed client-side from the items Base on every read",
      nodeId: "",
      baseId: "",
      readLimit: 60,
      fields: [
        { slug: "vehicle-id", name: "Vehicle ID", type: "text", required: true },
        { slug: "name", name: "Name", type: "text", required: false },
        { slug: "vehicle-type", name: "Vehicle type", type: "text", required: false },
        { slug: "origination-entity", name: "Origination entity", type: "text", required: false },
        { slug: "fund-manager-entity", name: "Fund-manager entity", type: "text", required: false },
        { slug: "listing-venue", name: "Listing venue", type: "text", required: false },
        { slug: "base-currency", name: "Base currency", type: "text", required: false },
        { slug: "target-close-date", name: "Target close date", type: "text", required: false },
      ],
    },
    {
      key: "items",
      name: "Disclosure Items",
      slug: "kelly-disclosure-tracker-items-v1",
      description:
        "One row per standardized disclosure checklist item, scoped to a vehicle and one of the three entity roles (origination / fund_manager / listing_venue). Carries the raw checklist fields, an optional cross-entity reconciliation record, the reviewer's decision, and — once scripts/execute_decisions.mjs runs — an execution marker. Status is never stored; it is recomputed client-side from decision + reconciliation on every read",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "item-id", name: "Item ID", type: "text", required: true },
        { slug: "vehicle-id", name: "Vehicle ID", type: "text", required: true },
        { slug: "role", name: "Entity role", type: "text", required: false },
        { slug: "item-key", name: "Item key", type: "text", required: false },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "summary", name: "Summary", type: "text", required: false },
        { slug: "body", name: "Body", type: "longtext", required: false },
        { slug: "category", name: "Category", type: "text", required: false },
        { slug: "proposed-action", name: "Proposed action", type: "text", required: false },
        { slug: "reason", name: "Reason", type: "text", required: false },
        { slug: "reconciliation", name: "Reconciliation (JSON)", type: "longtext", required: false },
        { slug: "decision-action", name: "Decision action", type: "text", required: false },
        { slug: "decision-comment", name: "Decision comment", type: "longtext", required: false },
        { slug: "decided-at", name: "Decided at", type: "text", required: false },
        { slug: "override-reconciliation", name: "Override reconciliation", type: "text", required: false },
        { slug: "execution-status", name: "Execution status", type: "text", required: false },
        { slug: "execution-detail", name: "Execution detail", type: "text", required: false },
        { slug: "executed-at", name: "Executed at", type: "text", required: false },
      ],
    },
    {
      key: "settings",
      name: "Settings",
      slug: "kelly-disclosure-tracker-settings-v1",
      description: "Sanitized config summary (reviewer name) and the current batch's run metadata, one row per kind",
      nodeId: "",
      baseId: "",
      readLimit: 20,
      fields: [
        { slug: "record-id", name: "Record ID", type: "text", required: true },
        { slug: "kind", name: "Kind", type: "text", required: true },
        { slug: "payload", name: "Payload", type: "longtext", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
  ],
  permissions: {
    readProcedures: ["nodes.list", "nodes.get", "bases.get", "records.list"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata"],
    writeProcedures: ["records.changeRequest", "bases.createChangeRequest"],
  },
};
