export const appConfig = {
  appId: "kelly-homework-coach",
  appName: "Kelly Homework Coach",
  deployment: "cloud",
  locale: "auto",
  readOnly: false,
  spaceId: "",
  schemaVersion: 1,
  folder: {
    name: "Kelly Homework Coach",
    description:
      "Kelly Homework Coach: a child-friendly homework desk — questions the agent explained (with the gentle step-by-step explanation), the mistake notebook, practice papers, the parent/teacher review queue, and sanitized settings",
    nodeId: "",
    slug: "kelly-homework-coach",
  },
  airApp: { name: "Kelly Homework Coach", slug: "kelly-homework-coach-app", resourceKey: "airapp" },
  bases: [
    {
      key: "questions",
      name: "Questions",
      slug: "kelly-homework-coach-questions-v1",
      description:
        "One row per homework question the agent has explained (from a photo, pasted text, or a paper) — prompt/answers, outcome, and the child-facing explanation (kid summary, steps, key concept, self check, next hint). Written by scripts/record_homework.mjs when the agent finishes explaining a question in chat; status is stored directly, set by the parent/teacher's review decision on the linked review row",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "question-id", name: "Question ID", type: "text", required: true },
        { slug: "ref", name: "Ref", type: "number", required: false },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "subject", name: "Subject", type: "text", required: false },
        { slug: "grade", name: "Grade", type: "text", required: false },
        { slug: "topic", name: "Topic", type: "text", required: false },
        { slug: "source", name: "Source", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "difficulty", name: "Difficulty", type: "text", required: false },
        { slug: "photo-label", name: "Photo label", type: "text", required: false },
        { slug: "prompt-text", name: "Prompt text", type: "longtext", required: false },
        { slug: "student-answer", name: "Student answer", type: "text", required: false },
        { slug: "correct-answer", name: "Correct answer", type: "text", required: false },
        { slug: "outcome", name: "Outcome", type: "text", required: false },
        { slug: "confidence", name: "Confidence", type: "number", required: false },
        { slug: "created-at", name: "Created at", type: "text", required: false },
        { slug: "tags", name: "Tags (JSON array)", type: "longtext", required: false },
        { slug: "explanation", name: "Explanation (JSON object)", type: "longtext", required: false },
        { slug: "mistake-id", name: "Mistake ID", type: "text", required: false },
      ],
    },
    {
      key: "mistakes",
      name: "Mistakes",
      slug: "kelly-homework-coach-mistakes-v1",
      description:
        "One row per mistake-book entry (grouped by stable id so repeated review updates the same card instead of duplicating it) — root cause, misconception, fix strategy, similar practice prompt, and parent note. Written by scripts/record_homework.mjs alongside the question it came from",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "mistake-id", name: "Mistake ID", type: "text", required: true },
        { slug: "question-id", name: "Question ID", type: "text", required: false },
        { slug: "ref", name: "Ref", type: "number", required: false },
        { slug: "subject", name: "Subject", type: "text", required: false },
        { slug: "topic", name: "Topic", type: "text", required: false },
        { slug: "mistake-type", name: "Mistake type", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "last-seen", name: "Last seen", type: "text", required: false },
        { slug: "next-review-at", name: "Next review at", type: "text", required: false },
        { slug: "attempts", name: "Attempts", type: "number", required: false },
        { slug: "review-history", name: "Review history (JSON array)", type: "longtext", required: false },
        { slug: "analysis", name: "Analysis (JSON object)", type: "longtext", required: false },
      ],
    },
    {
      key: "papers",
      name: "Papers",
      slug: "kelly-homework-coach-papers-v1",
      description:
        "One row per practice paper plan or completed-paper analysis — focus topics, linked mistakes, difficulty mix, items, and (once analyzed) wrong-question count/strengths/review plan. Written by scripts/record_homework.mjs; export to a real file happens outside this app after parent/teacher approval",
      nodeId: "",
      baseId: "",
      readLimit: 50,
      fields: [
        { slug: "paper-id", name: "Paper ID", type: "text", required: true },
        { slug: "ref", name: "Ref", type: "number", required: false },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "subject", name: "Subject", type: "text", required: false },
        { slug: "grade", name: "Grade", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "generated-at", name: "Generated at", type: "text", required: false },
        { slug: "focus-topics", name: "Focus topics (JSON array)", type: "longtext", required: false },
        { slug: "linked-mistakes", name: "Linked mistakes (JSON array)", type: "longtext", required: false },
        { slug: "question-count", name: "Question count", type: "number", required: false },
        { slug: "estimated-minutes", name: "Estimated minutes", type: "number", required: false },
        { slug: "difficulty-mix", name: "Difficulty mix (JSON object)", type: "longtext", required: false },
        { slug: "items", name: "Items (JSON array)", type: "longtext", required: false },
        { slug: "analysis", name: "Analysis (JSON object)", type: "longtext", required: false },
      ],
    },
    {
      key: "reviews",
      name: "Reviews",
      slug: "kelly-homework-coach-reviews-v1",
      description:
        "One row per parent/teacher review item (targets a question, mistake, or paper) — the raw review fields plus the reviewer's decision (decision-action/decision-comment/decided-at) and, once scripts/execute_decisions.mjs runs, an execution marker, all written directly onto the same row. Status is stored directly, set by the reviewer's decision action",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "review-id", name: "Review ID", type: "text", required: true },
        { slug: "ref", name: "Ref", type: "number", required: false },
        { slug: "target-type", name: "Target type", type: "text", required: false },
        { slug: "target-id", name: "Target ID", type: "text", required: false },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "summary", name: "Summary", type: "longtext", required: false },
        { slug: "risk", name: "Risk (JSON array)", type: "longtext", required: false },
        { slug: "proposed-action", name: "Proposed action", type: "text", required: false },
        { slug: "reason", name: "Reason", type: "longtext", required: false },
        { slug: "suggestions", name: "Suggestions (JSON array)", type: "longtext", required: false },
        { slug: "suggested-note", name: "Suggested note", type: "longtext", required: false },
        { slug: "decision-action", name: "Decision action", type: "text", required: false },
        { slug: "decision-comment", name: "Decision comment", type: "longtext", required: false },
        { slug: "decided-at", name: "Decided at", type: "text", required: false },
        { slug: "execution-status", name: "Execution status", type: "text", required: false },
        { slug: "execution-detail", name: "Execution detail", type: "text", required: false },
        { slug: "executed-at", name: "Executed at", type: "text", required: false },
      ],
    },
    {
      key: "settings",
      name: "Settings",
      slug: "kelly-homework-coach-settings-v1",
      description:
        "Sanitized config summary (student profile, subjects, learning policy, practice defaults, export policy, no secrets) plus the two authored aggregate metrics that cannot be recomputed from the current record lists (mastery_score, questions_analyzed — an all-time history, not just currently open items). One row keyed by record-id/kind",
      nodeId: "",
      baseId: "",
      readLimit: 20,
      fields: [
        { slug: "record-id", name: "Record ID", type: "text", required: true },
        { slug: "kind", name: "Kind", type: "text", required: true },
        { slug: "payload", name: "Payload (JSON object)", type: "longtext", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
  ],
  permissions: {
    readProcedures: ["nodes.list", "nodes.get", "bases.get", "records.list"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata"],
    writeProcedures: ["records.changeRequest", "bases.createChangeRequest"],
  },
};
