export const appConfig = {
  appId: "kelly-legal-matter-strategy",
  appName: "Legal Matter Strategy",
  deployment: "cloud",
  locale: "auto",
  readOnly: false,
  spaceId: "",
  schemaVersion: 1,
  folder: {
    name: "Legal Matter Strategy",
    description:
      "Matter-strategy desk over new-case strategy, issue trees, evidence checklists, risk analysis, pleading outlines, and approval-gated drafting packs grounded in internal precedents (approve / request changes / revise / block) before a strategy pack becomes a drafting handoff",
    nodeId: "",
    slug: "kelly-legal-matter-strategy",
  },
  airApp: { name: "Legal Matter Strategy", slug: "kelly-legal-matter-strategy-app", resourceKey: "airapp" },
  bases: [
    {
      key: "items",
      name: "Strategy Packs",
      slug: "kelly-legal-matter-strategy-items-v1",
      description:
        "Agent-prepared matter-strategy packs — issue tree, evidence map, risk posture, negotiation options, and pleading outline, workflow status, and the review-queue decision on the same row",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "item-id", name: "Item ID", type: "text", required: true },
        { slug: "ref", name: "Ref", type: "text", required: false },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "category", name: "Category", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "owner", name: "Owner", type: "text", required: false },
        { slug: "risk", name: "Risk (JSON array)", type: "longtext", required: false },
        { slug: "summary", name: "Summary", type: "longtext", required: false },
        { slug: "body", name: "Body", type: "longtext", required: false },
        { slug: "recommendation", name: "Recommendation", type: "longtext", required: false },
        { slug: "proposed-action", name: "Proposed action", type: "text", required: false },
        { slug: "draft", name: "Editable draft", type: "longtext", required: false },
        { slug: "evidence", name: "Evidence (JSON array)", type: "longtext", required: false },
        { slug: "matter-stage", name: "Matter stage", type: "text", required: false },
        { slug: "evidence-gap-count", name: "Evidence gap count", type: "number", required: false },
        { slug: "evidence-gaps-list", name: "Evidence gaps (JSON array)", type: "longtext", required: false },
        { slug: "issue-tree", name: "Issue tree (JSON array)", type: "longtext", required: false },
        { slug: "negotiation-options", name: "Negotiation options (JSON array)", type: "longtext", required: false },
        { slug: "posture", name: "Risk posture", type: "longtext", required: false },
        { slug: "pleading-outline", name: "Pleading outline", type: "longtext", required: false },
        { slug: "deadline", name: "Deadline", type: "text", required: false },
        { slug: "decision-action", name: "Decision action", type: "text", required: false },
        { slug: "decision-note", name: "Decision note", type: "longtext", required: false },
        { slug: "decided-at", name: "Decided at", type: "text", required: false },
        { slug: "execution-status", name: "Execution status", type: "text", required: false },
        { slug: "execution-operation", name: "Execution operation", type: "text", required: false },
        { slug: "execution-target", name: "Execution target", type: "text", required: false },
        { slug: "execution-detail", name: "Execution detail", type: "longtext", required: false },
        { slug: "executed-at", name: "Executed at", type: "text", required: false },
        { slug: "created-at", name: "Created at", type: "text", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
    {
      key: "entities",
      name: "Matter Library",
      slug: "kelly-legal-matter-strategy-entities-v1",
      description: "Matter families, issue clusters, or strategy lanes grouped by cause, stage, and responsible lawyer",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "entity-id", name: "Entity ID", type: "text", required: true },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "meta", name: "Meta", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "owner", name: "Owner", type: "text", required: false },
        { slug: "summary", name: "Summary", type: "longtext", required: false },
        { slug: "tags", name: "Tags (JSON array)", type: "longtext", required: false },
        { slug: "metrics", name: "Metrics (JSON object)", type: "longtext", required: false },
      ],
    },
    {
      key: "checks",
      name: "Checks",
      slug: "kelly-legal-matter-strategy-checks-v1",
      description:
        "Deterministic strategy QA checks for missing facts, evidence gaps, deadline caveats, precedent grounding, and unsupported legal positions",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "check-id", name: "Check ID", type: "text", required: true },
        { slug: "label", name: "Label", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "detail", name: "Detail", type: "longtext", required: false },
        { slug: "item-id", name: "Item ID", type: "text", required: false },
        { slug: "severity", name: "Severity", type: "text", required: false },
      ],
    },
    {
      key: "settings",
      name: "Settings",
      slug: "kelly-legal-matter-strategy-settings-v1",
      description: "Firm profile, strategy policy, drafting templates, and export preferences — a single settings row",
      nodeId: "",
      baseId: "",
      readLimit: 20,
      fields: [
        { slug: "record-id", name: "Record ID", type: "text", required: true },
        { slug: "firm-name", name: "Firm name", type: "text", required: false },
        { slug: "branch", name: "Branch", type: "text", required: false },
        {
          slug: "default-jurisdictions",
          name: "Default jurisdictions (JSON array)",
          type: "longtext",
          required: false,
        },
        { slug: "reviewer-role", name: "Reviewer role", type: "text", required: false },
        { slug: "require-precedent-links", name: "Require precedent links", type: "text", required: false },
        { slug: "require-evidence-map", name: "Require evidence map", type: "text", required: false },
        { slug: "default-risk-scale", name: "Default risk scale (JSON array)", type: "longtext", required: false },
        {
          slug: "approval-required-for-client-facing",
          name: "Approval required for client-facing output",
          type: "text",
          required: false,
        },
        { slug: "templates-enabled", name: "Enabled templates (JSON array)", type: "longtext", required: false },
        { slug: "export-format", name: "Export format", type: "text", required: false },
        { slug: "export-out-dir", name: "Export out dir", type: "text", required: false },
      ],
    },
  ],
  permissions: {
    readProcedures: ["nodes.list", "nodes.get", "bases.get", "records.list"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata"],
    writeProcedures: ["records.changeRequest", "bases.createChangeRequest"],
  },
};
