export const appConfig = {
  appId: "kelly-money",
  appName: "Kelly Money",
  deployment: "cloud",
  locale: "auto",
  readOnly: true,
  spaceId: "",
  schemaVersion: 1,
  folder: {
    name: "Kelly Money",
    description: "Aggregated money ledger across Mercury, Stripe, Airwallex, and Creem",
    nodeId: "",
    slug: "kelly-money",
  },
  bases: [
    {
      key: "accounts",
      name: "Accounts",
      slug: "kelly-money-accounts-v1",
      description: "Provider account inventory with balances and sync health",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "account-id", name: "Account ID", type: "text", required: true },
        { slug: "provider", name: "Provider", type: "text", required: false },
        { slug: "display-name", name: "Display name", type: "text", required: false },
        { slug: "entity", name: "Entity", type: "text", required: false },
        { slug: "currency", name: "Currency", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "balance-available", name: "Balance available", type: "number", required: false },
        { slug: "balance-pending", name: "Balance pending", type: "number", required: false },
        { slug: "balance-current", name: "Balance current", type: "number", required: false },
        { slug: "balance-as-of", name: "Balance as of", type: "text", required: false },
        { slug: "gross-inflow", name: "Gross inflow", type: "number", required: false },
        { slug: "gross-outflow", name: "Gross outflow", type: "number", required: false },
        { slug: "fees", name: "Fees", type: "number", required: false },
        { slug: "net", name: "Net", type: "number", required: false },
        { slug: "last-sync-at", name: "Last sync at", type: "text", required: false },
        { slug: "provider-account-id", name: "Provider account ID", type: "text", required: false },
        { slug: "notes", name: "Notes", type: "longtext", required: false },
      ],
    },
    {
      key: "transactions",
      name: "Transactions",
      slug: "kelly-money-transactions-v1",
      description: "Normalized ledger entries across providers",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "transaction-id", name: "Transaction ID", type: "text", required: true },
        { slug: "provider", name: "Provider", type: "text", required: false },
        { slug: "account-id", name: "Account ID", type: "text", required: false },
        { slug: "provider-account-id", name: "Provider account ID", type: "text", required: false },
        { slug: "provider-transaction-id", name: "Provider transaction ID", type: "text", required: false },
        { slug: "occurred-at", name: "Occurred at", type: "text", required: false },
        { slug: "available-at", name: "Available at", type: "text", required: false },
        { slug: "description", name: "Description", type: "text", required: false },
        { slug: "counterparty", name: "Counterparty", type: "text", required: false },
        { slug: "type", name: "Type", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "currency", name: "Currency", type: "text", required: false },
        { slug: "gross", name: "Gross", type: "number", required: false },
        { slug: "fee", name: "Fee", type: "number", required: false },
        { slug: "net", name: "Net", type: "number", required: false },
        { slug: "direction", name: "Direction", type: "text", required: false },
        { slug: "source-url", name: "Source URL", type: "text", required: false },
        { slug: "tags", name: "Tags", type: "text", required: false },
      ],
    },
    {
      key: "invoices",
      name: "Invoices",
      slug: "kelly-money-invoices-v1",
      description: "Invoice metadata from provider exports, PDFs, or manual entry",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "invoice-id", name: "Invoice ID", type: "text", required: true },
        { slug: "invoice-number", name: "Invoice number", type: "text", required: false },
        { slug: "direction", name: "Direction", type: "text", required: false },
        { slug: "vendor", name: "Vendor", type: "text", required: false },
        { slug: "customer", name: "Customer", type: "text", required: false },
        { slug: "issue-date", name: "Issue date", type: "text", required: false },
        { slug: "due-date", name: "Due date", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "currency", name: "Currency", type: "text", required: false },
        { slug: "subtotal", name: "Subtotal", type: "number", required: false },
        { slug: "tax", name: "Tax", type: "number", required: false },
        { slug: "total", name: "Total", type: "number", required: false },
        { slug: "source", name: "Source", type: "text", required: false },
        { slug: "source-url", name: "Source URL", type: "text", required: false },
        { slug: "file-path", name: "File path", type: "text", required: false },
        { slug: "notes", name: "Notes", type: "longtext", required: false },
      ],
    },
    {
      key: "invoice_matches",
      name: "Invoice Matches",
      slug: "kelly-money-invoice-matches-v1",
      description: "Invoice-to-transaction reconciliation results",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "match-id", name: "Match ID", type: "text", required: true },
        { slug: "invoice-id", name: "Invoice ID", type: "text", required: false },
        { slug: "transaction-id", name: "Transaction ID", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "amount-delta", name: "Amount delta", type: "number", required: false },
        { slug: "date-delta-days", name: "Date delta days", type: "number", required: false },
        { slug: "confidence", name: "Confidence", type: "number", required: false },
        { slug: "matching-method", name: "Matching method", type: "text", required: false },
        { slug: "matching-rule", name: "Matching rule", type: "text", required: false },
        { slug: "review-status", name: "Review status", type: "text", required: false },
        { slug: "amount-tolerance", name: "Amount tolerance", type: "number", required: false },
        { slug: "date-tolerance-days", name: "Date tolerance days", type: "number", required: false },
        { slug: "candidate-transaction-ids", name: "Candidate transaction IDs", type: "text", required: false },
        { slug: "matched-at", name: "Matched at", type: "text", required: false },
        { slug: "audit-events", name: "Audit events", type: "longtext", required: false },
        { slug: "notes", name: "Notes", type: "longtext", required: false },
      ],
    },
    {
      key: "settings",
      name: "Settings",
      slug: "kelly-money-settings-v1",
      description: "Configured accounts, onboarding marker, and the agent lock",
      nodeId: "",
      baseId: "",
      readLimit: 20,
      fields: [
        { slug: "record-id", name: "Record ID", type: "text", required: true },
        { slug: "kind", name: "Kind", type: "text", required: true },
        { slug: "name", name: "Name", type: "text", required: false },
        { slug: "payload", name: "Payload", type: "longtext", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
  ],
  permissions: {
    readProcedures: ["nodes.list", "nodes.get", "bases.get", "records.list"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata"],
    writeProcedures: [],
  },
};
