export const appConfig = {
  appId: "kelly-radar",
  appName: "Kelly Radar",
  deployment: "cloud",
  locale: "auto",
  readOnly: false,
  spaceId: "",
  schemaVersion: 1,
  folder: {
    name: "Kelly Radar",
    description:
      "Market-intelligence desk: competitor signals, research briefs/reports, trend movers/opportunities, and a triage review queue",
    nodeId: "",
    slug: "kelly-radar",
  },
  bases: [
    {
      key: "watchlist",
      name: "Watchlist",
      slug: "kelly-radar-watchlist-v1",
      description: "Monitored competitors, categories, keywords, and communities, with per-source method",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "target-id", name: "Target ID", type: "text", required: true },
        { slug: "name", name: "Name", type: "text", required: false },
        { slug: "type", name: "Type", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "notes", name: "Notes", type: "longtext", required: false },
        { slug: "last-check-at", name: "Last check at", type: "text", required: false },
        { slug: "sources", name: "Sources", type: "longtext", required: false },
      ],
    },
    {
      key: "signals",
      name: "Signals",
      slug: "kelly-radar-signals-v1",
      description: "Normalized competitor-monitoring signals: pricing/changelog/launch/review/news/hiring changes",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "signal-id", name: "Signal ID", type: "text", required: true },
        { slug: "target-id", name: "Target ID", type: "text", required: false },
        { slug: "source-id", name: "Source ID", type: "text", required: false },
        { slug: "source-kind", name: "Source kind", type: "text", required: false },
        { slug: "severity", name: "Severity", type: "text", required: false },
        { slug: "detected-at", name: "Detected at", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "headline", name: "Headline", type: "text", required: false },
        { slug: "summary", name: "Summary", type: "longtext", required: false },
        { slug: "why-it-matters", name: "Why it matters", type: "longtext", required: false },
        { slug: "content-hash", name: "Content hash", type: "text", required: false },
        { slug: "evidence", name: "Evidence", type: "longtext", required: false },
        { slug: "proposed-action", name: "Proposed action", type: "text", required: false },
        { slug: "handoff", name: "Handoff", type: "longtext", required: false },
        { slug: "diff", name: "Diff", type: "longtext", required: false },
        { slug: "decision-verdict", name: "Decision verdict", type: "text", required: false },
        { slug: "decision-comment", name: "Decision comment", type: "longtext", required: false },
        { slug: "decided-at", name: "Decided at", type: "text", required: false },
      ],
    },
    {
      key: "questions",
      name: "Research Questions",
      slug: "kelly-radar-questions-v1",
      description: "Research questions moving through brief_needs_review -> researching -> report_ready -> closed",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "question-id", name: "Question ID", type: "text", required: true },
        { slug: "question", name: "Question", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "asked-at", name: "Asked at", type: "text", required: false },
        { slug: "depth", name: "Depth", type: "text", required: false },
        { slug: "cost-note", name: "Cost note", type: "longtext", required: false },
        { slug: "brief-id", name: "Brief ID", type: "text", required: false },
        { slug: "report-id", name: "Report ID", type: "text", required: false },
        { slug: "confidence", name: "Confidence", type: "number", required: false },
        { slug: "followups", name: "Follow-ups", type: "longtext", required: false },
      ],
    },
    {
      key: "briefs",
      name: "Research Briefs",
      slug: "kelly-radar-briefs-v1",
      description: "Agent-drafted research briefs awaiting approval before deep research starts",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "brief-id", name: "Brief ID", type: "text", required: true },
        { slug: "question-id", name: "Question ID", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "drafted-at", name: "Drafted at", type: "text", required: false },
        { slug: "depth", name: "Depth", type: "text", required: false },
        { slug: "scope", name: "Scope", type: "longtext", required: false },
        { slug: "planned-sources", name: "Planned sources", type: "longtext", required: false },
        { slug: "expected-deliverable", name: "Expected deliverable", type: "longtext", required: false },
        { slug: "notes", name: "Notes", type: "longtext", required: false },
        { slug: "decision-verdict", name: "Decision verdict", type: "text", required: false },
        { slug: "decision-comment", name: "Decision comment", type: "longtext", required: false },
        { slug: "decided-at", name: "Decided at", type: "text", required: false },
      ],
    },
    {
      key: "reports",
      name: "Research Reports",
      slug: "kelly-radar-reports-v1",
      description: "Cited research reports with sections, sources, annotations, and Kelly's confidence rating",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "report-id", name: "Report ID", type: "text", required: true },
        { slug: "question-id", name: "Question ID", type: "text", required: false },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "filed-at", name: "Filed at", type: "text", required: false },
        { slug: "summary", name: "Summary", type: "longtext", required: false },
        { slug: "confidence", name: "Confidence", type: "number", required: false },
        { slug: "sections", name: "Sections", type: "longtext", required: false },
        { slug: "sources", name: "Sources", type: "longtext", required: false },
        { slug: "annotations", name: "Annotations", type: "longtext", required: false },
        { slug: "decided-at", name: "Decided at", type: "text", required: false },
      ],
    },
    {
      key: "movers",
      name: "Trend Movers",
      slug: "kelly-radar-movers-v1",
      description: "Rising keyword/topic demand signals: search queries, community topic volume, category interest",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "mover-id", name: "Mover ID", type: "text", required: true },
        { slug: "keyword", name: "Keyword", type: "text", required: false },
        { slug: "source", name: "Source", type: "text", required: false },
        { slug: "volume-proxy", name: "Volume proxy", type: "number", required: false },
        { slug: "delta-pct", name: "Delta pct", type: "number", required: false },
        { slug: "momentum", name: "Momentum", type: "longtext", required: false },
        { slug: "first-seen", name: "First seen", type: "text", required: false },
        { slug: "last-updated", name: "Last updated", type: "text", required: false },
        { slug: "opportunity-id", name: "Opportunity ID", type: "text", required: false },
      ],
    },
    {
      key: "opportunities",
      name: "Opportunities",
      slug: "kelly-radar-opportunities-v1",
      description: "Opportunity cards turned from sustained trend movers, with a proposed next-step handoff",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "opportunity-id", name: "Opportunity ID", type: "text", required: true },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "mover-ids", name: "Mover IDs", type: "longtext", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "created-at", name: "Created at", type: "text", required: false },
        { slug: "rationale", name: "Rationale", type: "longtext", required: false },
        { slug: "proposed-next-step", name: "Proposed next step", type: "longtext", required: false },
        { slug: "decision-verdict", name: "Decision verdict", type: "text", required: false },
        { slug: "decision-comment", name: "Decision comment", type: "longtext", required: false },
        { slug: "decided-at", name: "Decided at", type: "text", required: false },
      ],
    },
    {
      key: "sync_log",
      name: "Sync Log",
      slug: "kelly-radar-sync-log-v1",
      description: "Append-only history of ingest/file-report/execute-decisions runs",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "log-id", name: "Log ID", type: "text", required: true },
        { slug: "at", name: "At", type: "text", required: false },
        { slug: "actor", name: "Actor", type: "text", required: false },
        { slug: "action", name: "Action", type: "text", required: false },
        { slug: "detail", name: "Detail", type: "longtext", required: false },
      ],
    },
    {
      key: "settings",
      name: "Settings",
      slug: "kelly-radar-settings-v1",
      description: "Product profile, research defaults, trend sources, and cadence, a single settings row",
      nodeId: "",
      baseId: "",
      readLimit: 20,
      fields: [
        { slug: "record-id", name: "Record ID", type: "text", required: true },
        { slug: "products", name: "Products", type: "longtext", required: false },
        { slug: "cadence-monitor", name: "Cadence monitor", type: "text", required: false },
        { slug: "cadence-trends", name: "Cadence trends", type: "text", required: false },
        { slug: "research-default-depth", name: "Research default depth", type: "text", required: false },
        { slug: "research-source-policy", name: "Research source policy", type: "text", required: false },
        { slug: "research-require-citations", name: "Research require citations", type: "text", required: false },
        { slug: "research-max-sources", name: "Research max sources", type: "number", required: false },
        { slug: "trend-sources", name: "Trend sources", type: "longtext", required: false },
      ],
    },
  ],
  permissions: {
    readProcedures: ["nodes.list", "nodes.get", "bases.get", "records.list"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata"],
    writeProcedures: ["records.changeRequest", "bases.createChangeRequest"],
  },
};
