export const appConfig = {
  appId: "kelly-beauty-intel",
  appName: "Kelly Beauty Intel",
  deployment: "cloud",
  locale: "auto",
  readOnly: false,
  spaceId: "",
  schemaVersion: 1,
  folder: {
    name: "Kelly Beauty Intel",
    description: "Daily beauty, wellness, and medical-aesthetics intelligence cockpit",
    slug: "kelly-beauty-intel",
  },
  airApp: { name: "Kelly Beauty Intel", slug: "kelly-beauty-intel-app", resourceKey: "kelly-beauty-intel-app" },
  bases: [
    {
      key: "signals",
      name: "Signals",
      slug: "kelly-beauty-intel-signals",
      description: "Source-backed signals with buyer-intent interpretation",
      readLimit: 100,
      fields: [
        { slug: "signal-id", name: "Signal ID", type: "text", required: true },
        { slug: "ref", name: "Ref", type: "number", required: false },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "summary", name: "Summary", type: "longtext", required: false },
        { slug: "why-it-matters", name: "Why it matters", type: "longtext", required: false },
        { slug: "buyer-intent", name: "Buyer intent", type: "longtext", required: false },
        { slug: "confidence", name: "Confidence", type: "number", required: false },
        { slug: "detected-at", name: "Detected at", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "risk", name: "Risk", type: "text", required: false },
        { slug: "source-name", name: "Source name", type: "text", required: false },
        { slug: "source-url", name: "Source URL", type: "text", required: false },
        { slug: "suggested-action-id", name: "Suggested action", type: "text", required: false },
        { slug: "decision-note", name: "Decision note", type: "longtext", required: false },
        { slug: "decided-at", name: "Decided at", type: "text", required: false },
      ],
    },
    {
      key: "actions",
      name: "Actions",
      slug: "kelly-beauty-intel-actions",
      description: "Approved/blocked/reviewable operating or sales actions",
      readLimit: 100,
      fields: [
        { slug: "action-id", name: "Action ID", type: "text", required: true },
        { slug: "ref", name: "Ref", type: "number", required: false },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "summary", name: "Summary", type: "longtext", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "priority", name: "Priority", type: "text", required: false },
        { slug: "owner", name: "Owner", type: "text", required: false },
        { slug: "reason", name: "Reason", type: "longtext", required: false },
        { slug: "linked-signal-ids", name: "Linked signals", type: "text", required: false },
        { slug: "next-step", name: "Next step", type: "longtext", required: false },
        { slug: "decision-note", name: "Decision note", type: "longtext", required: false },
        { slug: "decided-at", name: "Decided at", type: "text", required: false },
      ],
    },
    {
      key: "drafts",
      name: "Drafts",
      slug: "kelly-beauty-intel-drafts",
      description: "Editable channel drafts under review before handoff",
      readLimit: 100,
      fields: [
        { slug: "draft-id", name: "Draft ID", type: "text", required: true },
        { slug: "ref", name: "Ref", type: "number", required: false },
        { slug: "channel", name: "Channel", type: "text", required: false },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "body", name: "Body", type: "longtext", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "risk", name: "Risk", type: "text", required: false },
        { slug: "linked-action-id", name: "Linked action", type: "text", required: false },
        { slug: "decision-note", name: "Decision note", type: "longtext", required: false },
        { slug: "decided-at", name: "Decided at", type: "text", required: false },
      ],
    },
    {
      key: "sources",
      name: "Sources",
      slug: "kelly-beauty-intel-sources",
      description: "Configured source categories, freshness, and coverage",
      readLimit: 50,
      fields: [
        { slug: "source-id", name: "Source ID", type: "text", required: true },
        { slug: "label", name: "Label", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "freshness", name: "Freshness", type: "text", required: false },
        { slug: "coverage", name: "Coverage", type: "longtext", required: false },
      ],
    },
    {
      key: "settings",
      name: "Settings",
      slug: "kelly-beauty-intel-settings",
      description: "Operator brand config, onboarding marker, and the agent lock",
      readLimit: 20,
      fields: [
        { slug: "record-id", name: "Record ID", type: "text", required: true },
        { slug: "kind", name: "Kind", type: "text", required: true },
        { slug: "name", name: "Name", type: "text", required: false },
        { slug: "payload", name: "Payload", type: "longtext", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
  ],
  permissions: {
    readProcedures: ["nodes.list", "nodes.get", "bases.get", "records.list"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata"],
    writeProcedures: ["records.changeRequest", "bases.createChangeRequest"],
  },
};
