const field = (slug, name, type = "text", required = false) => ({ slug, name, type, required });

const reviewFields = [
  field("subject", "Subject", "text", true),
  field("record-id", "Record ID", "text", true),
  field("kind", "Kind"),
  field("batch-id", "Batch ID"),
  field("item-id", "Item ID"),
  field("email-uid", "Email UID"),
  field("thread-id", "Thread ID"),
  field("message-id", "Message ID"),
  field("folder", "Mailbox Folder"),
  field("sender", "Sender"),
  field("sender-contact-id", "Sender Contact ID"),
  field("sender-email", "Sender Email", "email"),
  field("sender-domain", "Sender Domain"),
  field("recipients", "Recipients", "longtext"),
  field("recipient-contact-ids", "Recipient Contact IDs", "longtext"),
  field("recipient-emails", "Recipient Emails", "longtext"),
  field("cc", "CC", "longtext"),
  field("source-account", "Source Account"),
  field("email-date", "Email Date", "date"),
  field("category", "Category"),
  field("risk", "Risk", "longtext"),
  field("reason", "Reason", "longtext"),
  field("summary", "Summary", "longtext"),
  field("review-background", "Review Background", "longtext"),
  field("review-recommendation", "Recommendation", "longtext"),
  field("review-why", "Why Review", "longtext"),
  field("body-text", "Body Text", "longtext"),
  field("body-original", "Original Body", "longtext"),
  field("body-translation", "Body Translation", "longtext"),
  field("body-excerpt", "Body Excerpt", "longtext"),
  field("quote-preview", "Quote Preview", "longtext"),
  field("html-excerpt", "HTML Excerpt", "longtext"),
  field("draft-text", "Draft Text", "longtext"),
  field("suggested-reply", "Suggested Reply", "longtext"),
  field("draft-excerpt", "Draft Excerpt", "longtext"),
  field("user-comment", "User Comment", "longtext"),
  field("decision-action", "Decision Action"),
  field("decided-at", "Decided At", "date"),
  field("execution-status", "Execution Status"),
  field("mailbox-operation", "Mailbox Operation"),
  field("target-folder", "Target Folder"),
  field("executed-at", "Executed At", "date"),
  field("execution-reason", "Execution Reason", "longtext"),
  field("execution-error", "Execution Error", "longtext"),
  field("has-html", "Has HTML", "checkbox"),
  field("has-draft", "Has Draft", "checkbox"),
  field("has-translation", "Has Translation", "checkbox"),
  field("has-attachments", "Has Attachments", "checkbox"),
  field("drive-path", "Drive Path"),
  field("html-drive-path", "HTML Drive Path"),
  field("attachments-drive-path", "Attachments Drive Path"),
  field("attachment-count", "Attachment Count", "number"),
  field("attachment-names", "Attachment Names", "longtext"),
  field("attachment-refs", "Attachment References", "longtext"),
  field("classification-method", "Classification Method"),
  field("user-language", "User Language"),
  field("source-language", "Source Language"),
  field("body-original-language", "Original Language"),
  field("body-translation-language", "Translation Language"),
  field("status", "Status"),
  field("proposed-action", "Proposed Action"),
  field("updated-at", "Updated At", "date"),
  field("created-at", "Created At", "date"),
  field("report", "Execution Report", "json"),
  field("latest-record-id", "Latest Record ID"),
];

const contactFields = [
  field("email", "Email", "email", true),
  field("record-id", "Record ID", "text", true),
  field("kind", "Kind"),
  field("contact-id", "Contact ID"),
  field("display-name", "Display Name"),
  field("domain", "Domain"),
  field("roles", "Roles", "longtext"),
  field("source-accounts", "Source Accounts", "longtext"),
  field("first-seen-at", "First Seen At", "date"),
  field("last-seen-at", "Last Seen At", "date"),
  field("message-count", "Message Count", "number"),
  field("last-subject", "Last Subject", "longtext"),
  field("last-message-id", "Last Message ID"),
  field("last-batch-id", "Last Batch ID"),
  field("last-status", "Last Status"),
  field("last-proposed-action", "Last Proposed Action"),
  field("category-counts", "Category Counts", "longtext"),
  field("risk-tags", "Risk Tags", "longtext"),
  field("notes", "Notes", "longtext"),
  field("default-action", "Default Action"),
  field("updated-at", "Updated At", "date"),
  field("created-at", "Created At", "date"),
];

const settingsFields = [
  field("name", "Name", "text", true),
  field("record-id", "Record ID", "text", true),
  field("kind", "Kind"),
  field("payload", "Configuration", "json"),
  field("vault-refs", "Vault References", "longtext"),
  field("locked", "Locked", "checkbox"),
  field("message", "Message", "longtext"),
  field("owner", "Owner"),
  field("started-at", "Started At", "date"),
  field("updated-at", "Updated At", "date"),
];

export const appConfig = {
  appId: "kelly-email",
  appName: "Kelly Email",
  deployment: "cloud",
  locale: "zh-CN",
  spaceId: "",
  schemaVersion: 3,
  folder: {
    nodeId: "nodmscmgdpci1ebzks",
    slug: "kelly-email",
    name: "Kelly Email",
    description: "Mailbox triage, human review, trusted execution state, and account settings",
  },
  bases: [
    {
      key: "reviews",
      nodeId: "nodmscmgdpwrj7i3b7",
      baseId: "bsemscmgdpwhid8t9g",
      slug: "kelly-email-reviews-v3",
      name: "Email Reviews",
      description: "Mailbox review items, human decisions, and execution outcomes",
      readLimit: 100,
      fields: reviewFields,
    },
    {
      key: "contacts",
      nodeId: "nodmscmgdqohwvgmwn",
      baseId: "bsemscmgdqot5zzcp1",
      slug: "kelly-email-contacts-v3",
      name: "Email Contacts",
      description: "Contact observations derived from reviewed mail",
      readLimit: 100,
      fields: contactFields,
    },
    {
      key: "settings",
      nodeId: "nodmscmgdr8g774ywa",
      baseId: "bsemscmgdr87ctxkdr",
      slug: "kelly-email-settings-v3",
      name: "Email Settings",
      description: "Account configuration, Vault references, locks, and scan state",
      readLimit: 30,
      fields: settingsFields,
    },
  ],
  drive: {
    nodeId: "nodmscmgzya0euvgyy",
    slug: "kelly-email-files-v3",
    name: "Email Files",
    description: "Email HTML and attachment artifacts",
  },
  vaultNamespace: "kelly-email",
  permissions: {
    readProcedures: ["nodes.list", "nodes.get", "bases.get", "records.list", "records.get", "fileTrees.readFile"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata", "fileTrees.create"],
    writeProcedures: ["bases.createChangeRequest", "records.changeRequest", "fileTrees.createChangeRequest"],
  },
};
