export const appConfig = {
  appId: "kelly-jobhunt",
  appName: "Kelly JobHunt",
  deployment: "cloud",
  locale: "zh-CN",
  readOnly: false,
  spaceId: "",
  schemaVersion: 1,
  folder: {
    name: "Kelly 求职直投",
    description: "Job-search profile, target companies, and outreach state",
    nodeId: "",
    slug: "kelly-jobhunt",
  },
  bases: [
    {
      key: "profile",
      name: "求职档案",
      slug: "jobhunt-profile-v1",
      description: "One job seeker profile that drives company search and email drafting",
      nodeId: "",
      baseId: "",
      readLimit: 20,
      fields: [
        { slug: "name", name: "求职人", type: "text", required: true },
        { slug: "target-role", name: "目标岗位", type: "text", required: true },
        { slug: "locations", name: "意向城市", type: "text", required: false },
        { slug: "industries", name: "意向行业", type: "text", required: false },
        { slug: "highlights", name: "自我介绍", type: "longtext", required: false },
        { slug: "resume-file", name: "简历文件", type: "text", required: false },
        { slug: "from-email", name: "发件邮箱", type: "text", required: false },
        { slug: "updated-at", name: "更新时间", type: "date", required: false },
      ],
    },
    {
      key: "companies",
      name: "目标公司",
      slug: "jobhunt-companies-v1",
      description: "One row per target company: match evidence, drafted email, and outreach status",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "name", name: "公司名称", type: "text", required: true },
        { slug: "key", name: "公司标识", type: "text", required: true },
        { slug: "website", name: "官网", type: "text", required: false },
        { slug: "source-url", name: "来源链接", type: "text", required: false },
        { slug: "industry", name: "行业", type: "text", required: false },
        { slug: "match-score", name: "匹配度", type: "number", required: false },
        { slug: "match-reason", name: "匹配理由", type: "longtext", required: false },
        { slug: "email-subject", name: "邮件主题", type: "text", required: false },
        { slug: "email-body", name: "邮件正文", type: "longtext", required: false },
        { slug: "status", name: "状态", type: "text", required: false },
        { slug: "sent-to", name: "实发邮箱", type: "text", required: false },
        { slug: "approved-at", name: "批准时间", type: "date", required: false },
        { slug: "sent-at", name: "发送时间", type: "date", required: false },
      ],
    },
    {
      key: "leads",
      name: "联系邮箱",
      slug: "jobhunt-leads-v1",
      description: "Candidate contact addresses discovered for a company, several per company",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "email", name: "邮箱", type: "text", required: true },
        { slug: "company-key", name: "所属公司", type: "text", required: true },
        { slug: "role", name: "角色", type: "text", required: false },
        { slug: "source-url", name: "来源链接", type: "text", required: false },
        { slug: "confidence", name: "置信度", type: "text", required: false },
      ],
    },
  ],
  permissions: {
    readProcedures: ["nodes.list", "folders.get", "bases.get", "records.list"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata"],
    writeProcedures: ["bases.createChangeRequest", "records.changeRequest"],
  },
};
