export const appConfig = {
  appId: "kelly-instructor-sourcing",
  appName: "Kelly Instructor Sourcing",
  deployment: "cloud",
  locale: "zh-CN",
  readOnly: false,
  spaceId: "",
  schemaVersion: 1,
  onboardingVersion: 1,
  folder: {
    name: "Kelly 讲师寻访",
    description: "Search-criteria hypothesis, scoring rubric, and candidate screening for course instructor sourcing",
    nodeId: "",
    slug: "kelly-instructor-sourcing",
  },
  airApp: { name: "Kelly Instructor Sourcing", slug: "kelly-instructor-sourcing-app", resourceKey: "airapp" },
  bases: [
    {
      key: "criteria",
      name: "筛选标准",
      slug: "instructor-sourcing-criteria-v1",
      description: "One search-criteria hypothesis and the three-axis scoring rubric that drives candidate screening",
      nodeId: "",
      baseId: "",
      fields: [
        { slug: "role-keywords", name: "搜索关键词", type: "text", required: true },
        { slug: "experience-filter", name: "经验筛选假设", type: "text", required: false },
        { slug: "activity-filter", name: "活跃度筛选假设", type: "text", required: false },
        { slug: "endorsement-rubric", name: "背景背书标准", type: "longtext", required: false },
        { slug: "expertise-rubric", name: "专业深广度标准", type: "longtext", required: false },
        { slug: "teaching-rubric", name: "授课服务能力标准", type: "longtext", required: false },
        { slug: "qualify-threshold", name: "合格分数线", type: "number", required: true },
        { slug: "updated-at", name: "更新时间", type: "date", required: false },
        { slug: "onboarding-version", name: "引导完成版本", type: "number", required: false },
      ],
    },
    {
      key: "candidates",
      name: "候选讲师",
      slug: "instructor-sourcing-candidates-v1",
      description:
        "One row per instructor candidate with per-axis scores, notes, review status, and connection timestamps",
      nodeId: "",
      baseId: "",
      fields: [
        { slug: "name", name: "候选人姓名", type: "text", required: true },
        { slug: "platform-headline", name: "平台公开简介", type: "text", required: false },
        { slug: "search-context", name: "搜索来源", type: "text", required: false },
        { slug: "endorsement-score", name: "背景背书分", type: "number", required: false },
        { slug: "expertise-score", name: "专业深广度分", type: "number", required: false },
        { slug: "teaching-score", name: "授课服务能力分", type: "number", required: false },
        { slug: "overall-score", name: "综合评分", type: "number", required: false },
        { slug: "match-notes", name: "评分依据", type: "longtext", required: false },
        { slug: "status", name: "状态", type: "text", required: false },
        { slug: "wechat-added-at", name: "微信添加时间", type: "date", required: false },
        { slug: "logged-at", name: "建联记录时间", type: "date", required: false },
      ],
    },
  ],
  permissions: {
    readProcedures: ["nodes.list", "nodes.get", "bases.get", "records.list"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata"],
    writeProcedures: ["bases.createChangeRequest", "records.changeRequest"],
  },
};
