export const appConfig = {
  appId: "kelly-launch",
  appName: "Kelly Launch",
  deployment: "cloud",
  locale: "auto",
  readOnly: false,
  spaceId: "",
  schemaVersion: 1,
  folder: {
    name: "Kelly Launch",
    description: "Product-launch command desk built on the RAMP discipline",
    nodeId: "",
    slug: "kelly-launch",
  },
  airApp: { name: "Kelly Launch", slug: "kelly-launch-app", resourceKey: "airapp" },
  bases: [
    {
      key: "items",
      name: "Launch Items",
      slug: "kelly-launch-items-v1",
      description: "RAMP checklist tasks and assets under human review",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "item-id", name: "Item ID", type: "text", required: true },
        { slug: "ref", name: "Ref", type: "number", required: false },
        { slug: "phase", name: "Phase", type: "text", required: false },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "owner", name: "Owner", type: "text", required: false },
        { slug: "channel-id", name: "Channel", type: "text", required: false },
        { slug: "readiness", name: "Readiness", type: "text", required: false },
        { slug: "proposed-action", name: "Proposed action", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "draft", name: "Draft", type: "longtext", required: false },
        { slug: "reason", name: "Reason", type: "longtext", required: false },
        { slug: "format", name: "Format", type: "text", required: false },
        { slug: "risk", name: "Risk", type: "text", required: false },
        { slug: "created-at", name: "Created at", type: "text", required: false },
        { slug: "decision-note", name: "Decision note", type: "longtext", required: false },
        { slug: "decided-at", name: "Decided at", type: "text", required: false },
      ],
    },
    {
      key: "channels",
      name: "Channels",
      slug: "kelly-launch-channels-v1",
      description: "Launch channels and their submission status",
      nodeId: "",
      baseId: "",
      readLimit: 30,
      fields: [
        { slug: "channel-id", name: "Channel ID", type: "text", required: true },
        { slug: "type", name: "Type", type: "text", required: false },
        { slug: "display-name", name: "Display name", type: "text", required: false },
        { slug: "submission-status", name: "Submission status", type: "text", required: false },
      ],
    },
    {
      key: "runbook",
      name: "Runbook",
      slug: "kelly-launch-runbook-v1",
      description: "Ordered launch-day timeline",
      nodeId: "",
      baseId: "",
      readLimit: 50,
      fields: [
        { slug: "step-id", name: "Step ID", type: "text", required: true },
        { slug: "offset", name: "Offset", type: "text", required: false },
        { slug: "at", name: "At", type: "text", required: false },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "owner", name: "Owner", type: "text", required: false },
        { slug: "note", name: "War-room note", type: "longtext", required: false },
      ],
    },
    {
      key: "settings",
      name: "Settings",
      slug: "kelly-launch-settings-v1",
      description: "Product/launch profile, readiness policy, and the agent lock",
      nodeId: "",
      baseId: "",
      readLimit: 20,
      fields: [
        { slug: "record-id", name: "Record ID", type: "text", required: true },
        { slug: "kind", name: "Kind", type: "text", required: true },
        { slug: "name", name: "Name", type: "text", required: false },
        { slug: "payload", name: "Payload", type: "longtext", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
  ],
  permissions: {
    readProcedures: ["nodes.list", "nodes.get", "bases.get", "records.list"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata"],
    writeProcedures: ["records.changeRequest", "bases.createChangeRequest"],
  },
};
