export const appConfig = {
  appId: "kelly-legal-contracts",
  appName: "Kelly Legal Contracts",
  deployment: "cloud",
  locale: "auto",
  readOnly: false,
  spaceId: "",
  schemaVersion: 1,
  folder: {
    name: "Kelly Legal Contracts",
    description:
      "Legal-contract review desk: contract library, clause issues, risk checks, clause playbook, and a review queue",
    nodeId: "",
    slug: "kelly-legal-contracts",
  },
  bases: [
    {
      key: "contracts",
      name: "Contracts",
      slug: "kelly-legal-contracts-contracts-v1",
      description: "Contract library referenced by clause issues (NDA/MSA/DPA/SOW)",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "contract-id", name: "Contract ID", type: "text", required: true },
        { slug: "ref", name: "Ref", type: "number", required: false },
        { slug: "name", name: "Name", type: "text", required: false },
        { slug: "sku", name: "Counterparty", type: "text", required: false },
        { slug: "category", name: "Matter type", type: "text", required: false },
        { slug: "source", name: "Source", type: "text", required: false },
        { slug: "platforms", name: "Workstreams", type: "longtext", required: false },
        { slug: "locales", name: "Jurisdictions", type: "longtext", required: false },
        { slug: "specs", name: "Contract facts", type: "longtext", required: false },
        { slug: "features", name: "Key obligations", type: "longtext", required: false },
        { slug: "keywords", name: "Watch terms", type: "longtext", required: false },
        { slug: "images", name: "Document checklist", type: "longtext", required: false },
        { slug: "notes", name: "Notes", type: "longtext", required: false },
        { slug: "created-at", name: "Created at", type: "text", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
    {
      key: "issues",
      name: "Issues",
      slug: "kelly-legal-contracts-issues-v1",
      description: "Clause issues — structured fields, workflow status, and the review-queue decision on the same row",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "issue-id", name: "Issue ID", type: "text", required: true },
        { slug: "ref", name: "Ref", type: "number", required: false },
        { slug: "contract-id", name: "Contract ID", type: "text", required: false },
        { slug: "platform", name: "Workstream", type: "text", required: false },
        { slug: "locale", name: "Jurisdiction", type: "text", required: false },
        { slug: "variant-group", name: "Variant group", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "compliance-score", name: "Risk score", type: "number", required: false },
        { slug: "keyword-strategy", name: "Reviewer rationale", type: "longtext", required: false },
        { slug: "title", name: "Issue title", type: "text", required: false },
        { slug: "subtitle", name: "Short issue", type: "text", required: false },
        { slug: "bullets", name: "Risk notes", type: "longtext", required: false },
        { slug: "description", name: "Fallback language", type: "longtext", required: false },
        { slug: "search-terms", name: "Negotiation notes", type: "longtext", required: false },
        { slug: "seo-title", name: "Memo title", type: "text", required: false },
        { slug: "seo-description", name: "Memo summary", type: "longtext", required: false },
        { slug: "selling-points", name: "Business ask", type: "longtext", required: false },
        { slug: "aplus-outline", name: "Redline / memo outline", type: "longtext", required: false },
        { slug: "item-specifics", name: "Structured facts", type: "longtext", required: false },
        { slug: "compliance-summary", name: "Risk summary", type: "longtext", required: false },
        { slug: "suggestions", name: "Agent suggestions", type: "longtext", required: false },
        { slug: "decision-action", name: "Decision action", type: "text", required: false },
        { slug: "decision-note", name: "Decision note", type: "longtext", required: false },
        { slug: "decided-at", name: "Decided at", type: "text", required: false },
        { slug: "execution-status", name: "Execution status", type: "text", required: false },
        { slug: "execution-operation", name: "Execution operation", type: "text", required: false },
        { slug: "execution-target", name: "Execution target", type: "text", required: false },
        { slug: "execution-detail", name: "Execution detail", type: "longtext", required: false },
        { slug: "executed-at", name: "Executed at", type: "text", required: false },
        { slug: "created-at", name: "Created at", type: "text", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
    {
      key: "checks",
      name: "Checks",
      slug: "kelly-legal-contracts-checks-v1",
      description: "Per-issue, per-rule risk-check results",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "check-id", name: "Check ID", type: "text", required: true },
        { slug: "issue-id", name: "Issue ID", type: "text", required: false },
        { slug: "rule-id", name: "Rule ID", type: "text", required: false },
        { slug: "severity", name: "Severity", type: "text", required: false },
        { slug: "result", name: "Result", type: "text", required: false },
        { slug: "evidence", name: "Evidence", type: "longtext", required: false },
        { slug: "ref-rules", name: "Referenced hard-stop terms", type: "longtext", required: false },
        { slug: "ref-claims", name: "Referenced clauses", type: "longtext", required: false },
        { slug: "checked-at", name: "Checked at", type: "text", required: false },
      ],
    },
    {
      key: "claims",
      name: "Claims",
      slug: "kelly-legal-contracts-claims-v1",
      description: "Clause playbook — approved fallback clauses and rejected positions",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "claim-id", name: "Claim ID", type: "text", required: true },
        { slug: "text", name: "Clause / position", type: "longtext", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "category", name: "Category", type: "text", required: false },
        { slug: "substantiation", name: "When to use", type: "longtext", required: false },
        { slug: "evidence", name: "Source", type: "longtext", required: false },
        { slug: "approved-by", name: "Approved by", type: "text", required: false },
        { slug: "approved-at", name: "Approved at", type: "text", required: false },
        { slug: "notes", name: "Notes", type: "longtext", required: false },
        { slug: "created-at", name: "Created at", type: "text", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
    {
      key: "claim_rules",
      name: "Claim Rules",
      slug: "kelly-legal-contracts-claim-rules-v1",
      description: "Clause playbook — hard-stop / restricted-phrase rules",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "rule-id", name: "Rule ID", type: "text", required: true },
        { slug: "phrase", name: "Term", type: "text", required: false },
        { slug: "type", name: "Type", type: "text", required: false },
        { slug: "severity", name: "Severity", type: "text", required: false },
        { slug: "reason", name: "Why it matters", type: "longtext", required: false },
        { slug: "alternative", name: "Fallback", type: "longtext", required: false },
        { slug: "created-at", name: "Created at", type: "text", required: false },
      ],
    },
    {
      key: "settings",
      name: "Settings",
      slug: "kelly-legal-contracts-settings-v1",
      description:
        "Legal profile, workstream rule sets, hard-stop terms, and export preferences — a single settings row",
      nodeId: "",
      baseId: "",
      readLimit: 20,
      fields: [
        { slug: "record-id", name: "Record ID", type: "text", required: true },
        { slug: "seller-brand", name: "Company", type: "text", required: false },
        { slug: "seller-entity", name: "Entity", type: "text", required: false },
        { slug: "seller-tone", name: "Review style", type: "text", required: false },
        { slug: "locales", name: "Jurisdictions", type: "longtext", required: false },
        { slug: "platforms", name: "Workstreams", type: "longtext", required: false },
        { slug: "banned-words", name: "Hard-stop terms", type: "longtext", required: false },
        { slug: "competitor-brands", name: "Restricted positions", type: "longtext", required: false },
        { slug: "keyword-stuffing-max-repeats", name: "Repeat threshold", type: "number", required: false },
        { slug: "allowed-all-caps", name: "Allowed all-caps terms", type: "longtext", required: false },
        { slug: "export-format", name: "Export format", type: "text", required: false },
        { slug: "export-out-dir", name: "Export out dir", type: "text", required: false },
        { slug: "publish-handoff-to-agent", name: "Handoff to agent", type: "text", required: false },
        { slug: "publish-requires-approval", name: "Requires approval", type: "text", required: false },
      ],
    },
  ],
  permissions: {
    readProcedures: ["nodes.list", "nodes.get", "bases.get", "records.list"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata"],
    writeProcedures: ["records.changeRequest", "bases.createChangeRequest"],
  },
};
