export const appConfig = {
  appId: "kelly-legal-casebase-ingest",
  appName: "Legal Casebase Ingest",
  deployment: "cloud",
  locale: "auto",
  readOnly: false,
  spaceId: "",
  schemaVersion: 1,
  folder: {
    name: "Legal Casebase Ingest",
    description:
      "Casebase intake and anonymization QA desk for law-firm judgment and arbitral award documents: agent-prepared case records, canonical case-library groupings, deterministic QA checks, and a review queue (approve / request changes / revise / block) before a record becomes a searchable knowledge asset",
    nodeId: "",
    slug: "kelly-legal-casebase-ingest",
  },
  airApp: { name: "Legal Casebase Ingest", slug: "kelly-legal-casebase-ingest-app", resourceKey: "airapp" },
  bases: [
    {
      key: "items",
      name: "Case Records",
      slug: "kelly-legal-casebase-ingest-items-v1",
      description:
        "Agent-prepared case records — anonymization/taxonomy facts, workflow status, and the review-queue decision on the same row",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "item-id", name: "Item ID", type: "text", required: true },
        { slug: "ref", name: "Ref", type: "text", required: false },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "category", name: "Category", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "owner", name: "Owner", type: "text", required: false },
        { slug: "risk", name: "Risk (JSON array)", type: "longtext", required: false },
        { slug: "summary", name: "Summary", type: "longtext", required: false },
        { slug: "body", name: "Body", type: "longtext", required: false },
        { slug: "recommendation", name: "Recommendation", type: "longtext", required: false },
        { slug: "proposed-action", name: "Proposed action", type: "text", required: false },
        { slug: "draft", name: "Editable draft", type: "longtext", required: false },
        { slug: "evidence", name: "Evidence (JSON array)", type: "longtext", required: false },
        { slug: "cause", name: "Cause of action", type: "text", required: false },
        { slug: "court", name: "Court / arbitral body", type: "text", required: false },
        { slug: "procedure", name: "Procedure / document type", type: "text", required: false },
        { slug: "outcome", name: "Outcome", type: "text", required: false },
        { slug: "paragraphs", name: "Source paragraphs (JSON array)", type: "longtext", required: false },
        { slug: "extraction-confidence", name: "Extraction confidence", type: "number", required: false },
        { slug: "duplicate-score", name: "Duplicate score", type: "number", required: false },
        { slug: "ingest-bucket", name: "Ingest bucket", type: "text", required: false },
        { slug: "pii-cleared", name: "PII cleared", type: "text", required: false },
        { slug: "parties-redacted", name: "Parties redacted", type: "text", required: false },
        { slug: "contacts-redacted", name: "Contacts redacted", type: "text", required: false },
        { slug: "decision-action", name: "Decision action", type: "text", required: false },
        { slug: "decision-note", name: "Decision note", type: "longtext", required: false },
        { slug: "decided-at", name: "Decided at", type: "text", required: false },
        { slug: "execution-status", name: "Execution status", type: "text", required: false },
        { slug: "execution-operation", name: "Execution operation", type: "text", required: false },
        { slug: "execution-target", name: "Execution target", type: "text", required: false },
        { slug: "execution-detail", name: "Execution detail", type: "longtext", required: false },
        { slug: "executed-at", name: "Executed at", type: "text", required: false },
        { slug: "created-at", name: "Created at", type: "text", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
    {
      key: "entities",
      name: "Case Library",
      slug: "kelly-legal-casebase-ingest-entities-v1",
      description: "Canonical case-library groupings by cause, court, lawyer, and status — not raw source documents",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "entity-id", name: "Entity ID", type: "text", required: true },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "meta", name: "Meta", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "owner", name: "Owner", type: "text", required: false },
        { slug: "summary", name: "Summary", type: "longtext", required: false },
        { slug: "tags", name: "Tags (JSON array)", type: "longtext", required: false },
        { slug: "metrics", name: "Metrics (JSON object)", type: "longtext", required: false },
      ],
    },
    {
      key: "checks",
      name: "Checks",
      slug: "kelly-legal-casebase-ingest-checks-v1",
      description: "Deterministic QA checks for PII leakage, missing metadata, source coverage, and tag confidence",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "check-id", name: "Check ID", type: "text", required: true },
        { slug: "label", name: "Label", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "detail", name: "Detail", type: "longtext", required: false },
        { slug: "item-id", name: "Item ID", type: "text", required: false },
        { slug: "severity", name: "Severity", type: "text", required: false },
      ],
    },
    {
      key: "settings",
      name: "Settings",
      slug: "kelly-legal-casebase-ingest-settings-v1",
      description:
        "Firm profile, ingestion/anonymization/taxonomy policy, and export preferences — a single settings row",
      nodeId: "",
      baseId: "",
      readLimit: 20,
      fields: [
        { slug: "record-id", name: "Record ID", type: "text", required: true },
        { slug: "firm-name", name: "Firm name", type: "text", required: false },
        { slug: "branch", name: "Branch", type: "text", required: false },
        {
          slug: "default-jurisdictions",
          name: "Default jurisdictions (JSON array)",
          type: "longtext",
          required: false,
        },
        { slug: "reviewer-role", name: "Reviewer role", type: "text", required: false },
        {
          slug: "allowed-document-types",
          name: "Allowed document types (JSON array)",
          type: "longtext",
          required: false,
        },
        { slug: "anonymization-standard", name: "Anonymization standard", type: "text", required: false },
        { slug: "require-party-redaction", name: "Require party redaction", type: "text", required: false },
        {
          slug: "require-business-secret-review",
          name: "Require business-secret review",
          type: "text",
          required: false,
        },
        { slug: "sample-rate", name: "Reviewer sample rate", type: "number", required: false },
        {
          slug: "required-taxonomy-fields",
          name: "Required taxonomy fields (JSON array)",
          type: "longtext",
          required: false,
        },
        { slug: "export-format", name: "Export format", type: "text", required: false },
        { slug: "export-out-dir", name: "Export out dir", type: "text", required: false },
      ],
    },
  ],
  permissions: {
    readProcedures: ["nodes.list", "nodes.get", "bases.get", "records.list"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata"],
    writeProcedures: ["records.changeRequest", "bases.createChangeRequest"],
  },
};
