export const appConfig = {
  appId: "kelly-local-model-lab",
  appName: "Kelly Local Model Lab",
  deployment: "cloud",
  locale: "auto",
  readOnly: false,
  spaceId: "",
  schemaVersion: 1,
  folder: {
    name: "Kelly Local Model Lab",
    slug: "kelly-local-model-lab",
    description:
      "Busabase-backed control plane for curating training examples, queuing local Apple Silicon fine-tuning runs, comparing locked evaluations, and registering model adapters.",
  },
  airApp: {
    name: "Kelly Local Model Lab",
    slug: "kelly-local-model-lab-app",
    resourceKey: "kelly-local-model-lab-app",
  },
  drive: {
    name: "Model Lab Files",
    slug: "kelly-local-model-lab-files",
    description: "Immutable dataset snapshots, LoRA adapters, evaluation reports, and model cards.",
  },
  bases: [
    {
      key: "training-examples",
      name: "Training Examples",
      slug: "kelly-local-model-lab-training-examples",
      description: "Human-reviewed prompt and ideal-response pairs used to build immutable training snapshots.",
      readLimit: 50,
      fields: [
        { slug: "example-id", name: "Example ID", type: "text", required: true },
        { slug: "task", name: "Task", type: "text", required: true },
        { slug: "prompt", name: "Prompt", type: "longtext", required: true },
        { slug: "ideal-response", name: "Ideal response", type: "longtext", required: true },
        { slug: "split", name: "Split", type: "text", required: true },
        { slug: "status", name: "Status", type: "text", required: true },
        { slug: "source", name: "Source", type: "text", required: false },
        { slug: "content-hash", name: "Content hash", type: "text", required: true },
        { slug: "review-note", name: "Review note", type: "longtext", required: false },
        { slug: "reviewed-at", name: "Reviewed at", type: "text", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
    {
      key: "training-runs",
      name: "Training Runs",
      slug: "kelly-local-model-lab-training-runs",
      description:
        "Reviewable local training jobs with immutable inputs, claims, heartbeat, status, and result references.",
      readLimit: 50,
      fields: [
        { slug: "run-id", name: "Run ID", type: "text", required: true },
        { slug: "title", name: "Title", type: "text", required: true },
        { slug: "base-model", name: "Base model", type: "text", required: true },
        { slug: "base-revision", name: "Base revision", type: "text", required: false },
        { slug: "method", name: "Method", type: "text", required: true },
        { slug: "status", name: "Status", type: "text", required: true },
        { slug: "dataset-snapshot", name: "Dataset snapshot file", type: "text", required: true },
        { slug: "dataset-hash", name: "Dataset hash", type: "text", required: true },
        { slug: "config", name: "Training config JSON", type: "longtext", required: true },
        { slug: "claimant", name: "Claimant", type: "text", required: false },
        { slug: "claimed-at", name: "Claimed at", type: "text", required: false },
        { slug: "heartbeat-at", name: "Heartbeat at", type: "text", required: false },
        { slug: "attempt", name: "Attempt", type: "number", required: false },
        { slug: "adapter-file", name: "Adapter file", type: "text", required: false },
        { slug: "report-file", name: "Report file", type: "text", required: false },
        { slug: "error", name: "Sanitized error", type: "longtext", required: false },
        { slug: "created-at", name: "Created at", type: "text", required: true },
        { slug: "completed-at", name: "Completed at", type: "text", required: false },
      ],
    },
    {
      key: "evaluations",
      name: "Evaluations",
      slug: "kelly-local-model-lab-evaluations",
      description: "Locked baseline and adapter evaluation results with exact metrics and human promotion verdicts.",
      readLimit: 50,
      fields: [
        { slug: "evaluation-id", name: "Evaluation ID", type: "text", required: true },
        { slug: "run-id", name: "Run ID", type: "text", required: true },
        { slug: "model-role", name: "Model role", type: "text", required: true },
        { slug: "dataset-hash", name: "Evaluation dataset hash", type: "text", required: true },
        { slug: "case-count", name: "Case count", type: "number", required: true },
        { slug: "json-valid-pct", name: "JSON valid %", type: "number", required: false },
        { slug: "schema-valid-pct", name: "Schema valid %", type: "number", required: false },
        { slug: "exact-field-pct", name: "Exact field %", type: "number", required: false },
        { slug: "latency-ms", name: "Median latency ms", type: "number", required: false },
        { slug: "report-file", name: "Report file", type: "text", required: false },
        { slug: "verdict", name: "Verdict", type: "text", required: false },
        { slug: "decision-note", name: "Decision note", type: "longtext", required: false },
        { slug: "evaluated-at", name: "Evaluated at", type: "text", required: true },
      ],
    },
    {
      key: "model-registry",
      name: "Model Registry",
      slug: "kelly-local-model-lab-model-registry",
      description: "Base models and adapter versions that passed evaluation, including provenance and lifecycle.",
      readLimit: 50,
      fields: [
        { slug: "model-id", name: "Model ID", type: "text", required: true },
        { slug: "display-name", name: "Display name", type: "text", required: true },
        { slug: "base-model", name: "Base model", type: "text", required: true },
        { slug: "base-revision", name: "Base revision", type: "text", required: false },
        { slug: "adapter-file", name: "Adapter file", type: "text", required: false },
        { slug: "training-run-id", name: "Training run ID", type: "text", required: false },
        { slug: "dataset-hash", name: "Dataset hash", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: true },
        { slug: "notes", name: "Notes", type: "longtext", required: false },
        { slug: "registered-at", name: "Registered at", type: "text", required: true },
      ],
    },
    {
      key: "settings",
      name: "Settings",
      slug: "kelly-local-model-lab-settings",
      description: "Sanitized model-lab defaults, evaluation gates, onboarding state, and operator preferences.",
      readLimit: 20,
      fields: [
        { slug: "record-id", name: "Record ID", type: "text", required: true },
        { slug: "kind", name: "Kind", type: "text", required: true },
        { slug: "payload", name: "Payload JSON", type: "longtext", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
  ],
  permissions: {
    readProcedures: ["nodes.list", "nodes.get", "bases.get", "records.list", "records.count"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata"],
    writeProcedures: ["records.changeRequest", "bases.createChangeRequest"],
  },
};
