export const appConfig = {
  appId: "kelly-family-office",
  appName: "Kelly Family Office",
  deployment: "cloud",
  locale: "auto",
  readOnly: true,
  spaceId: "",
  schemaVersion: 1,
  folder: {
    name: "Kelly Family Office",
    description: "Multi-entity family-office consolidation dashboard",
    slug: "kelly-family-office",
  },
  airApp: { name: "Kelly Family Office", slug: "kelly-family-office-app", resourceKey: "kelly-family-office-app" },
  bases: [
    {
      key: "entities",
      name: "Entities",
      slug: "kelly-family-office-entities",
      description: "The individuals, trusts, companies, funds, and foundations being consolidated",
      readLimit: 20,
      fields: [
        { slug: "entity-id", name: "Entity ID", type: "text", required: true },
        { slug: "name", name: "Name", type: "text", required: false },
        { slug: "type", name: "Type", type: "text", required: false },
        { slug: "member", name: "Member", type: "text", required: false },
      ],
    },
    {
      key: "accounts",
      name: "Accounts",
      slug: "kelly-family-office-accounts",
      description: "Custodian/institution accounts held by each entity",
      readLimit: 40,
      fields: [
        { slug: "account-id", name: "Account ID", type: "text", required: true },
        { slug: "entity-id", name: "Entity ID", type: "text", required: false },
        { slug: "institution", name: "Institution", type: "text", required: false },
        { slug: "account-type", name: "Account type", type: "text", required: false },
        { slug: "currency", name: "Currency", type: "text", required: false },
        { slug: "display-name", name: "Display name", type: "text", required: false },
        { slug: "as-of", name: "As of", type: "text", required: false },
      ],
    },
    {
      key: "holdings",
      name: "Holdings",
      slug: "kelly-family-office-holdings",
      description: "Individual holdings across every account",
      readLimit: 100,
      fields: [
        { slug: "holding-id", name: "Holding ID", type: "text", required: true },
        { slug: "entity-id", name: "Entity ID", type: "text", required: false },
        { slug: "account-id", name: "Account ID", type: "text", required: false },
        { slug: "symbol", name: "Symbol", type: "text", required: false },
        { slug: "name", name: "Name", type: "text", required: false },
        { slug: "asset-class", name: "Asset class", type: "text", required: false },
        { slug: "quantity", name: "Quantity", type: "number", required: false },
        { slug: "cost-basis", name: "Cost basis", type: "number", required: false },
        { slug: "market-value", name: "Market value", type: "number", required: false },
        { slug: "currency", name: "Currency", type: "text", required: false },
        { slug: "as-of", name: "As of", type: "text", required: false },
      ],
    },
    {
      key: "settings",
      name: "Settings",
      slug: "kelly-family-office-settings",
      description: "Base currency, FX rates, target allocation, and onboarding marker",
      readLimit: 20,
      fields: [
        { slug: "record-id", name: "Record ID", type: "text", required: true },
        { slug: "kind", name: "Kind", type: "text", required: true },
        { slug: "name", name: "Name", type: "text", required: false },
        { slug: "payload", name: "Payload", type: "longtext", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
  ],
  permissions: {
    readProcedures: ["nodes.list", "nodes.get", "bases.get", "records.list"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata"],
    writeProcedures: [],
  },
};
