export const appConfig = {
  appId: "kelly-pr-review",
  appName: "Kelly PR Review",
  deployment: "cloud",
  locale: "auto",
  readOnly: false,
  spaceId: "",
  schemaVersion: 1,
  folder: {
    name: "Kelly PR Review",
    description: "GitHub pull request review desk backed by the gh CLI",
    nodeId: "",
    slug: "kelly-pr-review",
  },
  bases: [
    {
      key: "reviews",
      name: "Reviews",
      slug: "kelly-pr-review-reviews-v1",
      description: "GitHub pull request review queue, review notes, and human verdicts",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "item-id", name: "Item ID", type: "text", required: true },
        { slug: "repo", name: "Repo", type: "text", required: false },
        { slug: "number", name: "PR number", type: "number", required: false },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "author", name: "Author", type: "text", required: false },
        { slug: "url", name: "URL", type: "text", required: false },
        { slug: "summary", name: "Summary", type: "longtext", required: false },
        { slug: "body", name: "Body", type: "longtext", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "proposed-action", name: "Proposed action", type: "text", required: false },
        { slug: "reason", name: "Reason", type: "longtext", required: false },
        { slug: "risk", name: "Risk", type: "longtext", required: false },
        { slug: "labels", name: "Labels", type: "longtext", required: false },
        { slug: "changed-files", name: "Changed files", type: "longtext", required: false },
        { slug: "additions", name: "Additions", type: "number", required: false },
        { slug: "deletions", name: "Deletions", type: "number", required: false },
        { slug: "comments-count", name: "Comments count", type: "number", required: false },
        { slug: "checks", name: "Checks", type: "text", required: false },
        { slug: "state", name: "State", type: "text", required: false },
        { slug: "merged", name: "Merged", type: "text", required: false },
        { slug: "merged-at", name: "Merged at", type: "text", required: false },
        { slug: "is-draft", name: "Is draft", type: "text", required: false },
        { slug: "created-at", name: "Created at", type: "text", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
        { slug: "review-body", name: "Review body", type: "longtext", required: false },
        { slug: "patch-excerpt", name: "Patch excerpt", type: "longtext", required: false },
        { slug: "decision-action", name: "Decision action", type: "text", required: false },
        { slug: "decision-note", name: "Decision note", type: "longtext", required: false },
        { slug: "decided-at", name: "Decided at", type: "text", required: false },
        { slug: "execution-status", name: "Execution status", type: "text", required: false },
        { slug: "execution-detail", name: "Execution detail", type: "longtext", required: false },
        { slug: "tested", name: "Tested", type: "text", required: false },
        { slug: "tested-at", name: "Tested at", type: "text", required: false },
        { slug: "test-note", name: "Test note", type: "longtext", required: false },
        { slug: "test-evidence", name: "Test evidence", type: "longtext", required: false },
      ],
    },
    {
      key: "settings",
      name: "Settings",
      slug: "kelly-pr-review-settings-v1",
      description: "Reviewer/repo profile and the agent lock",
      nodeId: "",
      baseId: "",
      readLimit: 20,
      fields: [
        { slug: "record-id", name: "Record ID", type: "text", required: true },
        { slug: "kind", name: "Kind", type: "text", required: true },
        { slug: "payload", name: "Payload", type: "longtext", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
  ],
  permissions: {
    readProcedures: ["nodes.list", "nodes.get", "bases.get", "records.list"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata"],
    writeProcedures: ["records.changeRequest", "bases.createChangeRequest"],
  },
};
