export const appConfig = {
  appId: "kelly-crm",
  appName: "Kelly CRM",
  deployment: "cloud",
  locale: "auto",
  readOnly: false,
  spaceId: "",
  schemaVersion: 1,
  folder: {
    name: "Kelly CRM",
    description: "Contacts, companies, deals, and follow-up review workspace",
    nodeId: "",
    slug: "kelly-crm",
  },
  bases: [
    {
      key: "companies",
      name: "公司",
      slug: "kelly-crm-companies-v1",
      description: "Companies referenced by contacts and deals",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "company-id", name: "公司 ID", type: "text", required: true },
        { slug: "name", name: "公司名称", type: "text", required: true },
        { slug: "domain", name: "域名", type: "text", required: false },
        { slug: "industry", name: "行业", type: "text", required: false },
        { slug: "size", name: "规模", type: "text", required: false },
        { slug: "location", name: "地点", type: "text", required: false },
        { slug: "notes", name: "备注", type: "longtext", required: false },
      ],
    },
    {
      key: "contacts",
      name: "联系人",
      slug: "kelly-crm-contacts-v1",
      description: "People, their relationship strength, and next follow-up",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "contact-id", name: "联系人 ID", type: "text", required: true },
        { slug: "name", name: "姓名", type: "text", required: true },
        { slug: "company-id", name: "所属公司", type: "text", required: false },
        { slug: "role", name: "职位", type: "text", required: false },
        { slug: "email", name: "邮箱", type: "text", required: false },
        { slug: "relationship", name: "关系强度", type: "text", required: false },
        { slug: "tags", name: "标签", type: "text", required: false },
        { slug: "last-touch-at", name: "最近联系时间", type: "text", required: false },
        { slug: "next-followup-at", name: "下次跟进日期", type: "text", required: false },
        { slug: "agent-notes", name: "Agent 备注", type: "longtext", required: false },
        { slug: "channels", name: "触达渠道", type: "text", required: false },
      ],
    },
    {
      key: "deals",
      name: "交易",
      slug: "kelly-crm-deals-v1",
      description: "Pipeline deals with stage, amount, and next step",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "deal-id", name: "交易 ID", type: "text", required: true },
        { slug: "name", name: "交易名称", type: "text", required: true },
        { slug: "company-id", name: "所属公司", type: "text", required: false },
        { slug: "primary-contact-id", name: "主要联系人", type: "text", required: false },
        { slug: "contact-ids", name: "关联联系人", type: "text", required: false },
        { slug: "stage", name: "阶段", type: "text", required: false },
        { slug: "amount", name: "金额", type: "number", required: false },
        { slug: "currency", name: "币种", type: "text", required: false },
        { slug: "probability", name: "赢单概率", type: "number", required: false },
        { slug: "next-step", name: "下一步", type: "text", required: false },
        { slug: "owner", name: "负责人", type: "text", required: false },
        { slug: "opened-at", name: "开始日期", type: "text", required: false },
        { slug: "expected-close", name: "预计成交日期", type: "text", required: false },
        { slug: "last-activity-at", name: "最近活动时间", type: "text", required: false },
        { slug: "status", name: "状态", type: "text", required: false },
        { slug: "agent-next-action", name: "Agent 建议动作", type: "longtext", required: false },
        { slug: "notes", name: "备注", type: "longtext", required: false },
      ],
    },
    {
      key: "interactions",
      name: "互动记录",
      slug: "kelly-crm-interactions-v1",
      description: "Email, meeting, call, chat, social, and note touchpoints",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "interaction-id", name: "互动 ID", type: "text", required: true },
        { slug: "contact-id", name: "联系人", type: "text", required: true },
        { slug: "company-id", name: "所属公司", type: "text", required: false },
        { slug: "deal-id", name: "关联交易", type: "text", required: false },
        { slug: "type", name: "类型", type: "text", required: false },
        { slug: "occurred-at", name: "发生时间", type: "text", required: false },
        { slug: "direction", name: "方向", type: "text", required: false },
        { slug: "summary", name: "摘要", type: "longtext", required: false },
        { slug: "source", name: "来源", type: "text", required: false },
      ],
    },
    {
      key: "followups",
      name: "跟进队列",
      slug: "kelly-crm-followups-v1",
      description: "Agent-drafted follow-ups under human review before handoff",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "followup-id", name: "跟进 ID", type: "text", required: true },
        { slug: "ref", name: "序号", type: "number", required: false },
        { slug: "contact-id", name: "联系人", type: "text", required: true },
        { slug: "deal-id", name: "关联交易", type: "text", required: false },
        { slug: "channel-id", name: "渠道 ID", type: "text", required: false },
        { slug: "channel-type", name: "渠道类型", type: "text", required: false },
        { slug: "subject", name: "主题", type: "text", required: false },
        { slug: "reason", name: "触发原因", type: "longtext", required: false },
        { slug: "risk", name: "风险标签", type: "text", required: false },
        { slug: "due-at", name: "截止日期", type: "text", required: false },
        { slug: "status", name: "状态", type: "text", required: false },
        { slug: "suggested-reply", name: "草稿", type: "longtext", required: false },
        { slug: "decision-comment", name: "复核意见", type: "longtext", required: false },
        { slug: "decided-at", name: "决定时间", type: "text", required: false },
        { slug: "decided-by", name: "决定人", type: "text", required: false },
        { slug: "created-at", name: "创建时间", type: "text", required: false },
      ],
    },
    {
      key: "settings",
      name: "设置",
      slug: "kelly-crm-settings-v1",
      description: "Operator profile, pipeline config, channels, and the agent lock",
      nodeId: "",
      baseId: "",
      readLimit: 20,
      fields: [
        { slug: "record-id", name: "记录 ID", type: "text", required: true },
        { slug: "kind", name: "类型", type: "text", required: true },
        { slug: "name", name: "名称", type: "text", required: false },
        { slug: "payload", name: "内容", type: "longtext", required: false },
        { slug: "updated-at", name: "更新时间", type: "text", required: false },
      ],
    },
  ],
  permissions: {
    readProcedures: ["nodes.list", "nodes.get", "bases.get", "records.list"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata"],
    writeProcedures: ["records.changeRequest", "bases.createChangeRequest"],
  },
};
