export const appConfig = {
  appId: "kelly-ideas",
  appName: "Kelly Ideas",
  deployment: "cloud",
  locale: "auto",
  readOnly: false,
  spaceId: "",
  schemaVersion: 1,
  folder: {
    name: "Kelly Ideas",
    description: "灵感库、咨询师追问，以及每条灵感的 BRD / MRD / PRD",
    slug: "kelly-ideas",
  },
  airApp: { name: "Kelly Ideas", slug: "kelly-ideas-app", resourceKey: "kelly-ideas-app" },
  bases: [
    {
      key: "ideas",
      name: "灵感库",
      slug: "kelly-ideas-ideas",
      description: "每一条灵感，以及它被打磨到什么程度",
      readLimit: 100,
      fields: [
        { slug: "record-id", name: "记录 ID", type: "text", required: true },
        { slug: "title", name: "灵感名", type: "text", required: true },
        { slug: "one-liner", name: "一句话说清楚", type: "text", required: false },
        { slug: "problem", name: "谁的什么问题", type: "longtext", required: false },
        { slug: "who", name: "目标用户", type: "text", required: false },
        { slug: "why-now", name: "为什么是现在", type: "longtext", required: false },
        { slug: "stage", name: "推进到哪一层", type: "text", required: false },
        { slug: "status", name: "状态", type: "text", required: false },
        { slug: "clarity", name: "清晰度", type: "number", required: false },
        { slug: "open-questions", name: "待回答问题数", type: "number", required: false },
        { slug: "source", name: "灵感来源", type: "text", required: false },
        { slug: "tags", name: "标签", type: "text", required: false },
        { slug: "agent-next-action", name: "Agent 建议动作", type: "longtext", required: false },
        { slug: "notes", name: "备注", type: "longtext", required: false },
        { slug: "created-at", name: "创建时间", type: "text", required: false },
        { slug: "updated-at", name: "更新时间", type: "text", required: false },
      ],
    },
    {
      key: "documents",
      name: "文档",
      slug: "kelly-ideas-documents",
      description: "同一条灵感的 BRD / MRD / PRD 三份文档",
      readLimit: 100,
      fields: [
        { slug: "record-id", name: "记录 ID", type: "text", required: true },
        { slug: "idea-id", name: "所属灵感", type: "text", required: true },
        { slug: "kind", name: "文档类型", type: "text", required: true },
        { slug: "title", name: "标题", type: "text", required: false },
        { slug: "body", name: "正文", type: "longtext", required: false },
        { slug: "status", name: "状态", type: "text", required: false },
        { slug: "version", name: "版本", type: "number", required: false },
        { slug: "gaps", name: "还缺什么", type: "longtext", required: false },
        { slug: "updated-at", name: "更新时间", type: "text", required: false },
      ],
    },
    {
      key: "questions",
      name: "咨询师追问",
      slug: "kelly-ideas-questions",
      description: "把模糊需求问清楚的那些问题，以及你的回答",
      readLimit: 100,
      fields: [
        { slug: "record-id", name: "记录 ID", type: "text", required: true },
        { slug: "idea-id", name: "所属灵感", type: "text", required: true },
        { slug: "stage", name: "属于哪一层", type: "text", required: false },
        { slug: "question", name: "咨询师的问题", type: "longtext", required: true },
        { slug: "why-asking", name: "为什么问这个", type: "longtext", required: false },
        { slug: "answer", name: "你的回答", type: "longtext", required: false },
        { slug: "status", name: "状态", type: "text", required: false },
        { slug: "position", name: "顺序", type: "number", required: false },
        { slug: "asked-at", name: "提问时间", type: "text", required: false },
        { slug: "answered-at", name: "回答时间", type: "text", required: false },
      ],
    },
    {
      key: "settings",
      name: "设置",
      slug: "kelly-ideas-settings",
      description: "Operator profile, language, accent, and the agent lock",
      readLimit: 20,
      fields: [
        { slug: "record-id", name: "记录 ID", type: "text", required: true },
        { slug: "kind", name: "类型", type: "text", required: true },
        { slug: "name", name: "名称", type: "text", required: false },
        { slug: "payload", name: "内容", type: "longtext", required: false },
        { slug: "updated-at", name: "更新时间", type: "text", required: false },
      ],
    },
  ],
  permissions: {
    readProcedures: ["nodes.list", "nodes.get", "bases.get", "records.list", "records.count"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata"],
    writeProcedures: ["records.changeRequest", "bases.createChangeRequest"],
  },
};

export const STAGES = ["idea", "brd", "mrd", "prd"];

export const DOC_KINDS = ["brd", "mrd", "prd"];
