export const appConfig = {
  appId: "kelly-tickets",
  appName: "Kelly Tickets",
  deployment: "cloud",
  locale: "auto",
  readOnly: false,
  spaceId: "",
  schemaVersion: 1,
  folder: {
    name: "Kelly Tickets",
    description: "Complaint/ticket triage-and-dispatch desk: intake stream, ticket board, and a dispatch review queue",
    slug: "kelly-tickets",
  },
  airApp: { name: "Kelly Tickets", slug: "kelly-tickets-app", resourceKey: "kelly-tickets-app" },
  bases: [
    {
      key: "crews",
      name: "Crews",
      slug: "kelly-tickets-crews",
      description: "Crews that tickets can be dispatched to",
      readLimit: 50,
      fields: [
        { slug: "crew-id", name: "Crew ID", type: "text", required: true },
        { slug: "name", name: "Name", type: "text", required: false },
        { slug: "skills", name: "Skills", type: "longtext", required: false },
        { slug: "members", name: "Members", type: "text", required: false },
        { slug: "contact-env", name: "Contact env", type: "text", required: false },
        { slug: "active", name: "Active", type: "text", required: false },
      ],
    },
    {
      key: "intake",
      name: "Intake",
      slug: "kelly-tickets-intake",
      description: "Raw complaints/requests as they arrived on a channel, before or after triage",
      readLimit: 100,
      fields: [
        { slug: "intake-id", name: "Intake ID", type: "text", required: true },
        { slug: "channel", name: "Channel", type: "text", required: false },
        { slug: "external-id", name: "External ID", type: "text", required: false },
        { slug: "content-hash", name: "Content hash", type: "text", required: false },
        { slug: "reporter", name: "Reporter", type: "text", required: false },
        { slug: "contact-masked", name: "Contact masked", type: "text", required: false },
        { slug: "unit", name: "Unit", type: "text", required: false },
        { slug: "location", name: "Location", type: "text", required: false },
        { slug: "text", name: "Text", type: "longtext", required: false },
        { slug: "received-at", name: "Received at", type: "text", required: false },
        { slug: "urgency-guess", name: "Urgency guess", type: "text", required: false },
        { slug: "category-guess", name: "Category guess", type: "text", required: false },
        { slug: "triage-state", name: "Triage state", type: "text", required: false },
        { slug: "ticket-id", name: "Ticket ID", type: "text", required: false },
        { slug: "attachments-note", name: "Attachments note", type: "text", required: false },
        { slug: "decision-action", name: "Decision action", type: "text", required: false },
        { slug: "decision-note", name: "Decision note", type: "longtext", required: false },
        { slug: "decision-fields", name: "Decision fields", type: "longtext", required: false },
        { slug: "decided-at", name: "Decided at", type: "text", required: false },
      ],
    },
    {
      key: "tickets",
      name: "Tickets",
      slug: "kelly-tickets-tickets",
      description: "Tickets tracked from classification through resolution, with an append-only history timeline",
      readLimit: 100,
      fields: [
        { slug: "ticket-id", name: "Ticket ID", type: "text", required: true },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "category", name: "Category", type: "text", required: false },
        { slug: "urgency", name: "Urgency", type: "text", required: false },
        { slug: "unit", name: "Unit", type: "text", required: false },
        { slug: "location", name: "Location", type: "text", required: false },
        { slug: "reporter", name: "Reporter", type: "text", required: false },
        { slug: "contact-masked", name: "Contact masked", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "crew-id", name: "Crew ID", type: "text", required: false },
        { slug: "assignee", name: "Assignee", type: "text", required: false },
        { slug: "created-at", name: "Created at", type: "text", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
        { slug: "resolved-at", name: "Resolved at", type: "text", required: false },
        { slug: "sla-due-at", name: "SLA due at", type: "text", required: false },
        { slug: "intake-ids", name: "Intake IDs", type: "longtext", required: false },
        { slug: "resolution-note", name: "Resolution note", type: "longtext", required: false },
        { slug: "history", name: "History", type: "longtext", required: false },
      ],
    },
    {
      key: "proposals",
      name: "Dispatch Proposals",
      slug: "kelly-tickets-proposals",
      description:
        "The dispatch review queue — proposed crew/priority/SLA, the human decision, and the execution marker on the same row",
      readLimit: 100,
      fields: [
        { slug: "proposal-id", name: "Proposal ID", type: "text", required: true },
        { slug: "ref", name: "Ref", type: "number", required: false },
        { slug: "ticket-id", name: "Ticket ID", type: "text", required: false },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "summary", name: "Summary", type: "text", required: false },
        { slug: "proposed-crew-id", name: "Proposed crew ID", type: "text", required: false },
        { slug: "proposed-assignee", name: "Proposed assignee", type: "text", required: false },
        { slug: "priority", name: "Priority", type: "text", required: false },
        { slug: "sla-due-at", name: "SLA due at", type: "text", required: false },
        { slug: "sla-hours", name: "SLA hours", type: "number", required: false },
        { slug: "reason", name: "Reason", type: "longtext", required: false },
        { slug: "note-to-crew", name: "Note to crew", type: "longtext", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "decision-action", name: "Decision action", type: "text", required: false },
        { slug: "decision-note", name: "Decision note", type: "longtext", required: false },
        { slug: "decision-draft", name: "Decision draft", type: "longtext", required: false },
        { slug: "decided-at", name: "Decided at", type: "text", required: false },
        { slug: "execution-status", name: "Execution status", type: "text", required: false },
        { slug: "execution-operations", name: "Execution operations", type: "longtext", required: false },
        { slug: "execution-detail", name: "Execution detail", type: "longtext", required: false },
        { slug: "executed-at", name: "Executed at", type: "text", required: false },
        { slug: "created-at", name: "Created at", type: "text", required: false },
      ],
    },
    {
      key: "sync-log",
      name: "Sync Log",
      slug: "kelly-tickets-sync-log",
      description: "Append-only history of ingest/triage/execute runs",
      readLimit: 100,
      fields: [
        { slug: "log-id", name: "Log ID", type: "text", required: true },
        { slug: "at", name: "At", type: "text", required: false },
        { slug: "source", name: "Source", type: "text", required: false },
        { slug: "action", name: "Action", type: "text", required: false },
        { slug: "detail", name: "Detail", type: "longtext", required: false },
        { slug: "count", name: "Count", type: "number", required: false },
      ],
    },
    {
      key: "settings",
      name: "Settings",
      slug: "kelly-tickets-settings",
      description: "Property profile, channels, categories, and SLA rules, a single settings row",
      readLimit: 20,
      fields: [
        { slug: "record-id", name: "Record ID", type: "text", required: true },
        { slug: "property-name", name: "Property name", type: "text", required: false },
        { slug: "buildings", name: "Buildings", type: "number", required: false },
        { slug: "timezone", name: "Timezone", type: "text", required: false },
        { slug: "channels", name: "Channels", type: "longtext", required: false },
        { slug: "categories", name: "Categories", type: "longtext", required: false },
        { slug: "sla-rules", name: "SLA rules", type: "longtext", required: false },
        { slug: "sla-default-hours", name: "SLA default hours", type: "number", required: false },
      ],
    },
  ],
  permissions: {
    readProcedures: ["nodes.list", "nodes.get", "bases.get", "records.list"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata"],
    writeProcedures: ["records.changeRequest", "bases.createChangeRequest"],
  },
};
