export const appConfig = {
  appId: "kelly-invest-webull",
  appName: "Kelly Invest (Webull)",
  deployment: "cloud",
  locale: "auto",
  readOnly: true,
  spaceId: "",
  schemaVersion: 1,
  folder: {
    name: "Kelly Invest (Webull)",
    description: "Read-only Webull brokerage portfolio dashboard (accounts, positions, insights)",
    slug: "kelly-invest-webull",
  },
  airApp: { name: "Kelly Invest (Webull)", slug: "kelly-invest-webull-app", resourceKey: "kelly-invest-webull-app" },
  bases: [
    {
      key: "accounts",
      name: "Accounts",
      slug: "kelly-invest-webull-accounts",
      description: "Webull cash and margin accounts with cash, buying power, and net liquidation",
      readLimit: 20,
      fields: [
        { slug: "account-id", name: "Account ID", type: "text", required: true },
        { slug: "account-type", name: "Account type", type: "text", required: false },
        { slug: "display-name", name: "Display name", type: "text", required: false },
        { slug: "currency", name: "Currency", type: "text", required: false },
        { slug: "net-liquidation", name: "Net liquidation", type: "number", required: false },
        { slug: "total-cash", name: "Total cash", type: "number", required: false },
        { slug: "buying-power", name: "Buying power", type: "number", required: false },
      ],
    },
    {
      key: "positions",
      name: "Positions",
      slug: "kelly-invest-webull-positions",
      description: "Webull holdings per account with cost basis, market value, and P/L",
      readLimit: 100,
      fields: [
        { slug: "position-id", name: "Position ID", type: "text", required: true },
        { slug: "symbol", name: "Symbol", type: "text", required: true },
        { slug: "name", name: "Name", type: "text", required: false },
        { slug: "asset-type", name: "Asset type", type: "text", required: false },
        { slug: "account-id", name: "Account ID", type: "text", required: true },
        { slug: "quantity", name: "Quantity", type: "number", required: false },
        { slug: "avg-cost", name: "Avg cost", type: "number", required: false },
        { slug: "last-price", name: "Last price", type: "number", required: false },
        { slug: "market-value", name: "Market value", type: "number", required: false },
        { slug: "cost-basis", name: "Cost basis", type: "number", required: false },
        { slug: "unrealized-pnl", name: "Unrealized P/L", type: "number", required: false },
        { slug: "unrealized-pnl-pct", name: "Unrealized P/L %", type: "number", required: false },
        { slug: "day-change", name: "Day change", type: "number", required: false },
        { slug: "day-change-pct", name: "Day change %", type: "number", required: false },
        { slug: "currency", name: "Currency", type: "text", required: false },
      ],
    },
    {
      key: "settings",
      name: "Settings",
      slug: "kelly-invest-webull-settings",
      description: "Sanitized config summary (no secrets) and onboarding marker, written by the trusted sync script",
      readLimit: 20,
      fields: [
        { slug: "record-id", name: "Record ID", type: "text", required: true },
        { slug: "kind", name: "Kind", type: "text", required: true },
        { slug: "name", name: "Name", type: "text", required: false },
        { slug: "payload", name: "Payload", type: "longtext", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
  ],
  permissions: {
    readProcedures: ["nodes.list", "nodes.get", "bases.get", "records.list"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata"],
    writeProcedures: [],
  },
};
