export const appConfig = {
  appId: "kelly-agent-observability",
  appName: "Kelly Agent Observability",
  deployment: "cloud",
  locale: "auto",
  readOnly: false,
  spaceId: "",
  schemaVersion: 1,
  folder: {
    name: "Kelly Agent Observability",
    description:
      "Agent Fleet Observability Desk: a generated-mock (never real) fleet of LLM agents behind a shared AI gateway for a generic organization — per-agent call volume/latency/error-rate/cost, hourly buckets, and trace-level chain-break detail. Agents and traces are seeded by a trusted script; the only human action, a handoff note (acknowledge / needs investigation) on an agent or trace, is appended to its own log. Generic and brand-free.",
    nodeId: "",
    slug: "kelly-agent-observability",
  },
  bases: [
    {
      key: "agents",
      name: "Agents",
      slug: "kelly-agent-observability-agents-v1",
      description:
        "One row per mock agent archetype (8 rows): identity plus the latest rolled-up health metrics (status, call volume, p50/p95 latency, error rate, cost) and a 48h hourly call/error series (JSON array). Written only by the trusted generator script; the AirApp never writes here.",
      nodeId: "",
      baseId: "",
      readLimit: 20,
      fields: [
        { slug: "agent-id", name: "Agent ID", type: "text", required: true },
        { slug: "name", name: "Name", type: "text", required: false },
        { slug: "description", name: "Description", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "calls-24h", name: "Calls (24h)", type: "number", required: false },
        { slug: "calls-48h", name: "Calls (48h)", type: "number", required: false },
        { slug: "error-rate-pct", name: "Error rate %", type: "number", required: false },
        { slug: "p50-latency-ms", name: "p50 latency (ms)", type: "number", required: false },
        { slug: "p95-latency-ms", name: "p95 latency (ms)", type: "number", required: false },
        { slug: "cost-per-call-usd", name: "Cost per call (USD)", type: "number", required: false },
        { slug: "cost-today-usd", name: "Cost today (USD)", type: "number", required: false },
        { slug: "cost-7d-usd", name: "Cost 7d (USD)", type: "number", required: false },
        { slug: "hourly", name: "Hourly buckets (JSON array)", type: "longtext", required: false },
      ],
    },
    {
      key: "traces",
      name: "Traces",
      slug: "kelly-agent-observability-traces-v1",
      description:
        "One row per mock trace (ordered tool-call chain) for one agent, capped to fit under the 100-record read limit. Steps (JSON array) carry the ordered timeline; broke-at-step-id flags exactly where a broken chain stopped. Written only by the trusted generator script.",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "trace-id", name: "Trace ID", type: "text", required: true },
        { slug: "agent-id", name: "Agent ID", type: "text", required: true },
        { slug: "started-at", name: "Started at", type: "text", required: false },
        { slug: "duration-ms", name: "Duration (ms)", type: "number", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "cost-usd", name: "Cost (USD)", type: "number", required: false },
        { slug: "broke-at-step-id", name: "Broke at step ID", type: "text", required: false },
        { slug: "steps", name: "Steps (JSON array)", type: "longtext", required: false },
      ],
    },
    {
      key: "handoffs",
      name: "Handoffs",
      slug: "kelly-agent-observability-handoffs-v1",
      description:
        "Append-only human-in-the-loop handoff log: an acknowledge / needs-investigation note recorded against one agent or trace. The only Base the AirApp itself ever writes to — always a new record, never an update to an agent/trace row.",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "handoff-id", name: "Handoff ID", type: "text", required: true },
        { slug: "target-type", name: "Target type", type: "text", required: false },
        { slug: "target-id", name: "Target ID", type: "text", required: false },
        { slug: "agent-id", name: "Agent ID", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "note", name: "Note", type: "longtext", required: false },
        { slug: "created-at", name: "Created at", type: "text", required: false },
        { slug: "created-by", name: "Created by", type: "text", required: false },
      ],
    },
    {
      key: "settings",
      name: "Settings",
      slug: "kelly-agent-observability-settings-v1",
      description: "Sanitized fleet-generation metadata (schema version, seed, generated-at), one row keyed by kind",
      nodeId: "",
      baseId: "",
      readLimit: 20,
      fields: [
        { slug: "record-id", name: "Record ID", type: "text", required: true },
        { slug: "kind", name: "Kind", type: "text", required: true },
        { slug: "payload", name: "Payload (JSON object)", type: "longtext", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
  ],
  permissions: {
    readProcedures: ["nodes.list", "nodes.get", "bases.get", "records.list"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata"],
    writeProcedures: ["records.changeRequest", "bases.createChangeRequest"],
  },
};
