export const appConfig = {
  appId: "kelly-ppt-factory",
  appName: "Kelly PPT Factory",
  deployment: "cloud",
  locale: "auto",
  readOnly: false,
  spaceId: "",
  schemaVersion: 1,
  folder: {
    name: "Kelly PPT Factory",
    description:
      "Project-based PPTX production desk — project, deck, slide card, style system, QA checks, and generated exports, with a review queue (approve / request changes / block / revise) gating PPTX generation",
    nodeId: "",
    slug: "kelly-ppt-factory",
  },
  bases: [
    {
      key: "projects",
      name: "Projects",
      slug: "kelly-ppt-factory-projects-v1",
      description: "A client / use-case / theme batch, e.g. Demo Studio / Pitch Deck / Seed Round",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "project-id", name: "Project ID", type: "text", required: true },
        { slug: "ref", name: "Ref", type: "text", required: false },
        { slug: "client-id", name: "Client ID", type: "text", required: false },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "course", name: "Use case", type: "text", required: false },
        { slug: "stage", name: "Stage", type: "text", required: false },
        { slug: "owner", name: "Owner", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "deck-count", name: "Deck count", type: "number", required: false },
        { slug: "slide-count", name: "Slide count", type: "number", required: false },
        { slug: "due-at", name: "Due at", type: "text", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
    {
      key: "decks",
      name: "Decks",
      slug: "kelly-ppt-factory-decks-v1",
      description: "One PPTX deliverable under a project — approval, style score, and output paths on the same row",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "deck-id", name: "Deck ID", type: "text", required: true },
        { slug: "ref", name: "Ref", type: "text", required: false },
        { slug: "project-id", name: "Project ID", type: "text", required: false },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "theme", name: "Theme", type: "text", required: false },
        { slug: "level", name: "Level", type: "text", required: false },
        { slug: "audience", name: "Audience", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "target-slide-count", name: "Target slide count", type: "number", required: false },
        { slug: "approved-slide-count", name: "Approved slide count", type: "number", required: false },
        { slug: "generated-slide-count", name: "Generated slide count", type: "number", required: false },
        { slug: "style-score", name: "Style score", type: "number", required: false },
        { slug: "pptx-path", name: "PPTX path", type: "text", required: false },
        { slug: "render-path", name: "Render path", type: "text", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
        { slug: "review-summary", name: "Review summary", type: "longtext", required: false },
        { slug: "review-suggestions", name: "Review suggestions (JSON array)", type: "longtext", required: false },
        { slug: "review-draft-note", name: "Review draft note", type: "longtext", required: false },
        { slug: "decision-action", name: "Decision action", type: "text", required: false },
        { slug: "decision-note", name: "Decision note", type: "longtext", required: false },
        { slug: "decided-at", name: "Decided at", type: "text", required: false },
        { slug: "execution-status", name: "Execution status", type: "text", required: false },
        { slug: "execution-operation", name: "Execution operation", type: "text", required: false },
        { slug: "execution-target", name: "Execution target", type: "text", required: false },
        { slug: "execution-detail", name: "Execution detail", type: "longtext", required: false },
        { slug: "executed-at", name: "Executed at", type: "text", required: false },
      ],
    },
    {
      key: "slideCards",
      name: "Slide Cards",
      slug: "kelly-ppt-factory-slide-cards-v1",
      description:
        "The storyboard unit for one PPTX page — objective, layout, structured content, asset brief, style/QA checks, and the review-queue decision on the same row",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "slide-id", name: "Slide ID", type: "text", required: true },
        { slug: "ref", name: "Ref", type: "text", required: false },
        { slug: "deck-id", name: "Deck ID", type: "text", required: false },
        { slug: "project-id", name: "Project ID", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "slide-type", name: "Slide type", type: "text", required: false },
        { slug: "layout", name: "Layout", type: "text", required: false },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "objective", name: "Objective", type: "longtext", required: false },
        { slug: "content-subtitle", name: "Content: subtitle", type: "text", required: false },
        { slug: "content-chinese", name: "Content: chinese", type: "text", required: false },
        { slug: "content-pinyin", name: "Content: pinyin", type: "text", required: false },
        { slug: "content-english", name: "Content: english", type: "text", required: false },
        { slug: "content-bullets", name: "Content: bullets (JSON array)", type: "longtext", required: false },
        { slug: "content-teacher-notes", name: "Content: presenter notes", type: "longtext", required: false },
        { slug: "content-interaction", name: "Content: interaction", type: "longtext", required: false },
        { slug: "content-image-prompt", name: "Content: image prompt", type: "longtext", required: false },
        { slug: "asset-brief", name: "Asset brief", type: "longtext", required: false },
        { slug: "style-checks", name: "Style checks (JSON array)", type: "longtext", required: false },
        { slug: "qa-flags", name: "QA flags (JSON array)", type: "longtext", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
        { slug: "review-summary", name: "Review summary", type: "longtext", required: false },
        { slug: "review-suggestions", name: "Review suggestions (JSON array)", type: "longtext", required: false },
        { slug: "review-draft-note", name: "Review draft note", type: "longtext", required: false },
        { slug: "decision-action", name: "Decision action", type: "text", required: false },
        { slug: "decision-note", name: "Decision note", type: "longtext", required: false },
        { slug: "decided-at", name: "Decided at", type: "text", required: false },
        { slug: "execution-status", name: "Execution status", type: "text", required: false },
        { slug: "execution-operation", name: "Execution operation", type: "text", required: false },
        { slug: "execution-target", name: "Execution target", type: "text", required: false },
        { slug: "execution-detail", name: "Execution detail", type: "longtext", required: false },
        { slug: "executed-at", name: "Executed at", type: "text", required: false },
      ],
    },
    {
      key: "styleSystems",
      name: "Style Systems",
      slug: "kelly-ppt-factory-style-systems-v1",
      description: "Reusable presentation style kits — palette, fonts, visual/layout rules, and component library",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "style-system-id", name: "Style system ID", type: "text", required: true },
        { slug: "name", name: "Name", type: "text", required: false },
        { slug: "palette", name: "Palette (JSON array)", type: "longtext", required: false },
        { slug: "font-heading", name: "Font: heading", type: "text", required: false },
        { slug: "font-body", name: "Font: body", type: "text", required: false },
        { slug: "font-chinese", name: "Font: chinese", type: "text", required: false },
        { slug: "visual-rules", name: "Visual rules (JSON array)", type: "longtext", required: false },
        { slug: "layout-rules", name: "Layout rules (JSON array)", type: "longtext", required: false },
        { slug: "component-library", name: "Component library (JSON array)", type: "longtext", required: false },
      ],
    },
    {
      key: "qaChecks",
      name: "QA Checks",
      slug: "kelly-ppt-factory-qa-checks-v1",
      description: "Deterministic or human QA evidence for a deck, slide, or export",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "check-id", name: "Check ID", type: "text", required: true },
        { slug: "target-id", name: "Target ID", type: "text", required: false },
        { slug: "target-type", name: "Target type", type: "text", required: false },
        { slug: "rule", name: "Rule", type: "text", required: false },
        { slug: "result", name: "Result", type: "text", required: false },
        { slug: "evidence", name: "Evidence", type: "longtext", required: false },
        { slug: "checked-at", name: "Checked at", type: "text", required: false },
      ],
    },
    {
      key: "exports",
      name: "Exports",
      slug: "kelly-ppt-factory-exports-v1",
      description: "Generated PPTX output records — path, render path, generation status, and QA summary",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "export-id", name: "Export ID", type: "text", required: true },
        { slug: "deck-id", name: "Deck ID", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "format", name: "Format", type: "text", required: false },
        { slug: "path", name: "Path", type: "text", required: false },
        { slug: "generated-at", name: "Generated at", type: "text", required: false },
        { slug: "qa-summary", name: "QA summary", type: "longtext", required: false },
      ],
    },
    {
      key: "settings",
      name: "Settings",
      slug: "kelly-ppt-factory-settings-v1",
      description: "Default client profile, style default, and export preferences — a single settings row",
      nodeId: "",
      baseId: "",
      readLimit: 20,
      fields: [
        { slug: "record-id", name: "Record ID", type: "text", required: true },
        { slug: "default-brand-id", name: "Default brand ID", type: "text", required: false },
        { slug: "brand-name", name: "Brand name", type: "text", required: false },
        { slug: "brand-audience", name: "Brand audience", type: "text", required: false },
        { slug: "brand-language-mode", name: "Brand language mode", type: "text", required: false },
        { slug: "brand-style-system-id", name: "Brand default style system ID", type: "text", required: false },
        { slug: "export-out-dir", name: "Export out dir", type: "text", required: false },
        { slug: "export-render-dir", name: "Export render dir", type: "text", required: false },
        { slug: "export-pptx-template", name: "Export PPTX template", type: "text", required: false },
        { slug: "export-require-render-qa", name: "Export require render QA", type: "text", required: false },
      ],
    },
  ],
  permissions: {
    readProcedures: ["nodes.list", "nodes.get", "bases.get", "records.list"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata"],
    writeProcedures: ["records.changeRequest", "bases.createChangeRequest"],
  },
};
