export const appConfig = {
  appId: "kelly-invest-stock",
  appName: "Kelly Invest Stock",
  deployment: "cloud",
  locale: "zh-CN",
  readOnly: false,
  spaceId: "",
  schemaVersion: 4,
  folder: {
    name: "Kelly Invest Stock",
    description: "Strategy screening and virtual ledger workspace",
    nodeId: "nodms6x55yvfgahybw",
    slug: "kelly-invest-stock",
  },
  bases: [
    {
      key: "strategies",
      name: "策略",
      slug: "stock-strategies-v2",
      description: "Selection rules, thesis, invalidation, and benchmark for each strategy",
      nodeId: "nodms6x55zik8prn1g",
      baseId: "bsems6x55ziqucmuwb",
      readLimit: 20,
      fields: [
        { slug: "name", name: "策略名称", type: "text", required: true },
        { slug: "key", name: "策略标识", type: "text", required: true },
        { slug: "family", name: "策略族", type: "text", required: false },
        { slug: "status", name: "状态", type: "text", required: false },
        { slug: "thesis", name: "核心假设", type: "longtext", required: false },
        { slug: "selection-rule", name: "选股规则", type: "longtext", required: false },
        { slug: "invalidation-rule", name: "失效条件", type: "longtext", required: false },
        { slug: "rebalance", name: "复核频率", type: "text", required: false },
        { slug: "benchmark", name: "基准", type: "text", required: false },
        { slug: "confidence", name: "策略置信度", type: "number", required: false },
        { slug: "next-review-at", name: "下次复核时间", type: "text", required: false },
      ],
    },
    {
      key: "ledger-accounts",
      name: "虚拟账户",
      slug: "stock-ledger-accounts-v2",
      description: "One virtual capital account per strategy",
      nodeId: "nodms6x560pw3mhtdk",
      baseId: "bsems6x560pxd42tx6",
      readLimit: 20,
      fields: [
        { slug: "name", name: "账户名称", type: "text", required: true },
        { slug: "strategy-key", name: "策略标识", type: "text", required: true },
        { slug: "nominal-capital", name: "名义本金", type: "number", required: true },
        { slug: "nav", name: "净值", type: "number", required: true },
        { slug: "cash", name: "现金", type: "number", required: false },
        { slug: "benchmark-return", name: "基准收益", type: "number", required: false },
        { slug: "max-drawdown", name: "最大回撤", type: "number", required: false },
        { slug: "updated-at", name: "更新时间", type: "text", required: false },
        { slug: "baseline-date", name: "收益起算日", type: "text", required: false },
      ],
    },
    {
      key: "ledger-positions",
      name: "虚拟持仓",
      slug: "stock-ledger-positions-v2",
      description: "Virtual positions used to validate strategy behavior",
      nodeId: "nodms6x5619db2pux3",
      baseId: "bsems6x5619srj0ffu",
      readLimit: 100,
      fields: [
        { slug: "name", name: "证券名称", type: "text", required: true },
        { slug: "strategy-key", name: "策略标识", type: "text", required: true },
        { slug: "code", name: "证券代码", type: "text", required: true },
        { slug: "quantity", name: "虚拟数量", type: "number", required: true },
        { slug: "entry-price", name: "虚拟成本", type: "number", required: true },
        { slug: "latest-price", name: "参考价", type: "number", required: false },
        { slug: "market-value", name: "虚拟市值", type: "number", required: false },
        { slug: "weight", name: "账户权重", type: "number", required: false },
        { slug: "price-source", name: "参考价来源", type: "text", required: false },
        { slug: "price-as-of", name: "参考价时间", type: "text", required: false },
      ],
    },
    {
      key: "strategy-backtests",
      name: "策略回测报告",
      slug: "stock-strategy-backtests-v3",
      description: "Dated backtest results and methodology by strategy",
      nodeId: "nodmsfua9rz99mk2pt",
      baseId: "bsemsfua9rzgkknt11",
      readLimit: 100,
      fields: [
        { slug: "name", name: "报告名称", type: "text", required: true },
        { slug: "strategy-key", name: "策略标识", type: "text", required: true },
        { slug: "report-date", name: "报告日期", type: "text", required: true },
        { slug: "window-start", name: "回测起点", type: "text", required: true },
        { slug: "window-end", name: "回测截止", type: "text", required: true },
        { slug: "window-label", name: "回测窗口", type: "text", required: false },
        { slug: "method", name: "回测方法", type: "text", required: true },
        { slug: "coverage", name: "数据覆盖", type: "text", required: false },
        { slug: "benchmark", name: "比较基准", type: "text", required: false },
        { slug: "total-return", name: "总回报", type: "number", required: false },
        { slug: "cagr", name: "年化收益", type: "number", required: false },
        { slug: "volatility", name: "年化波动", type: "number", required: false },
        { slug: "sharpe", name: "Sharpe", type: "number", required: false },
        { slug: "max-drawdown", name: "最大回撤", type: "number", required: false },
        { slug: "benchmark-return", name: "基准总回报", type: "number", required: false },
        { slug: "excess-return", name: "相对基准", type: "number", required: false },
        { slug: "source-note", name: "口径与偏差", type: "longtext", required: false },
      ],
    },
    {
      key: "strategy-reviews",
      name: "策略研究与审批",
      slug: "stock-strategy-reviews-v1",
      description: "Dated research evidence, account snapshots, and manual maturity decisions",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "name", name: "记录名称", type: "text", required: true },
        { slug: "strategy-key", name: "策略标识", type: "text", required: true },
        { slug: "review-date", name: "记录时间", type: "text", required: true },
        { slug: "review-type", name: "记录类型", type: "text", required: true },
        { slug: "source-note", name: "来源说明", type: "longtext", required: false },
        { slug: "source-as-of", name: "来源时间", type: "text", required: false },
        { slug: "supporting-evidence", name: "支持证据", type: "longtext", required: false },
        { slug: "counter-evidence", name: "反方证据", type: "longtext", required: false },
        { slug: "data-freshness", name: "数据新鲜度", type: "text", required: false },
        { slug: "snapshot-nav", name: "复查净值", type: "number", required: false },
        { slug: "snapshot-benchmark-return", name: "复查基准收益", type: "number", required: false },
        { slug: "snapshot-max-drawdown", name: "复查最大回撤", type: "number", required: false },
        { slug: "from-stage", name: "原阶段", type: "text", required: false },
        { slug: "to-stage", name: "目标阶段", type: "text", required: false },
        { slug: "decision", name: "人工决定", type: "text", required: false },
        { slug: "reason", name: "人工理由", type: "longtext", required: false },
        { slug: "reviewer", name: "审批人", type: "text", required: false },
        { slug: "change-request-id", name: "变更请求", type: "text", required: false },
      ],
    },
  ],
  permissions: {
    readProcedures: ["nodes.list", "nodes.get", "bases.get", "records.list"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata", "bases.fieldChangeRequest"],
    writeProcedures: ["records.changeRequest", "bases.createChangeRequest", "bases.createBulkChangeRequest"],
  },
};
