export const appConfig = {
  appId: "kelly-invest-stock",
  appName: "Kelly Invest Stock",
  deployment: "cloud",
  locale: "zh-CN",
  readOnly: true,
  spaceId: "",
  schemaVersion: 2,
  folder: {
    name: "Kelly Invest Stock",
    description: "Strategy screening and virtual ledger workspace",
    nodeId: "nodms6x55yvfgahybw",
    slug: "kelly-invest-stock",
  },
  bases: [
    {
      key: "strategies",
      name: "策略",
      slug: "stock-strategies-v2",
      description: "Selection rules, thesis, invalidation, and benchmark for each strategy",
      nodeId: "nodms6x55zik8prn1g",
      baseId: "bsems6x55ziqucmuwb",
      readLimit: 20,
      fields: [
        { slug: "name", name: "策略名称", type: "text", required: true },
        { slug: "key", name: "策略标识", type: "text", required: true },
        { slug: "family", name: "策略族", type: "text", required: false },
        { slug: "status", name: "状态", type: "text", required: false },
        { slug: "thesis", name: "核心假设", type: "longtext", required: false },
        { slug: "selection-rule", name: "选股规则", type: "longtext", required: false },
        { slug: "invalidation-rule", name: "失效条件", type: "longtext", required: false },
        { slug: "rebalance", name: "复核频率", type: "text", required: false },
        { slug: "benchmark", name: "基准", type: "text", required: false },
        { slug: "confidence", name: "策略置信度", type: "number", required: false },
      ],
    },
    {
      key: "candidates",
      name: "候选股",
      slug: "stock-candidates-v2",
      description: "L1, L2, and L3 candidates with evidence and graduation state",
      nodeId: "nodms6x560633vozfc",
      baseId: "bsems6x5606qe567ax",
      readLimit: 100,
      fields: [
        { slug: "name", name: "证券名称", type: "text", required: true },
        { slug: "code", name: "证券代码", type: "text", required: true },
        { slug: "exchange", name: "交易所", type: "text", required: true },
        { slug: "strategy-key", name: "所属策略", type: "text", required: true },
        { slug: "stage", name: "分层", type: "text", required: true },
        { slug: "confidence", name: "综合分", type: "number", required: false },
        { slug: "value-score", name: "估值分", type: "number", required: false },
        { slug: "quality-score", name: "质量分", type: "number", required: false },
        { slug: "catalyst-score", name: "催化分", type: "number", required: false },
        { slug: "latest-price", name: "参考价", type: "number", required: false },
        { slug: "daily-change", name: "当日变化", type: "number", required: false },
        { slug: "thesis", name: "入选理由", type: "longtext", required: false },
        { slug: "evidence", name: "关键证据", type: "longtext", required: false },
        { slug: "invalidation", name: "失效条件", type: "longtext", required: false },
        { slug: "next-review", name: "下次复核", type: "date", required: false },
        { slug: "freshness-status", name: "数据状态", type: "text", required: false },
      ],
    },
    {
      key: "ledger-accounts",
      name: "虚拟账户",
      slug: "stock-ledger-accounts-v2",
      description: "One virtual capital account per strategy",
      nodeId: "nodms6x560pw3mhtdk",
      baseId: "bsems6x560pxd42tx6",
      readLimit: 20,
      fields: [
        { slug: "name", name: "账户名称", type: "text", required: true },
        { slug: "strategy-key", name: "策略标识", type: "text", required: true },
        { slug: "nominal-capital", name: "名义本金", type: "number", required: true },
        { slug: "nav", name: "净值", type: "number", required: true },
        { slug: "cash", name: "现金", type: "number", required: false },
        { slug: "benchmark-return", name: "基准收益", type: "number", required: false },
        { slug: "max-drawdown", name: "最大回撤", type: "number", required: false },
        { slug: "updated-at", name: "更新时间", type: "text", required: false },
      ],
    },
    {
      key: "ledger-positions",
      name: "虚拟持仓",
      slug: "stock-ledger-positions-v2",
      description: "Virtual positions used to validate strategy behavior",
      nodeId: "nodms6x5619db2pux3",
      baseId: "bsems6x5619srj0ffu",
      readLimit: 100,
      fields: [
        { slug: "name", name: "证券名称", type: "text", required: true },
        { slug: "strategy-key", name: "策略标识", type: "text", required: true },
        { slug: "code", name: "证券代码", type: "text", required: true },
        { slug: "quantity", name: "虚拟数量", type: "number", required: true },
        { slug: "entry-price", name: "虚拟成本", type: "number", required: true },
        { slug: "latest-price", name: "参考价", type: "number", required: false },
        { slug: "market-value", name: "虚拟市值", type: "number", required: false },
        { slug: "weight", name: "账户权重", type: "number", required: false },
      ],
    },
  ],
  permissions: {
    readProcedures: ["nodes.list", "nodes.get", "bases.get", "records.list"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata"],
    writeProcedures: [],
  },
};
