export const appConfig = {
  appId: "kelly-brand",
  appName: "Kelly Brand",
  deployment: "cloud",
  locale: "auto",
  readOnly: false,
  spaceId: "",
  schemaVersion: 1,
  folder: {
    name: "Kelly Brand",
    description: "Brand-narrative single source of truth built on the TALE discipline",
    slug: "kelly-brand",
  },
  airApp: { name: "Kelly Brand", slug: "kelly-brand-app", resourceKey: "kelly-brand-app" },
  bases: [
    {
      key: "items",
      name: "Narrative Items",
      slug: "kelly-brand-items",
      description: "Positioning, message pillars, story bank, proof points, vocabulary and guardrails under review",
      readLimit: 100,
      fields: [
        { slug: "item-id", name: "Item ID", type: "text", required: true },
        { slug: "ref", name: "Ref", type: "number", required: false },
        { slug: "type", name: "Type", type: "text", required: false },
        { slug: "phase", name: "Phase", type: "text", required: false },
        { slug: "sub-skill", name: "Sub-skill", type: "text", required: false },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "draft", name: "Draft", type: "longtext", required: false },
        { slug: "reason", name: "Reason", type: "longtext", required: false },
        { slug: "nqs-score", name: "NQS score", type: "number", required: false },
        { slug: "nqs-gate", name: "NQS gate", type: "text", required: false },
        { slug: "evidence-source", name: "Evidence source", type: "text", required: false },
        { slug: "evidence-stat", name: "Evidence stat", type: "text", required: false },
        { slug: "evidence-url", name: "Evidence URL", type: "text", required: false },
        { slug: "risk", name: "Risk", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "created-at", name: "Created at", type: "text", required: false },
        { slug: "decision-note", name: "Decision note", type: "longtext", required: false },
        { slug: "decided-at", name: "Decided at", type: "text", required: false },
      ],
    },
    {
      key: "drift-alerts",
      name: "Drift Alerts",
      slug: "kelly-brand-drift-alerts",
      description: "Cross-channel off-brand usage flagged by the narrative-drift-monitor",
      readLimit: 50,
      fields: [
        { slug: "alert-id", name: "Alert ID", type: "text", required: true },
        { slug: "channel-id", name: "Channel", type: "text", required: false },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "offending-usage", name: "Offending usage", type: "longtext", required: false },
        { slug: "guardrail-item-id", name: "Guardrail item ID", type: "text", required: false },
        { slug: "canonical-guidance", name: "Canonical guidance", type: "longtext", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "severity", name: "Severity", type: "text", required: false },
        { slug: "detected-at", name: "Detected at", type: "text", required: false },
        { slug: "decision-note", name: "Decision note", type: "longtext", required: false },
        { slug: "decided-at", name: "Decided at", type: "text", required: false },
      ],
    },
    {
      key: "settings",
      name: "Settings",
      slug: "kelly-brand-settings",
      description: "Brand profile, style/tone, risk policy, monitored channels, and the agent lock",
      readLimit: 20,
      fields: [
        { slug: "record-id", name: "Record ID", type: "text", required: true },
        { slug: "kind", name: "Kind", type: "text", required: true },
        { slug: "name", name: "Name", type: "text", required: false },
        { slug: "payload", name: "Payload", type: "longtext", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
  ],
  permissions: {
    readProcedures: ["nodes.list", "nodes.get", "bases.get", "records.list"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata"],
    writeProcedures: ["records.changeRequest", "bases.createChangeRequest"],
  },
};
