#!/usr/bin/env node
// Writes a small deterministic sample snapshot to app/.data/ so the app has
// something to render before real feedback is ingested. This is NOT the demo
// mode dataset (that lives in app/server/demo.mjs and never touches .data).
import { recomputeDerived, writeJson } from "../lib/common.ts";
import { SNAPSHOT_PATH } from "../lib/paths.ts";
import type { FeedbackSnapshot } from "../lib/types.ts";

const now = new Date().toISOString();

const snapshot = {
  schema_version: "1",
  generated_at: now,
  source: "kelly-feedback-sample",
  products: [{ product_id: "example-app", display_name: "Example App", tagline: "Sample product" }],
  sources: [
    {
      source_id: "support-email",
      channel: "email",
      name: "Support inbox",
      collection: "kelly-email handoff",
      last_ingest_at: now,
      item_count: 2,
      status: "ok",
    },
    {
      source_id: "discord-community",
      channel: "discord",
      name: "Discord #feedback",
      collection: "kelly-messenger handoff",
      last_ingest_at: now,
      item_count: 1,
      status: "ok",
    },
  ],
  feedback: [
    {
      feedback_id: "fb-support-email-demo-1",
      source_id: "support-email",
      channel: "email",
      product: "example-app",
      user: { handle: "customer@example.com", plan: "pro", tenure_months: 6, weight: 3 },
      text: "Could you add a CSV export for the reports page? We rebuild it by hand every week.",
      sentiment: "neutral",
      received_at: now,
      permalink: "",
      request_id: "req-sample-export",
      triage: "clustered",
      agent_note: "",
    },
    {
      feedback_id: "fb-support-email-demo-2",
      source_id: "support-email",
      channel: "email",
      product: "example-app",
      user: { handle: "founder@example.org", plan: "team", tenure_months: 12, weight: 5 },
      text: "Export to CSV please — screenshots do not work for our auditors.",
      sentiment: "negative",
      received_at: now,
      permalink: "",
      request_id: "req-sample-export",
      triage: "clustered",
      agent_note: "",
    },
    {
      feedback_id: "fb-discord-community-demo-3",
      source_id: "discord-community",
      channel: "discord",
      product: "example-app",
      user: { handle: "@nightbuilder", plan: "free", tenure_months: 2, weight: 1 },
      text: "any chance of a dark mode?",
      sentiment: "neutral",
      received_at: now,
      permalink: "",
      request_id: "",
      triage: "new",
      agent_note: "",
    },
  ],
  requests: [
    {
      request_id: "req-sample-export",
      title: "CSV export for reports",
      product: "example-app",
      status: "candidate",
      trend: "up",
      frequency: 0,
      weighted_score: 0,
      problem_statement: "Users cannot get raw report data out; finance workflows are blocked.",
      spec_summary: "Add an Export CSV action to the reports page mirroring the on-screen table.",
      effort_estimate: "M (1-2 weeks)",
      representative_feedback_ids: ["fb-support-email-demo-1"],
      decision_history: [{ at: now, actor: "agent", action: "created", note: "Sample cluster." }],
      created_at: now,
      updated_at: now,
    },
  ],
  roadmap: {
    now: [{ item_id: "rm-now-sample", title: "Performance pass", request_id: "", note: "Sample roadmap item." }],
    next: [],
    later: [],
  },
  proposals: [
    {
      proposal_id: "prop-sample-export",
      ref: 1,
      type: "promote_request",
      title: "Promote 'CSV export for reports' to Next",
      status: "needs_review",
      request_id: "req-sample-export",
      request_ids: [],
      target_lane: "next",
      reason: "Two paid accounts blocked on reporting; highest weighted cluster in the sample.",
      evidence: "2 email feedback items, both from paying plans.",
      draft_kind: "changelog_note",
      draft: "Next up: CSV export for reports. Get the raw numbers behind every report.",
      review_note: "",
      created_at: now,
      decided_at: "",
    },
  ],
  metrics: {},
  sync_log: [
    {
      at: now,
      actor: "kelly-feedback",
      action: "ingest",
      detail: "Sample snapshot generated by scripts/generate_demo_snapshot.mjs.",
      count: 3,
    },
  ],
};

recomputeDerived(snapshot as unknown as FeedbackSnapshot);
await writeJson(SNAPSHOT_PATH, snapshot);
console.log(`Wrote ${SNAPSHOT_PATH}`);
