export const appConfig = {
  appId: "kelly-creators",
  appName: "Kelly Creators",
  deployment: "cloud",
  locale: "auto",
  readOnly: false,
  spaceId: "",
  schemaVersion: 1,
  folder: {
    name: "Kelly Creators",
    description: "Influencer/creator marketing command desk — discovery, outreach, briefs, contracts, and ROI",
    slug: "kelly-creators",
  },
  airApp: { name: "Kelly Creators", slug: "kelly-creators-app", resourceKey: "kelly-creators-app" },
  bases: [
    {
      key: "creators",
      name: "Creator Engagements",
      slug: "kelly-creators-creators",
      description:
        "Creator candidates and engagements (fit score, outreach drafts, briefs, contracts) plus pre-publication content-review quality gates, under human review",
      readLimit: 100,
      fields: [
        { slug: "creator-id", name: "Creator ID", type: "text", required: true },
        { slug: "ref", name: "Ref", type: "number", required: false },
        { slug: "item-type", name: "Item type", type: "text", required: false },
        { slug: "handle", name: "Handle", type: "text", required: false },
        { slug: "name", name: "Name", type: "text", required: false },
        { slug: "platform", name: "Platform", type: "text", required: false },
        { slug: "niche", name: "Niche", type: "text", required: false },
        { slug: "followers", name: "Followers", type: "number", required: false },
        { slug: "engagement-rate", name: "Engagement rate", type: "number", required: false },
        { slug: "fit-score", name: "Fit score", type: "number", required: false },
        { slug: "fit-breakdown", name: "Fit breakdown", type: "longtext", required: false },
        { slug: "stage", name: "Stage", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "proposed-action", name: "Proposed action", type: "text", required: false },
        { slug: "est-rate", name: "Est. rate", type: "number", required: false },
        { slug: "risk", name: "Risk", type: "text", required: false },
        { slug: "channel", name: "Channel", type: "text", required: false },
        { slug: "reason", name: "Reason", type: "longtext", required: false },
        { slug: "audience-note", name: "Audience note", type: "longtext", required: false },
        { slug: "suggested-reply", name: "Suggested reply", type: "longtext", required: false },
        { slug: "est-value", name: "Est. value", type: "number", required: false },
        { slug: "spend", name: "Spend", type: "number", required: false },
        { slug: "gate-verdict", name: "Gate verdict", type: "text", required: false },
        { slug: "gate-checks", name: "Gate checks", type: "longtext", required: false },
        { slug: "created-at", name: "Created at", type: "text", required: false },
        { slug: "decision-note", name: "Decision note", type: "longtext", required: false },
        { slug: "decided-at", name: "Decided at", type: "text", required: false },
      ],
    },
    {
      key: "settings",
      name: "Settings",
      slug: "kelly-creators-settings",
      description: "Operator profile, brand(s), program budget, platforms, and the agent lock",
      readLimit: 20,
      fields: [
        { slug: "record-id", name: "Record ID", type: "text", required: true },
        { slug: "kind", name: "Kind", type: "text", required: true },
        { slug: "name", name: "Name", type: "text", required: false },
        { slug: "payload", name: "Payload", type: "longtext", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
  ],
  permissions: {
    readProcedures: ["nodes.list", "nodes.get", "bases.get", "records.list"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata"],
    writeProcedures: ["records.changeRequest", "bases.createChangeRequest"],
  },
};
