export const appConfig = {
  appId: "kelly-products",
  appName: "Kelly Products",
  deployment: "cloud",
  locale: "auto",
  readOnly: false,
  spaceId: "",
  schemaVersion: 1,
  folder: {
    name: "Kelly Products",
    description:
      "E-commerce product-management desk: catalog/SKU master data, pricing, inventory, channel status (Amazon/Shopify/TikTok Shop/eBay), content readiness, compliance notes, lifecycle state, and an approval-gated review queue (channel publish approvals, price-change review, quality holds, lifecycle decisions). Products, channel rows, inventory rows, and review items enter Busabase only through the agent's own ingest workflow (see SKILL.md); the AirApp itself only ever decides on a review item (approve/request_changes/block) directly onto its own record -- it never creates a product, channel row, or inventory row.",
    slug: "kelly-products",
  },
  airApp: { name: "Kelly Products", slug: "kelly-products-app", resourceKey: "kelly-products-app" },
  bases: [
    {
      key: "products",
      name: "Products",
      slug: "kelly-products-products",
      description:
        "One row per product/SKU: catalog identity, lifecycle/status, owner, vendor, launch date, image + gallery, tags, and JSON-encoded pricing/inventory-rollup/content/compliance blocks. Created and updated only by the agent's ingest workflow.",
      readLimit: 100,
      fields: [
        { slug: "product-id", name: "Product ID", type: "text", required: true },
        { slug: "ref", name: "Ref", type: "number", required: false },
        { slug: "sku", name: "SKU", type: "text", required: false },
        { slug: "name", name: "Name", type: "text", required: false },
        { slug: "subtitle", name: "Subtitle", type: "text", required: false },
        { slug: "category", name: "Category", type: "text", required: false },
        { slug: "lifecycle", name: "Lifecycle", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "owner", name: "Owner", type: "text", required: false },
        { slug: "vendor", name: "Vendor", type: "text", required: false },
        { slug: "launch-date", name: "Launch date", type: "text", required: false },
        { slug: "image", name: "Image URL", type: "text", required: false },
        { slug: "gallery", name: "Gallery (JSON array)", type: "longtext", required: false },
        { slug: "tags", name: "Tags (JSON array)", type: "longtext", required: false },
        { slug: "pricing", name: "Pricing (JSON object)", type: "longtext", required: false },
        { slug: "inventory", name: "Inventory rollup (JSON object)", type: "longtext", required: false },
        { slug: "content", name: "Content readiness (JSON object)", type: "longtext", required: false },
        { slug: "compliance", name: "Compliance (JSON object)", type: "longtext", required: false },
        { slug: "created-at", name: "Created at", type: "text", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
    {
      key: "channels",
      name: "Channels",
      slug: "kelly-products-channels",
      description:
        "One row per product x marketplace channel (Amazon/Shopify/TikTok Shop/eBay): listing id, status, price, buybox, content score, and channel issue note. Created and updated only by the agent's ingest workflow.",
      readLimit: 100,
      fields: [
        { slug: "channel-id", name: "Channel ID", type: "text", required: true },
        { slug: "product-id", name: "Product ID", type: "text", required: false },
        { slug: "platform", name: "Platform", type: "text", required: false },
        { slug: "listing-id", name: "Listing ID", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "price", name: "Price", type: "number", required: false },
        { slug: "buybox", name: "Buybox", type: "text", required: false },
        { slug: "content-score", name: "Content score", type: "number", required: false },
        { slug: "issue", name: "Channel issue", type: "longtext", required: false },
        { slug: "next-step", name: "Next step", type: "text", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
    {
      key: "inventory",
      name: "Inventory",
      slug: "kelly-products-inventory",
      description:
        "One row per product x warehouse: on-hand/available/reserved/inbound units, inbound ETA, days of cover, and stock-risk status. Created and updated only by the agent's ingest workflow.",
      readLimit: 100,
      fields: [
        { slug: "inventory-id", name: "Inventory ID", type: "text", required: true },
        { slug: "product-id", name: "Product ID", type: "text", required: false },
        { slug: "warehouse-id", name: "Warehouse ID", type: "text", required: false },
        { slug: "warehouse-name", name: "Warehouse name", type: "text", required: false },
        { slug: "on-hand", name: "On hand", type: "number", required: false },
        { slug: "available", name: "Available", type: "number", required: false },
        { slug: "reserved", name: "Reserved", type: "number", required: false },
        { slug: "inbound", name: "Inbound", type: "number", required: false },
        { slug: "inbound-eta", name: "Inbound ETA", type: "text", required: false },
        { slug: "days-cover", name: "Days cover", type: "number", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
    {
      key: "review",
      name: "Review",
      slug: "kelly-products-review",
      description:
        "Approval-gated review queue: channel publish approvals, price-change review, quality holds, and lifecycle/archive decisions, linked to a product. The operator's decision (approve/request_changes/block) is written directly onto this row -- there is no separate decisions.json-equivalent bucket. Execution fields record the agent's follow-up outside the app after approval.",
      readLimit: 100,
      fields: [
        { slug: "item-id", name: "Item ID", type: "text", required: true },
        { slug: "ref", name: "Ref", type: "number", required: false },
        { slug: "product-id", name: "Product ID", type: "text", required: false },
        { slug: "type", name: "Type", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "summary", name: "Summary", type: "longtext", required: false },
        { slug: "risk", name: "Risk", type: "text", required: false },
        { slug: "recommendation", name: "Recommendation", type: "text", required: false },
        { slug: "evidence", name: "Evidence (JSON array)", type: "longtext", required: false },
        { slug: "decision-note", name: "Decision note", type: "longtext", required: false },
        { slug: "decided-at", name: "Decided at", type: "text", required: false },
        { slug: "execution-status", name: "Execution status", type: "text", required: false },
        { slug: "execution-detail", name: "Execution detail", type: "longtext", required: false },
        { slug: "executed-at", name: "Executed at", type: "text", required: false },
        { slug: "created-at", name: "Created at", type: "text", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
    {
      key: "settings",
      name: "Settings",
      slug: "kelly-products-settings",
      description: "Seller profile, platform connectors, warehouses, and review policy -- a single settings row",
      readLimit: 20,
      fields: [
        { slug: "record-id", name: "Record ID", type: "text", required: true },
        { slug: "seller-brand", name: "Brand", type: "text", required: false },
        { slug: "seller-entity", name: "Entity", type: "text", required: false },
        { slug: "base-currency", name: "Base currency", type: "text", required: false },
        { slug: "platforms", name: "Platforms (JSON array)", type: "longtext", required: false },
        { slug: "warehouses", name: "Warehouses (JSON array)", type: "longtext", required: false },
        { slug: "review-policy", name: "Review policy (JSON object)", type: "longtext", required: false },
        { slug: "sync", name: "Sync (JSON object)", type: "longtext", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
  ],
  permissions: {
    readProcedures: ["nodes.list", "nodes.get", "bases.get", "records.list"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata"],
    // The browser only ever decides on a review item (records.changeRequest);
    // it never creates a product/channel/inventory row (those enter through
    // scripts/ingest_products.mjs, a trusted skill-root script using its own
    // Busabase credentials -- see that script and busabase-provider.js's
    // comments). bases.createChangeRequest is unused from the browser but
    // kept in the allow-list for symmetry with the ingest script's own
    // upserts, which reuse the same field-encoding helpers.
    writeProcedures: ["records.changeRequest", "bases.createChangeRequest"],
  },
};
