export const appConfig = {
  appId: "kelly-audit",
  appName: "Kelly Audit",
  deployment: "cloud",
  locale: "auto",
  readOnly: false,
  spaceId: "",
  schemaVersion: 1,
  folder: {
    name: "Kelly Audit",
    description:
      "Finance anomaly review desk: imported orders/invoices/payments, deterministic anomaly rules, and a human review queue",
    slug: "kelly-audit",
  },
  airApp: { name: "Kelly Audit", slug: "kelly-audit-app", resourceKey: "kelly-audit-app" },
  bases: [
    {
      key: "orders",
      name: "Orders",
      slug: "kelly-audit-orders",
      description: "Normalized sales orders imported from CSV/JSON exports",
      readLimit: 100,
      fields: [
        { slug: "order-id", name: "Order ID", type: "text", required: true },
        { slug: "order-no", name: "Order no", type: "text", required: false },
        { slug: "customer", name: "Customer", type: "text", required: false },
        { slug: "order-date", name: "Order date", type: "text", required: false },
        { slug: "amount", name: "Amount", type: "number", required: false },
        { slug: "currency", name: "Currency", type: "text", required: false },
        { slug: "source-file", name: "Source file", type: "text", required: false },
      ],
    },
    {
      key: "invoices",
      name: "Invoices",
      slug: "kelly-audit-invoices",
      description: "Normalized invoices and credit notes imported from CSV/JSON exports",
      readLimit: 100,
      fields: [
        { slug: "invoice-id", name: "Invoice ID", type: "text", required: true },
        { slug: "invoice-no", name: "Invoice no", type: "text", required: false },
        { slug: "order-no", name: "Order no", type: "text", required: false },
        { slug: "customer", name: "Customer", type: "text", required: false },
        { slug: "issue-date", name: "Issue date", type: "text", required: false },
        { slug: "due-date", name: "Due date", type: "text", required: false },
        { slug: "amount", name: "Amount", type: "number", required: false },
        { slug: "currency", name: "Currency", type: "text", required: false },
        { slug: "kind", name: "Kind", type: "text", required: false },
        { slug: "notes", name: "Notes", type: "longtext", required: false },
        { slug: "source-file", name: "Source file", type: "text", required: false },
      ],
    },
    {
      key: "payments",
      name: "Payments",
      slug: "kelly-audit-payments",
      description: "Normalized payments / receipts (回款) imported from CSV/JSON exports",
      readLimit: 100,
      fields: [
        { slug: "payment-id", name: "Payment ID", type: "text", required: true },
        { slug: "payment-ref", name: "Payment ref", type: "text", required: false },
        { slug: "invoice-no", name: "Invoice no", type: "text", required: false },
        { slug: "order-no", name: "Order no", type: "text", required: false },
        { slug: "payer", name: "Payer", type: "text", required: false },
        { slug: "paid-date", name: "Paid date", type: "text", required: false },
        { slug: "amount", name: "Amount", type: "number", required: false },
        { slug: "currency", name: "Currency", type: "text", required: false },
        { slug: "method", name: "Method", type: "text", required: false },
        { slug: "source-file", name: "Source file", type: "text", required: false },
      ],
    },
    {
      key: "anomalies",
      name: "Anomalies",
      slug: "kelly-audit-anomalies",
      description: "Rule-flagged anomalies with evidence, a drafted follow-up, and the review-queue decision",
      readLimit: 100,
      fields: [
        { slug: "anomaly-id", name: "Anomaly ID", type: "text", required: true },
        { slug: "ref", name: "Ref", type: "number", required: false },
        { slug: "rule", name: "Rule", type: "text", required: false },
        { slug: "severity", name: "Severity", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "customer", name: "Customer", type: "text", required: false },
        { slug: "amount-at-stake", name: "Amount at stake", type: "number", required: false },
        { slug: "currency", name: "Currency", type: "text", required: false },
        { slug: "aging-bucket", name: "Aging bucket", type: "text", required: false },
        { slug: "reason", name: "Reason", type: "longtext", required: false },
        { slug: "evidence", name: "Evidence", type: "longtext", required: false },
        { slug: "proposed-action", name: "Proposed action", type: "text", required: false },
        { slug: "draft", name: "Draft", type: "longtext", required: false },
        { slug: "agent-notes", name: "Agent notes", type: "longtext", required: false },
        { slug: "created-at", name: "Created at", type: "text", required: false },
        { slug: "resolved-at", name: "Resolved at", type: "text", required: false },
        { slug: "decision-action", name: "Decision action", type: "text", required: false },
        { slug: "decision-note", name: "Decision note", type: "longtext", required: false },
        { slug: "decided-at", name: "Decided at", type: "text", required: false },
        { slug: "execution-status", name: "Execution status", type: "text", required: false },
        { slug: "execution-operation", name: "Execution operation", type: "text", required: false },
        { slug: "execution-target", name: "Execution target", type: "text", required: false },
        { slug: "execution-detail", name: "Execution detail", type: "longtext", required: false },
        { slug: "executed-at", name: "Executed at", type: "text", required: false },
      ],
    },
    {
      key: "import-log",
      name: "Import Log",
      slug: "kelly-audit-import-log",
      description: "Append-only history of import runs: files, added/updated counts, and row warnings",
      readLimit: 100,
      fields: [
        { slug: "log-id", name: "Log ID", type: "text", required: true },
        { slug: "imported-at", name: "Imported at", type: "text", required: false },
        { slug: "files", name: "Files", type: "longtext", required: false },
        { slug: "added", name: "Added", type: "longtext", required: false },
        { slug: "updated", name: "Updated", type: "longtext", required: false },
        { slug: "warnings", name: "Warnings", type: "longtext", required: false },
      ],
    },
    {
      key: "settings",
      name: "Settings",
      slug: "kelly-audit-settings",
      description: "Company profile, tolerance rules, and import column mappings, a single settings row",
      readLimit: 20,
      fields: [
        { slug: "record-id", name: "Record ID", type: "text", required: true },
        { slug: "company-name", name: "Company name", type: "text", required: false },
        { slug: "contact-email", name: "Contact email", type: "text", required: false },
        { slug: "base-currency", name: "Base currency", type: "text", required: false },
        { slug: "fx-rates", name: "FX rates", type: "longtext", required: false },
        { slug: "days-to-invoice", name: "Days to invoice", type: "number", required: false },
        { slug: "amount-tolerance-pct", name: "Amount tolerance pct", type: "number", required: false },
        { slug: "aging-buckets", name: "Aging buckets", type: "longtext", required: false },
        { slug: "duplicate-window-days", name: "Duplicate window days", type: "number", required: false },
        { slug: "import-orders-columns", name: "Import orders columns", type: "longtext", required: false },
        { slug: "import-invoices-columns", name: "Import invoices columns", type: "longtext", required: false },
        { slug: "import-payments-columns", name: "Import payments columns", type: "longtext", required: false },
      ],
    },
  ],
  permissions: {
    readProcedures: ["nodes.list", "nodes.get", "bases.get", "records.list"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata"],
    writeProcedures: ["records.changeRequest", "bases.createChangeRequest"],
  },
};
