export const appConfig = {
  appId: "kelly-social",
  appName: "Kelly Social",
  deployment: "cloud",
  locale: "auto",
  readOnly: false,
  spaceId: "",
  schemaVersion: 1,
  folder: {
    name: "Kelly Social",
    description: "Social media command desk: cross-platform monitoring plus an ECHO publishing desk",
    nodeId: "",
    slug: "kelly-social",
  },
  airApp: { name: "Kelly Social", slug: "kelly-social-app", resourceKey: "airapp" },
  bases: [
    {
      key: "accounts",
      name: "Accounts",
      slug: "kelly-social-accounts-v1",
      description: "Connected social accounts: platform, handle, collection method, and rolled-up metrics",
      nodeId: "",
      baseId: "",
      readLimit: 50,
      fields: [
        { slug: "account-id", name: "Account ID", type: "text", required: true },
        { slug: "platform", name: "Platform", type: "text", required: false },
        { slug: "handle", name: "Handle", type: "text", required: false },
        { slug: "display-name", name: "Display name", type: "text", required: false },
        { slug: "profile-url", name: "Profile URL", type: "text", required: false },
        { slug: "collection", name: "Collection method", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "notes", name: "Notes", type: "longtext", required: false },
        { slug: "metrics", name: "Metrics", type: "longtext", required: false },
        { slug: "follower-series", name: "Follower series", type: "longtext", required: false },
        { slug: "traffic-sources", name: "Traffic sources", type: "longtext", required: false },
        { slug: "last-sync-at", name: "Last sync at", type: "text", required: false },
      ],
    },
    {
      key: "posts",
      name: "Posts",
      slug: "kelly-social-posts-v1",
      description: "Collected posts across all connected accounts, with per-post engagement metrics",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "post-id", name: "Post ID", type: "text", required: true },
        { slug: "platform", name: "Platform", type: "text", required: false },
        { slug: "account-id", name: "Account ID", type: "text", required: false },
        { slug: "provider-post-id", name: "Provider post ID", type: "text", required: false },
        { slug: "posted-at", name: "Posted at", type: "text", required: false },
        { slug: "type", name: "Type", type: "text", required: false },
        { slug: "text", name: "Text", type: "longtext", required: false },
        { slug: "media", name: "Media", type: "text", required: false },
        { slug: "media-count", name: "Media count", type: "number", required: false },
        { slug: "permalink", name: "Permalink", type: "text", required: false },
        { slug: "metrics", name: "Metrics", type: "longtext", required: false },
        { slug: "engagement-rate", name: "Engagement rate", type: "number", required: false },
        { slug: "agent-notes", name: "Agent notes", type: "longtext", required: false },
        { slug: "tags", name: "Tags", type: "longtext", required: false },
      ],
    },
    {
      key: "sync_log",
      name: "Sync Log",
      slug: "kelly-social-sync-log-v1",
      description: "Append-only history of collection runs per account",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "sync-id", name: "Sync ID", type: "text", required: true },
        { slug: "account-id", name: "Account ID", type: "text", required: false },
        { slug: "method", name: "Method", type: "text", required: false },
        { slug: "started-at", name: "Started at", type: "text", required: false },
        { slug: "completed-at", name: "Completed at", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "posts-collected", name: "Posts collected", type: "number", required: false },
        { slug: "message", name: "Message", type: "longtext", required: false },
        { slug: "actor", name: "Actor", type: "text", required: false },
      ],
    },
    {
      key: "calendar",
      name: "Calendar",
      slug: "kelly-social-calendar-v1",
      description: "Content calendar: scheduled posts across channels by theme pillar and date",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "entry-id", name: "Entry ID", type: "text", required: true },
        { slug: "date", name: "Date", type: "text", required: false },
        { slug: "channel", name: "Channel", type: "text", required: false },
        { slug: "pillar", name: "Pillar", type: "text", required: false },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "draft-id", name: "Draft ID", type: "text", required: false },
        { slug: "scheduled-for", name: "Scheduled for", type: "text", required: false },
        { slug: "notes", name: "Notes", type: "longtext", required: false },
      ],
    },
    {
      key: "drafts",
      name: "Drafts",
      slug: "kelly-social-drafts-v1",
      description: "Post composer / draft review queue, gated by the social-qa quality gate",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "draft-id", name: "Draft ID", type: "text", required: true },
        { slug: "channels", name: "Channels", type: "longtext", required: false },
        { slug: "pillar", name: "Pillar", type: "text", required: false },
        { slug: "hook", name: "Hook", type: "text", required: false },
        { slug: "body", name: "Body", type: "longtext", required: false },
        { slug: "hashtags", name: "Hashtags", type: "longtext", required: false },
        { slug: "cta", name: "CTA", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "scheduled-for", name: "Scheduled for", type: "text", required: false },
        { slug: "agent-notes", name: "Agent notes", type: "longtext", required: false },
        { slug: "review-note", name: "Review note", type: "longtext", required: false },
        { slug: "created-at", name: "Created at", type: "text", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
    {
      key: "shorts",
      name: "Shorts",
      slug: "kelly-social-shorts-v1",
      description: "Short-video scripts for Reels / Shorts / TikTok / Douyin, same five-state review model",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "short-id", name: "Short ID", type: "text", required: true },
        { slug: "channels", name: "Channels", type: "longtext", required: false },
        { slug: "pillar", name: "Pillar", type: "text", required: false },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "hook", name: "Hook", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "duration-s", name: "Duration (s)", type: "number", required: false },
        { slug: "shots", name: "Shots", type: "longtext", required: false },
        { slug: "caption", name: "Caption", type: "text", required: false },
        { slug: "hashtags", name: "Hashtags", type: "longtext", required: false },
        { slug: "agent-notes", name: "Agent notes", type: "longtext", required: false },
        { slug: "review-note", name: "Review note", type: "longtext", required: false },
        { slug: "created-at", name: "Created at", type: "text", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
    {
      key: "engagement",
      name: "Engagement",
      slug: "kelly-social-engagement-v1",
      description: "Incoming mentions/comments with agent-drafted replies, approval-gated",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "item-id", name: "Item ID", type: "text", required: true },
        { slug: "platform", name: "Platform", type: "text", required: false },
        { slug: "account-id", name: "Account ID", type: "text", required: false },
        { slug: "kind", name: "Kind", type: "text", required: false },
        { slug: "author-handle", name: "Author handle", type: "text", required: false },
        { slug: "incoming-text", name: "Incoming text", type: "longtext", required: false },
        { slug: "received-at", name: "Received at", type: "text", required: false },
        { slug: "sentiment", name: "Sentiment", type: "text", required: false },
        { slug: "priority", name: "Priority", type: "text", required: false },
        { slug: "draft-reply", name: "Draft reply", type: "longtext", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "review-note", name: "Review note", type: "longtext", required: false },
        { slug: "permalink", name: "Permalink", type: "text", required: false },
      ],
    },
    {
      key: "settings",
      name: "Settings",
      slug: "kelly-social-settings-v1",
      description: "Crisis playbook, share-of-voice, and other single-row settings, keyed by kind",
      nodeId: "",
      baseId: "",
      readLimit: 20,
      fields: [
        { slug: "record-id", name: "Record ID", type: "text", required: true },
        { slug: "kind", name: "Kind", type: "text", required: true },
        { slug: "name", name: "Name", type: "text", required: false },
        { slug: "payload", name: "Payload", type: "longtext", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
  ],
  permissions: {
    readProcedures: ["nodes.list", "nodes.get", "bases.get", "records.list"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata"],
    writeProcedures: ["records.changeRequest", "bases.createChangeRequest"],
  },
};
