export const appConfig = {
  appId: "kelly-ads",
  appName: "Kelly Ads",
  deployment: "cloud",
  locale: "auto",
  readOnly: false,
  spaceId: "",
  schemaVersion: 1,
  folder: {
    name: "Kelly Ads",
    description:
      "Ad-campaign command desk: Amazon/Meta/TikTok/Google spend and performance, deterministic anomaly detection, and an adjustment-card review queue",
    slug: "kelly-ads",
  },
  airApp: { name: "Kelly Ads", slug: "kelly-ads-app", resourceKey: "kelly-ads-app" },
  bases: [
    {
      key: "platforms",
      name: "Platforms",
      slug: "kelly-ads-platforms",
      description: "Connected ad platform roster: Amazon Ads, Meta, TikTok Ads, Google Ads",
      readLimit: 20,
      fields: [
        { slug: "platform-id", name: "Platform ID", type: "text", required: true },
        { slug: "name", name: "Name", type: "text", required: false },
        { slug: "account-id", name: "Account ID", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "currency", name: "Currency", type: "text", required: false },
        { slug: "last-sync-at", name: "Last sync at", type: "text", required: false },
      ],
    },
    {
      key: "campaigns",
      name: "Campaigns",
      slug: "kelly-ads-campaigns",
      description:
        "One row per campaign: budget, targets, and the daily spend/impressions/clicks/conversions/revenue series",
      readLimit: 100,
      fields: [
        { slug: "campaign-id", name: "Campaign ID", type: "text", required: true },
        { slug: "platform", name: "Platform", type: "text", required: false },
        { slug: "name", name: "Name", type: "text", required: false },
        { slug: "product", name: "Product", type: "text", required: false },
        { slug: "sku", name: "SKU", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "daily-budget", name: "Daily budget", type: "number", required: false },
        { slug: "budget-spent-today-pct", name: "Budget spent today pct", type: "number", required: false },
        { slug: "acos-target-pct", name: "ACOS target pct", type: "number", required: false },
        { slug: "currency", name: "Currency", type: "text", required: false },
        { slug: "daily", name: "Daily", type: "longtext", required: false },
        { slug: "targets", name: "Targets", type: "longtext", required: false },
        { slug: "last-sync-at", name: "Last sync at", type: "text", required: false },
      ],
    },
    {
      key: "anomalies",
      name: "Anomalies",
      slug: "kelly-ads-anomalies",
      description:
        "Deterministic anomaly feed: ACOS breaches, budget burnouts, zero-conversion spend, CPC spikes, rejections",
      readLimit: 100,
      fields: [
        { slug: "anomaly-id", name: "Anomaly ID", type: "text", required: true },
        { slug: "type", name: "Type", type: "text", required: false },
        { slug: "severity", name: "Severity", type: "text", required: false },
        { slug: "state", name: "State", type: "text", required: false },
        { slug: "campaign-id", name: "Campaign ID", type: "text", required: false },
        { slug: "platform", name: "Platform", type: "text", required: false },
        { slug: "target-id", name: "Target ID", type: "text", required: false },
        { slug: "evidence", name: "Evidence", type: "longtext", required: false },
        { slug: "detected-at", name: "Detected at", type: "text", required: false },
        { slug: "first-seen-at", name: "First seen at", type: "text", required: false },
        { slug: "adjustment-id", name: "Adjustment ID", type: "text", required: false },
      ],
    },
    {
      key: "adjustments",
      name: "Adjustments",
      slug: "kelly-ads-adjustments",
      description:
        "Agent-proposed adjustment cards: negative keyword, bid down/up, pause target, budget shift, creative refresh",
      readLimit: 100,
      fields: [
        { slug: "adjustment-id", name: "Adjustment ID", type: "text", required: true },
        { slug: "ref", name: "Ref", type: "number", required: false },
        { slug: "type", name: "Type", type: "text", required: false },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "campaign-id", name: "Campaign ID", type: "text", required: false },
        { slug: "platform", name: "Platform", type: "text", required: false },
        { slug: "reason", name: "Reason", type: "longtext", required: false },
        { slug: "evidence", name: "Evidence", type: "longtext", required: false },
        { slug: "target", name: "Target", type: "longtext", required: false },
        { slug: "current-value", name: "Current value", type: "text", required: false },
        { slug: "proposed-value", name: "Proposed value", type: "text", required: false },
        { slug: "expected-impact", name: "Expected impact", type: "longtext", required: false },
        { slug: "anomaly-id", name: "Anomaly ID", type: "text", required: false },
        { slug: "note", name: "Note", type: "longtext", required: false },
        { slug: "created-at", name: "Created at", type: "text", required: false },
        { slug: "decision-verdict", name: "Decision verdict", type: "text", required: false },
        { slug: "decision-note", name: "Decision note", type: "longtext", required: false },
        { slug: "decided-at", name: "Decided at", type: "text", required: false },
        { slug: "execution-status", name: "Execution status", type: "text", required: false },
        { slug: "execution-operation", name: "Execution operation", type: "text", required: false },
        { slug: "execution-target", name: "Execution target", type: "longtext", required: false },
        { slug: "execution-detail", name: "Execution detail", type: "longtext", required: false },
        { slug: "executed-at", name: "Executed at", type: "text", required: false },
      ],
    },
    {
      key: "sync-log",
      name: "Sync Log",
      slug: "kelly-ads-sync-log",
      description: "Append-only feed: ingest runs, anomaly checks, and execution plans",
      readLimit: 50,
      fields: [
        { slug: "sync-id", name: "Sync ID", type: "text", required: true },
        { slug: "at", name: "At", type: "text", required: false },
        { slug: "platform", name: "Platform", type: "text", required: false },
        { slug: "kind", name: "Kind", type: "text", required: false },
        { slug: "message", name: "Message", type: "longtext", required: false },
        { slug: "rows", name: "Rows", type: "number", required: false },
      ],
    },
    {
      key: "settings",
      name: "Settings",
      slug: "kelly-ads-settings",
      description: "ACOS/ROAS targets and anomaly-detection thresholds, a single settings row",
      readLimit: 20,
      fields: [
        { slug: "record-id", name: "Record ID", type: "text", required: true },
        { slug: "currency", name: "Currency", type: "text", required: false },
        { slug: "default-acos-pct", name: "Default ACOS pct", type: "number", required: false },
        { slug: "default-roas", name: "Default ROAS", type: "number", required: false },
        { slug: "per-platform-targets", name: "Per platform targets", type: "longtext", required: false },
        { slug: "per-product-targets", name: "Per product targets", type: "longtext", required: false },
        { slug: "acos-breach-days", name: "ACOS breach days", type: "number", required: false },
        { slug: "budget-exhausted-pct", name: "Budget exhausted pct", type: "number", required: false },
        { slug: "budget-risk-pct", name: "Budget risk pct", type: "number", required: false },
        { slug: "zero-conversion-spend-floor", name: "Zero conversion spend floor", type: "number", required: false },
        { slug: "cpc-spike-pct", name: "CPC spike pct", type: "number", required: false },
        { slug: "cpc-trailing-days", name: "CPC trailing days", type: "number", required: false },
        { slug: "currency-rates", name: "Currency rates", type: "longtext", required: false },
        { slug: "csv-mappings", name: "CSV mappings", type: "longtext", required: false },
        { slug: "spend-last-month", name: "Spend last month", type: "number", required: false },
      ],
    },
  ],
  permissions: {
    readProcedures: ["nodes.list", "nodes.get", "bases.get", "records.list"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata"],
    writeProcedures: ["records.changeRequest", "bases.createChangeRequest"],
  },
};
