export const appConfig = {
  appId: "kelly-picks",
  appName: "Kelly Picks",
  deployment: "cloud",
  locale: "auto",
  readOnly: false,
  spaceId: "",
  schemaVersion: 1,
  folder: {
    name: "Kelly Picks",
    description:
      "Product-research (选品) desk: trend sweeps, margin cards, competition reads, and a develop/watch/drop review queue",
    slug: "kelly-picks",
  },
  airApp: { name: "Kelly Picks", slug: "kelly-picks-app", resourceKey: "kelly-picks-app" },
  bases: [
    {
      key: "candidates",
      name: "Candidates",
      slug: "kelly-picks-candidates",
      description: "Products under research, with a margin card and competition read JSON-encoded on each row",
      readLimit: 100,
      fields: [
        { slug: "candidate-id", name: "Candidate ID", type: "text", required: true },
        { slug: "name", name: "Name", type: "text", required: false },
        { slug: "category", name: "Category", type: "text", required: false },
        { slug: "source", name: "Source", type: "text", required: false },
        { slug: "source-ref", name: "Source ref", type: "text", required: false },
        { slug: "stage", name: "Stage", type: "text", required: false },
        { slug: "platform-id", name: "Platform ID", type: "text", required: false },
        { slug: "competition-grade", name: "Competition grade", type: "text", required: false },
        { slug: "momentum-pct", name: "Momentum pct", type: "number", required: false },
        { slug: "est-price", name: "Est price", type: "number", required: false },
        { slug: "currency", name: "Currency", type: "text", required: false },
        { slug: "margin-card", name: "Margin card", type: "longtext", required: false },
        { slug: "competition", name: "Competition", type: "longtext", required: false },
        { slug: "evidence", name: "Evidence", type: "longtext", required: false },
        { slug: "why-it-matters", name: "Why it matters", type: "longtext", required: false },
        { slug: "first-seen", name: "First seen", type: "text", required: false },
        { slug: "last-updated", name: "Last updated", type: "text", required: false },
        { slug: "verdict-action", name: "Verdict action", type: "text", required: false },
        { slug: "verdict-comment", name: "Verdict comment", type: "longtext", required: false },
        { slug: "verdict-decided-at", name: "Verdict decided at", type: "text", required: false },
      ],
    },
    {
      key: "trend-items",
      name: "Trend Items",
      slug: "kelly-picks-trend-items",
      description: "Raw source-tagged trend signals from a sweep, optionally linked to a candidate",
      readLimit: 100,
      fields: [
        { slug: "trend-id", name: "Trend ID", type: "text", required: true },
        { slug: "source", name: "Source", type: "text", required: false },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "summary", name: "Summary", type: "longtext", required: false },
        { slug: "url", name: "URL", type: "text", required: false },
        { slug: "metric-label", name: "Metric label", type: "text", required: false },
        { slug: "metric-value", name: "Metric value", type: "number", required: false },
        { slug: "delta-pct", name: "Delta pct", type: "number", required: false },
        { slug: "momentum", name: "Momentum", type: "longtext", required: false },
        { slug: "observed-at", name: "Observed at", type: "text", required: false },
        { slug: "candidate-id", name: "Candidate ID", type: "text", required: false },
        { slug: "external-id", name: "External ID", type: "text", required: false },
        { slug: "content-hash", name: "Content hash", type: "text", required: false },
        { slug: "promotion-action", name: "Promotion action", type: "text", required: false },
        { slug: "promotion-comment", name: "Promotion comment", type: "longtext", required: false },
        { slug: "promotion-decided-at", name: "Promotion decided at", type: "text", required: false },
      ],
    },
    {
      key: "proposals",
      name: "Proposals",
      slug: "kelly-picks-proposals",
      description: "Agent-proposed develop/watch/drop verdicts per candidate, reviewed in the decision queue",
      readLimit: 100,
      fields: [
        { slug: "proposal-id", name: "Proposal ID", type: "text", required: true },
        { slug: "candidate-id", name: "Candidate ID", type: "text", required: false },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "verdict", name: "Verdict", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "reason", name: "Reason", type: "longtext", required: false },
        { slug: "brief", name: "Brief", type: "longtext", required: false },
        { slug: "proposed-at", name: "Proposed at", type: "text", required: false },
        { slug: "review-comment", name: "Review comment", type: "longtext", required: false },
        { slug: "review-decided-at", name: "Review decided at", type: "text", required: false },
      ],
    },
    {
      key: "sources",
      name: "Sources",
      slug: "kelly-picks-sources",
      description: "Configured trend sources: kind, collection method, and sweep freshness",
      readLimit: 100,
      fields: [
        { slug: "source-id", name: "Source ID", type: "text", required: true },
        { slug: "kind", name: "Kind", type: "text", required: false },
        { slug: "name", name: "Name", type: "text", required: false },
        { slug: "method", name: "Method", type: "text", required: false },
        { slug: "last-sweep-at", name: "Last sweep at", type: "text", required: false },
        { slug: "items-7d", name: "Items 7d", type: "number", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
      ],
    },
    {
      key: "sync-log",
      name: "Sync Log",
      slug: "kelly-picks-sync-log",
      description: "Append-only history of ingest/compute/execute runs",
      readLimit: 100,
      fields: [
        { slug: "log-id", name: "Log ID", type: "text", required: true },
        { slug: "at", name: "At", type: "text", required: false },
        { slug: "actor", name: "Actor", type: "text", required: false },
        { slug: "action", name: "Action", type: "text", required: false },
        { slug: "detail", name: "Detail", type: "longtext", required: false },
      ],
    },
    {
      key: "settings",
      name: "Settings",
      slug: "kelly-picks-settings",
      description: "Seller profile, platform fee tables, freight rules, and ad-cost default, a single settings row",
      readLimit: 20,
      fields: [
        { slug: "record-id", name: "Record ID", type: "text", required: true },
        { slug: "base-currency", name: "Base currency", type: "text", required: false },
        { slug: "seller-profile", name: "Seller profile", type: "longtext", required: false },
        { slug: "platforms", name: "Platforms", type: "longtext", required: false },
        { slug: "freight", name: "Freight", type: "longtext", required: false },
        { slug: "ad-cost-default-pct", name: "Ad cost default pct", type: "number", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
  ],
  permissions: {
    readProcedures: ["nodes.list", "nodes.get", "bases.get", "records.list"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata"],
    writeProcedures: ["records.changeRequest", "bases.createChangeRequest"],
  },
};
