export const appConfig = {
  appId: "kelly-lesson",
  appName: "Kelly Lesson",
  deployment: "cloud",
  locale: "auto",
  readOnly: false,
  spaceId: "",
  schemaVersion: 1,
  folder: {
    name: "Kelly Lesson",
    description:
      "Lesson-plan generation and compliance-check desk: plan library, compliance checks, and a review queue",
    slug: "kelly-lesson",
  },
  airApp: { name: "Kelly Lesson", slug: "kelly-lesson-app", resourceKey: "kelly-lesson-app" },
  bases: [
    {
      key: "teachers",
      name: "Teachers",
      slug: "kelly-lesson-teachers",
      description: "Teachers referenced by lesson plans",
      readLimit: 100,
      fields: [
        { slug: "teacher-id", name: "Teacher ID", type: "text", required: true },
        { slug: "name", name: "Name", type: "text", required: false },
        { slug: "subject", name: "Subject", type: "text", required: false },
        { slug: "grades", name: "Grades", type: "longtext", required: false },
      ],
    },
    {
      key: "plans",
      name: "Plans",
      slug: "kelly-lesson-plans",
      description: "Lesson plans — structured sections, workflow status, and the review-queue decision on the same row",
      readLimit: 100,
      fields: [
        { slug: "plan-id", name: "Plan ID", type: "text", required: true },
        { slug: "ref", name: "Ref", type: "number", required: false },
        { slug: "title", name: "Title", type: "text", required: false },
        { slug: "subject", name: "Subject", type: "text", required: false },
        { slug: "grade", name: "Grade", type: "text", required: false },
        { slug: "unit", name: "Unit", type: "text", required: false },
        { slug: "teacher-id", name: "Teacher ID", type: "text", required: false },
        { slug: "source", name: "Source", type: "text", required: false },
        { slug: "status", name: "Status", type: "text", required: false },
        { slug: "compliance-score", name: "Compliance score", type: "number", required: false },
        { slug: "class-length-minutes", name: "Class length minutes", type: "number", required: false },
        { slug: "duration-minutes", name: "Duration minutes", type: "number", required: false },
        { slug: "objectives", name: "Objectives", type: "longtext", required: false },
        { slug: "key-points", name: "Key points", type: "longtext", required: false },
        { slug: "difficulties", name: "Difficulties", type: "longtext", required: false },
        { slug: "materials", name: "Materials", type: "longtext", required: false },
        { slug: "curriculum-refs", name: "Curriculum refs", type: "longtext", required: false },
        { slug: "board-plan", name: "Board plan", type: "longtext", required: false },
        { slug: "homework", name: "Homework", type: "longtext", required: false },
        { slug: "reflection", name: "Reflection", type: "longtext", required: false },
        { slug: "safety-notes", name: "Safety notes", type: "longtext", required: false },
        { slug: "stages", name: "Stages", type: "longtext", required: false },
        { slug: "notes", name: "Notes", type: "longtext", required: false },
        { slug: "compliance-summary", name: "Compliance summary", type: "longtext", required: false },
        { slug: "suggestions", name: "Suggestions", type: "longtext", required: false },
        { slug: "feedback-draft", name: "Feedback draft", type: "longtext", required: false },
        { slug: "decision-action", name: "Decision action", type: "text", required: false },
        { slug: "decision-note", name: "Decision note", type: "longtext", required: false },
        { slug: "decided-at", name: "Decided at", type: "text", required: false },
        { slug: "execution-status", name: "Execution status", type: "text", required: false },
        { slug: "execution-operation", name: "Execution operation", type: "text", required: false },
        { slug: "execution-target", name: "Execution target", type: "text", required: false },
        { slug: "execution-detail", name: "Execution detail", type: "longtext", required: false },
        { slug: "executed-at", name: "Executed at", type: "text", required: false },
        { slug: "created-at", name: "Created at", type: "text", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
    {
      key: "checks",
      name: "Checks",
      slug: "kelly-lesson-checks",
      description: "Per-plan, per-rule compliance check results",
      readLimit: 100,
      fields: [
        { slug: "check-id", name: "Check ID", type: "text", required: true },
        { slug: "plan-id", name: "Plan ID", type: "text", required: false },
        { slug: "rule-id", name: "Rule ID", type: "text", required: false },
        { slug: "severity", name: "Severity", type: "text", required: false },
        { slug: "result", name: "Result", type: "text", required: false },
        { slug: "evidence", name: "Evidence", type: "longtext", required: false },
        { slug: "judged-by", name: "Judged by", type: "text", required: false },
        { slug: "checked-at", name: "Checked at", type: "text", required: false },
      ],
    },
    {
      key: "settings",
      name: "Settings",
      slug: "kelly-lesson-settings",
      description:
        "School profile, template sections, compliance rules, and export preferences — a single settings row",
      readLimit: 20,
      fields: [
        { slug: "record-id", name: "Record ID", type: "text", required: true },
        { slug: "school-name", name: "School name", type: "text", required: false },
        { slug: "school-kind", name: "School kind", type: "text", required: false },
        { slug: "school-term", name: "School term", type: "text", required: false },
        { slug: "class-length-minutes", name: "Class length minutes", type: "number", required: false },
        { slug: "subjects", name: "Subjects", type: "longtext", required: false },
        { slug: "grades", name: "Grades", type: "longtext", required: false },
        { slug: "template-sections", name: "Template sections", type: "longtext", required: false },
        { slug: "compliance-rules", name: "Compliance rules", type: "longtext", required: false },
        { slug: "export-format", name: "Export format", type: "text", required: false },
        { slug: "export-out-dir", name: "Export out dir", type: "text", required: false },
        { slug: "docx-via-agent", name: "DOCX via agent", type: "text", required: false },
        { slug: "feedback-handoff-skill", name: "Feedback handoff skill", type: "text", required: false },
        { slug: "feedback-requires-approval", name: "Feedback requires approval", type: "text", required: false },
      ],
    },
  ],
  permissions: {
    readProcedures: ["nodes.list", "nodes.get", "bases.get", "records.list"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata"],
    writeProcedures: ["records.changeRequest", "bases.createChangeRequest"],
  },
};
