// Domain model for Kelly LLM Gateway: cost/model-governance dashboard over a
// shared LLM gateway. Ported verbatim (same variable names, same order of
// operations, only TS types stripped) from the retired
// app/server/anomalies.ts (computeAnomalies), app/server/decisions.ts
// (recordRolloutDecision/recordAnomalyAck), the rollout overlay in
// app/server/store.ts's attachDerived(), and the per-route
// today/rolling-baseline derivation in lib/data-provider/seed-data.ts's
// buildRoutes(). Read this file before changing anomaly-detection,
// rollout-decision, or cost/error aggregation behavior.
//
// Architectural change from the retired local-file shape: this is a
// direct-manipulation operator dashboard, not a review/approval queue. A
// rollout promote/rollback/hold and an anomaly acknowledgement are written
// straight onto the route's own Busabase record (status/canary_pct/
// rollback_ready/note, and a per-anomaly-kind ack field) instead of a
// separate decisions.json handoff file — the same "reads are always live, no
// separate decisions bucket" simplification used across this batch of
// conversions. calls_today/cost_today/error_rate_today/cost_baseline/
// error_rate_baseline are never stored; they are pure/derived from each
// route's own `daily` series and recomputed on every read. Routes/services/
// models are never created by the AirApp — they enter Busabase through an
// external process (a future gateway usage-API adapter), the same way
// kelly-lead-funnel's leads enter through an upstream sourcing process the
// app doesn't control.

export const ROLLOUT_ACTIONS = ["promote", "rollback", "hold"];
export const DEFAULT_COST_SPIKE_THRESHOLD_PCT = 50;
export const DEFAULT_ERROR_SPIKE_THRESHOLD_PCT = 100;

export function round1(value = 0) {
  return Math.round(value * 10) / 10;
}

export function round2(value = 0) {
  return Math.round(value * 100) / 100;
}

export function round4(value = 0) {
  return Math.round(value * 10000) / 10000;
}

// ---- lib/data-provider/seed-data.ts's per-route today/baseline math, ported
// (generalized to read any stored `daily` series instead of one generated by
// the retired buildDaily()) ----

function baseline(daily = [], key = "cost", excludeToday = true) {
  const rows = excludeToday ? daily.slice(0, -1) : daily;
  if (!rows.length) return 0;
  if (key === "cost") return rows.reduce((sum, d) => sum + d.cost, 0) / rows.length;
  const errorRates = rows.map((d) => (d.calls ? d.errors / d.calls : 0));
  return errorRates.reduce((sum, v) => sum + v, 0) / errorRates.length;
}

// Attaches the derived today/baseline metrics the UI needs on top of a
// normalized route. Pure, recomputed on every read from the route's own
// `daily` series — never persisted.
export function deriveRouteMetrics({
  route_id = "",
  service_id = "",
  model_id = "",
  status = "stable",
  canary_pct = 0,
  rollback_ready = false,
  note = "",
  daily = [],
  cost_spike_ack = null,
  error_spike_ack = null,
  updated_at = "",
} = {}) {
  const todayRow = daily[daily.length - 1] || { calls: 0, cost: 0, errors: 0 };
  const errorRateToday = todayRow.calls ? todayRow.errors / todayRow.calls : 0;
  const costBaseline = baseline(daily, "cost", true);
  const errorRateBaseline = baseline(daily, "errorRate", true);
  return {
    route_id,
    service_id,
    model_id,
    status,
    canary_pct,
    rollback_ready,
    note,
    daily,
    cost_spike_ack,
    error_spike_ack,
    updated_at,
    calls_today: todayRow.calls || 0,
    cost_today: round2(todayRow.cost || 0),
    error_rate_today: round4(errorRateToday),
    cost_baseline: round2(costBaseline),
    error_rate_baseline: round4(errorRateBaseline),
  };
}

// ---- lib/data-provider/seed-data.ts's buildTotals/buildSpendTrend, ported
// verbatim (operating on already-derived routes) ----

export function buildTotals(routes = []) {
  const calls_today = routes.reduce((sum, r) => sum + r.calls_today, 0);
  const cost_today = round2(routes.reduce((sum, r) => sum + r.cost_today, 0));
  const cost_7d_avg = round2(
    routes.reduce((sum, r) => {
      const last7 = (r.daily || []).slice(-7);
      return sum + (last7.length ? last7.reduce((s, d) => s + d.cost, 0) / last7.length : 0);
    }, 0),
  );
  const totalErrors = routes.reduce((sum, r) => {
    const daily = r.daily || [];
    return sum + (daily[daily.length - 1]?.errors || 0);
  }, 0);
  const error_rate_today = calls_today ? round4(totalErrors / calls_today) : 0;
  return { calls_today, cost_today, cost_7d_avg, error_rate_today };
}

export function buildSpendTrend(routes = []) {
  const byDate = new Map();
  for (const route of routes) {
    for (const day of route.daily || []) {
      byDate.set(day.date, round2((byDate.get(day.date) || 0) + day.cost));
    }
  }
  return [...byDate.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([date, cost]) => ({ date, cost: round2(cost) }));
}

// ---- app/server/anomalies.ts, ported verbatim ----

function severityForDelta(deltaPct, highAt) {
  return deltaPct >= highAt ? "high" : "watch";
}

function costAnomalyFor(route, thresholdPct) {
  if (route.cost_baseline <= 0) return null;
  const deltaPct = ((route.cost_today - route.cost_baseline) / route.cost_baseline) * 100;
  if (deltaPct < thresholdPct) return null;
  return {
    id: `cost-spike-${route.route_id}`,
    route_id: route.route_id,
    kind: "cost_spike",
    severity: severityForDelta(deltaPct, thresholdPct * 2),
    baseline: route.cost_baseline,
    actual: route.cost_today,
    delta_pct: round1(deltaPct),
    status: "open",
  };
}

function errorAnomalyFor(route, thresholdPct) {
  if (route.error_rate_baseline <= 0) return null;
  const deltaPct = ((route.error_rate_today - route.error_rate_baseline) / route.error_rate_baseline) * 100;
  if (deltaPct < thresholdPct) return null;
  return {
    id: `error-spike-${route.route_id}`,
    route_id: route.route_id,
    kind: "error_spike",
    severity: severityForDelta(deltaPct, thresholdPct * 2),
    baseline: route.error_rate_baseline,
    actual: route.error_rate_today,
    delta_pct: round1(deltaPct),
    status: "open",
  };
}

/**
 * Compute anomalies for every route: a cost spike and/or an error spike vs
 * the route's own rolling baseline (mean of the preceding days, excluding
 * today). Deterministic, rule-based — never randomness, never an LLM call.
 */
export function computeAnomalies(
  routes = [],
  costThresholdPct = DEFAULT_COST_SPIKE_THRESHOLD_PCT,
  errorThresholdPct = DEFAULT_ERROR_SPIKE_THRESHOLD_PCT,
) {
  if (!Array.isArray(routes)) return [];
  const anomalies = [];
  for (const route of routes) {
    const cost = costAnomalyFor(route, costThresholdPct);
    if (cost) anomalies.push(cost);
    const error = errorAnomalyFor(route, errorThresholdPct);
    if (error) anomalies.push(error);
  }
  const order = { high: 2, watch: 1, info: 0 };
  anomalies.sort((a, b) => (order[b.severity] || 0) - (order[a.severity] || 0) || b.delta_pct - a.delta_pct);
  return anomalies;
}

// Merges each route's stored ack state (cost_spike_ack/error_spike_ack) onto
// the computed anomalies — ported in spirit from attachDerived()'s
// decisions.anomaly_acks merge in the retired app/server/store.ts, now
// reading the ack straight off the route record instead of a separate
// decisions.json.
export function applyAnomalyAcks(anomalies = [], routesById = new Map()) {
  return anomalies.map((anomaly) => {
    const route = routesById.get(anomaly.route_id);
    const ack = anomaly.kind === "cost_spike" ? route?.cost_spike_ack : route?.error_spike_ack;
    if (!ack) return anomaly;
    return { ...anomaly, status: "acknowledged", acknowledged_at: ack.acknowledged_at, ack_note: ack.note };
  });
}

// Deterministic anomaly ids (`cost-spike-<route_id>` / `error-spike-<route_id>`)
// let the UI's ack action recover which route/kind an anomaly id refers to
// without a lookup table.
export function parseAnomalyId(anomalyId = "") {
  if (anomalyId.startsWith("cost-spike-")) {
    return { kind: "cost_spike", route_id: anomalyId.slice("cost-spike-".length) };
  }
  if (anomalyId.startsWith("error-spike-")) {
    return { kind: "error_spike", route_id: anomalyId.slice("error-spike-".length) };
  }
  return { kind: "", route_id: "" };
}

// ---- app/server/decisions.ts + the rollout overlay in
// app/server/store.ts's attachDerived(), combined into one direct write onto
// the route's own record ----

export function applyRolloutDecision(
  {
    route_id = "",
    service_id = "",
    model_id = "",
    status = "stable",
    canary_pct = 0,
    rollback_ready = false,
    note: routeNote = "",
    daily = [],
    cost_spike_ack = null,
    error_spike_ack = null,
    updated_at = "",
  } = {},
  action = "",
  note = "",
  now = new Date().toISOString(),
) {
  if (!ROLLOUT_ACTIONS.includes(action)) throw new Error(`action must be one of ${ROLLOUT_ACTIONS.join("|")}`);
  const next = {
    route_id,
    service_id,
    model_id,
    status,
    canary_pct,
    rollback_ready,
    note: note || routeNote,
    daily,
    cost_spike_ack,
    error_spike_ack,
    updated_at: now,
  };
  if (action === "promote") {
    next.status = "stable";
    next.canary_pct = 100;
    next.rollback_ready = false;
  } else if (action === "rollback") {
    next.status = "rollback";
    next.rollback_ready = false;
  } else if (action === "hold") {
    next.status = "hold";
  }
  return next;
}

// Ported from recordAnomalyAck() (app/server/decisions.ts): writes the ack
// straight onto the route's cost_spike_ack/error_spike_ack field instead of
// a separate decisions.json anomaly_acks bucket.
export function applyAnomalyAck(
  {
    route_id = "",
    service_id = "",
    model_id = "",
    status = "stable",
    canary_pct = 0,
    rollback_ready = false,
    note = "",
    daily = [],
    cost_spike_ack = null,
    error_spike_ack = null,
    updated_at = "",
  } = {},
  kind = "",
  ackNote = "",
  now = new Date().toISOString(),
) {
  const ack = { note: ackNote || "", acknowledged_at: now };
  const next = {
    route_id,
    service_id,
    model_id,
    status,
    canary_pct,
    rollback_ready,
    note,
    daily,
    cost_spike_ack,
    error_spike_ack,
    updated_at: now,
  };
  if (kind === "cost_spike") return { ...next, cost_spike_ack: ack };
  if (kind === "error_spike") return { ...next, error_spike_ack: ack };
  throw new Error(`Unknown anomaly kind: ${kind}`);
}

// ---- Busabase row <-> domain object normalization ----

function parseJsonValue(value, fallback) {
  if (!value) return fallback;
  try {
    const parsed = JSON.parse(String(value));
    return parsed ?? fallback;
  } catch {
    return fallback;
  }
}

export function normalizeRouteRow({
  route_id = "",
  service_id = "",
  model_id = "",
  status = "stable",
  canary_pct = 0,
  rollback_ready = "false",
  note = "",
  daily = "",
  cost_spike_ack = "",
  error_spike_ack = "",
  updated_at = "",
  __recordId = undefined,
  __headCommitId = undefined,
} = {}) {
  return {
    route_id,
    service_id,
    model_id,
    status,
    canary_pct: Number(canary_pct) || 0,
    rollback_ready: String(rollback_ready) === "true",
    note: note || undefined,
    daily: parseJsonValue(daily, []),
    cost_spike_ack: parseJsonValue(cost_spike_ack, null),
    error_spike_ack: parseJsonValue(error_spike_ack, null),
    updated_at,
    __recordId,
    __headCommitId,
  };
}

// Only known field slugs are ever written back — never spread a raw row (it
// also carries __recordId/__headCommitId bookkeeping keys that must not be
// sent as Busabase fields). Every destructured parameter carries a default
// so checkJs never infers a required-but-absent property. Busabase has no
// boolean field type, so rollback_ready is written as a "true"/"false"
// string.
export function baseRouteFields({
  route_id = "",
  service_id = "",
  model_id = "",
  status = "stable",
  canary_pct = 0,
  rollback_ready = false,
  note = "",
  daily = [],
  cost_spike_ack = null,
  error_spike_ack = null,
  updated_at = "",
} = {}) {
  return {
    route_id,
    service_id,
    model_id,
    status,
    canary_pct: Number(canary_pct) || 0,
    rollback_ready: rollback_ready ? "true" : "false",
    note: note || "",
    daily: JSON.stringify(daily || []),
    cost_spike_ack: cost_spike_ack ? JSON.stringify(cost_spike_ack) : "",
    error_spike_ack: error_spike_ack ? JSON.stringify(error_spike_ack) : "",
    updated_at,
  };
}

export function normalizeServiceRow({ service_id = "", display_name = "", team = "" } = {}) {
  return { service_id, display_name, team };
}

export function normalizeModelRow({ model_id = "", display_name = "", provider = "", tier = "external" } = {}) {
  return { model_id, display_name, provider, tier };
}

// Ported in spirit from summarizeConfig() in the retired app/server/store.ts;
// `payload` is the parsed Settings row's JSON. There is no server-side env
// check in the browser, so this only ever reports non-secret metadata — it
// never claims credential readiness.
export function buildConfigSummary(payload = {}) {
  return {
    config_path: "busabase:base/kelly-llm-gateway-settings-v1",
    is_example: false,
    base_currency: payload.base_currency || "USD",
    cost_spike_threshold_pct: Number(payload.cost_spike_threshold_pct ?? DEFAULT_COST_SPIKE_THRESHOLD_PCT),
    error_spike_threshold_pct: Number(payload.error_spike_threshold_pct ?? DEFAULT_ERROR_SPIKE_THRESHOLD_PCT),
    gateway: {
      region: payload.gateway?.region || "",
      base_url: payload.gateway?.base_url || "",
      api_key_env: payload.gateway?.api_key_env || "",
    },
  };
}

// Builds the { services, models, routes, totals, spend_trend, anomalies,
// warnings } snapshot shape app.js renders: derives today/baseline metrics
// for every route, rolls up totals and the spend trend, computes anomalies
// against the config's thresholds, and merges in each anomaly's stored ack
// state. Ported in spirit from the retired app/server/store.ts's
// readSnapshot()+attachDerived() pipeline, now a single pure function over
// already-read Busabase rows instead of a local snapshot.json read.
export function buildSnapshot({
  services = [],
  models = [],
  routes = [],
  configSummary: {
    base_currency = "USD",
    cost_spike_threshold_pct = DEFAULT_COST_SPIKE_THRESHOLD_PCT,
    error_spike_threshold_pct = DEFAULT_ERROR_SPIKE_THRESHOLD_PCT,
  } = {},
  generatedAt = new Date().toISOString(),
} = {}) {
  const costThreshold = Number(cost_spike_threshold_pct ?? DEFAULT_COST_SPIKE_THRESHOLD_PCT);
  const errorThreshold = Number(error_spike_threshold_pct ?? DEFAULT_ERROR_SPIKE_THRESHOLD_PCT);
  const derivedRoutes = routes.map(deriveRouteMetrics);
  const totals = buildTotals(derivedRoutes);
  const spend_trend = buildSpendTrend(derivedRoutes);
  const rawAnomalies = computeAnomalies(derivedRoutes, costThreshold, errorThreshold);
  const routesById = new Map(derivedRoutes.map((route) => [route.route_id, route]));
  const anomalies = applyAnomalyAcks(rawAnomalies, routesById);
  return {
    schema_version: "1",
    snapshot_id: `gateway-${String(generatedAt).slice(0, 10)}`,
    generated_at: generatedAt,
    source: "kelly-llm-gateway",
    base_currency: base_currency || "USD",
    services,
    models,
    routes: derivedRoutes,
    totals,
    spend_trend,
    anomalies,
    warnings: [],
  };
}
