import { createHash } from "node:crypto";

export const BUSABASE_SCHEMA = {
  provider: "busabase",
  schema_id: "kelly-email.storage",
  schema_version: "3",
  folder: {
    default_slug: "kelly-email-workspace",
    name: "Kelly Email",
    children: ["base", "contacts_base", "drive"],
  },
  base: {
    default_id: "kelly-email",
    default_slug: "kelly-email",
    name: "Kelly Email Emails",
    record_kinds: ["review_item", "reply_draft", "execution_report"],
    fields: [
      "record_id",
      "kind",
      "batch_id",
      "item_id",
      "email_uid",
      "thread_id",
      "message_id",
      "folder",
      "subject",
      "sender",
      "sender_contact_id",
      "sender_email",
      "sender_domain",
      "recipients",
      "recipient_contact_ids",
      "recipient_emails",
      "cc",
      "source_account",
      "email_date",
      "category",
      "risk",
      "reason",
      "summary",
      "review_background",
      "review_recommendation",
      "review_why",
      "body_text",
      "body_original",
      "body_translation",
      "body_excerpt",
      "quote_preview",
      "html_excerpt",
      "draft_text",
      "suggested_reply",
      "draft_excerpt",
      "user_comment",
      "decision_action",
      "decided_at",
      "execution_status",
      "mailbox_operation",
      "target_folder",
      "executed_at",
      "execution_reason",
      "execution_error",
      "has_html",
      "has_draft",
      "has_translation",
      "has_attachments",
      "drive_path",
      "html_drive_path",
      "attachments_drive_path",
      "attachment_count",
      "attachment_names",
      "attachment_refs",
      "classification_method",
      "user_language",
      "source_language",
      "body_original_language",
      "body_translation_language",
      "status",
      "proposed_action",
      "updated_at",
      "created_at",
      "report",
      "latest_record_id",
    ],
  },
  contacts_base: {
    default_id: "kelly-email-contacts",
    default_slug: "kelly-email-contacts",
    name: "Kelly Email Contacts",
    record_kinds: ["email_contact"],
    fields: [
      "record_id",
      "kind",
      "contact_id",
      "email",
      "display_name",
      "domain",
      "roles",
      "source_accounts",
      "first_seen_at",
      "last_seen_at",
      "message_count",
      "last_subject",
      "last_message_id",
      "last_batch_id",
      "last_status",
      "last_proposed_action",
      "category_counts",
      "risk_tags",
      "notes",
      "default_action",
      "updated_at",
      "created_at",
    ],
  },
  drive: {
    default_id: "kelly-email-files",
    default_slug: "kelly-email-workspace-files",
    config_files: ["config/config.json"],
    state_files: ["state/schema.json", "state/lock.json", "state/scan_state.json"],
    compat_files: ["state/current_batch.json", "state/decisions.json"],
    roots: ["config", "state", "batches", "attachments", "imports", "exports", "reports"],
  },
  secrets: {
    namespace: "kelly-email",
    provider: "busabase-vault",
    refs: ["KELLY_EMAIL_IMAP_*", "KELLY_EMAIL_SMTP_*", "KELLY_EMAIL_BUSABASE_API_KEY"],
  },
} as const;

export const BUSABASE_LEGACY_RECORDS = {
  current_batch: "kelly-email-current-batch",
  decisions: "kelly-email-decisions",
} as const;

export function schemaFingerprint() {
  return createHash("sha256").update(JSON.stringify(BUSABASE_SCHEMA)).digest("hex");
}
