export const appConfig = {
  appId: "kelly-family-fund",
  appName: "Kelly Family Fund",
  deployment: "cloud",
  locale: "auto",
  readOnly: true,
  spaceId: "",
  schemaVersion: 1,
  folder: {
    name: "Kelly Family Fund",
    description: "Household pooled-pension / elder-care fund ledger and fairness dashboard",
    nodeId: "",
    slug: "kelly-family-fund",
  },
  bases: [
    {
      key: "beneficiaries",
      name: "Beneficiaries",
      slug: "kelly-family-fund-beneficiaries-v1",
      description: "The elders whose pensions are pooled",
      nodeId: "",
      baseId: "",
      readLimit: 20,
      fields: [
        { slug: "beneficiary-id", name: "Beneficiary ID", type: "text", required: true },
        { slug: "name", name: "Name", type: "text", required: false },
        { slug: "relation", name: "Relation", type: "text", required: false },
        { slug: "pension-monthly", name: "Pension monthly", type: "number", required: false },
      ],
    },
    {
      key: "families",
      name: "Families",
      slug: "kelly-family-fund-families-v1",
      description: "The sibling families that share the fund surplus",
      nodeId: "",
      baseId: "",
      readLimit: 20,
      fields: [
        { slug: "family-id", name: "Family ID", type: "text", required: true },
        { slug: "name", name: "Name", type: "text", required: false },
        { slug: "head", name: "Head", type: "text", required: false },
        { slug: "members-count", name: "Members count", type: "number", required: false },
        { slug: "note", name: "Note", type: "text", required: false },
      ],
    },
    {
      key: "income",
      name: "Income",
      slug: "kelly-family-fund-income-v1",
      description: "Monthly pension inflow per beneficiary",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "income-id", name: "Income ID", type: "text", required: true },
        { slug: "month", name: "Month", type: "text", required: false },
        { slug: "beneficiary-id", name: "Beneficiary ID", type: "text", required: false },
        { slug: "amount", name: "Amount", type: "number", required: false },
        { slug: "note", name: "Note", type: "text", required: false },
      ],
    },
    {
      key: "expenses",
      name: "Expenses",
      slug: "kelly-family-fund-expenses-v1",
      description: "Care cost and family-benefiting expenses",
      nodeId: "",
      baseId: "",
      readLimit: 100,
      fields: [
        { slug: "expense-id", name: "Expense ID", type: "text", required: true },
        { slug: "month", name: "Month", type: "text", required: false },
        { slug: "date", name: "Date", type: "text", required: false },
        { slug: "category", name: "Category", type: "text", required: false },
        { slug: "amount", name: "Amount", type: "number", required: false },
        { slug: "payee", name: "Payee", type: "text", required: false },
        { slug: "occasion", name: "Occasion", type: "text", required: false },
        { slug: "family-id", name: "Family ID", type: "text", required: false },
        { slug: "shared", name: "Shared", type: "text", required: false },
        { slug: "note", name: "Note", type: "text", required: false },
      ],
    },
    {
      key: "settings",
      name: "Settings",
      slug: "kelly-family-fund-settings-v1",
      description: "Fund meta, fairness threshold, and onboarding marker",
      nodeId: "",
      baseId: "",
      readLimit: 20,
      fields: [
        { slug: "record-id", name: "Record ID", type: "text", required: true },
        { slug: "kind", name: "Kind", type: "text", required: true },
        { slug: "name", name: "Name", type: "text", required: false },
        { slug: "payload", name: "Payload", type: "longtext", required: false },
        { slug: "updated-at", name: "Updated at", type: "text", required: false },
      ],
    },
  ],
  permissions: {
    readProcedures: ["nodes.list", "nodes.get", "bases.get", "records.list"],
    setupProcedures: ["nodes.createChangeRequest", "nodes.updateMetadata"],
    writeProcedures: [],
  },
};
